### ISSUE TITLE
Document Sass version

### ISSUE THREAD

**Issue by demurgos** [Keats/gutenberg#1619]
# Documentation issue

## Summary
What is the issue? Is the documentation unclear? Is it missing information?

The documentation should state which version of Sass is used to compile the stylesheets. In my case I wanted to use the `@use` directive but then noticed it wasn't supported.

## Proposed solution
A quick explanation of what you would like to see to solve the issue.
If you want to add content, please explain what you were looking for and what was
your process while looking at the current documentation.

The situation with Sass is pretty complex. The official documentation recognizes 3 implementations:  Dart Sass, LibSass and Ruby Sass. In particular, most features have a compatibility note similar to the following examples:

> Compatibility: Dart Sass since 1.23.0 LibSass ✗ Ruby Sass ✗

<sup>https://sass-lang.com/documentation/at-rules/use</sup>

> Compatibility: Dart Sass ✓ LibSass since 3.6.0 Ruby Sass since 3.6.0

<sup>https://sass-lang.com/documentation/at-rules/import#index-files</sup>

Zola does not use any of these implementations directly, instead it uses [sass-rs](https://github.com/compass-rs/sass-rs).

`sass-rs` is based on LibSass, its `README.md` states that it supports LibSass 3.6.4.

As you see, the whole situation is pretty messy and it's really hard to figure our which Sass features are actually supported by Zola.

I would recommend adding something like the following line to [the Sass documentation](https://www.getzola.org/documentation/content/sass/):

```
Zola $zolaVersion renders Sass files with [`sass-rs`](https://github.com/compass-rs/sass-rs) $sassRsVersion,
compatible with [LibSass](https://github.com/sass/libsass) $libSassVersion.
```

For the current release, it would read something like:

> Zola 0.14.1 renders Sass files with [`sass-rs`](https://github.com/compass-rs/sass-rs) 0.2.2, compatible with [LibSass](https://github.com/sass/libsass) 3.6.4.

**Comment by Keats** [comment]
The plan is https://github.com/getzola/zola/issues/1535
Libsass is a pain to build and will be dropped soon but as you mentioned it's tricky to explain which features are supported and which are not. Both rsass and grass are based on dartsass but not fully compatible yet.

> sass-rs is based on LibSass but its CHANGELOG.md is pretty poor so it is not clear which which release uses which version of LibSass. 

Isn't that answered by the first line of the README?

Overall +1 on adding that to the documentation

**Comment by demurgos** [comment]
> Isn't that answered by the first line of the README?

I was so lost in trying to find the version used by `sass-rs` that I missed it. You are right: it states that it supports LibSass 3.6.4.
(I edited the original message.)

I am very glad to hear that there are plans to move to a more recent version of Sass. I still hope that it will be documented: I expect `rsass` to not always be at feature parity.
