### ISSUE TITLE
Error: Failed to open 'config.toml'

### ISSUE THREAD

**Issue by zzzhenng** [Keats/gutenberg#1621]
zola version 0.41.1
os: centos 7

When I run `zola -c config.toml  build`, the following error is returned.

> Checking site...
Failed to check the site
Error: Failed to load config
Reason: Failed to open 'config.toml'
Reason: No such file or directory (os error 2)

The config.toml file is in the current directory and is readable.
Has anyone encountered this problem?

I found that it will find the configuration file in the `/var/lib/snapd/void` directory instead of using the configuration file in the current directory.

**Comment by Keats** [comment]
Can you try with the `next` branch? There has been a patch to fix some issues around config.toml
