### ISSUE TITLE
Asciidoc support

### ISSUE THREAD

**Issue by jakobneufeld** [Keats/gutenberg#1625]
Does zola support asciidoc. I like it a lot, and it would be nice. Emacs org mode, is also cool. but AsciiDoc is an easy formatto parse.

**Comment by Keats** [comment]
It's not supported currently but it would probably be the only other format I'd like to have with Markdown. I don't think there is a good Rust crate, and any additional format support will come way way later, when all the big features (i18n, backlinks etc) are implemented in Zola.

**Comment by lazyzyf** [comment]
still not supported yet?

**Comment by Keats** [comment]
Nope, and at this point the ship has sailed

**Comment by damccull** [comment]
Why has the ship sailed?

**Comment by Keats** [comment]
Still no asciidoc parser in Rust and its popularity didn't really go up in recent years

**Comment by nc7s** [comment]
I really wanted to switch from hugo but was turned down by lack of asciidoc support. FWIW, hugo supports asciidoc by calling out to asciidoctor; I see what the markdown component does is essentially transforming shortcodes then rendering markdown to HTML, so _maybe_, we can too call out to asciidoctor?

**Comment by antoyo** [comment]
There are now a few options of Rust parser for asciidoc:

 * https://github.com/scouten/asciidoc-parser
 * https://github.com/jaredh159/asciidork
 * https://github.com/nlopes/acdc/tree/main/acdc-parser
 * https://github.com/delfanbaum/asciidocr

Not sure what's their maturity or which one is more complete, though.
