### ISSUE TITLE
`TaxonomyConfig` seems to be lacking `permalink`

### ISSUE THREAD

**Issue by TeFiLeDo** [Keats/gutenberg#1627]
# Bug Report

## Environment

Zola version: `zola 0.14.1`

## Expected Behavior
I try to link to the taxonomy list from a term page (`single.html`). For that I want to use `taxonomy.permalink`, as documented [here](https://www.getzola.org/documentation/templates/taxonomies/#single-term-single-html).

The expected behaviour is that this provides me with the link to the taxonomy.

## Current Behavior
When accessing `taxonomy.permalink` I instead get this error:
```
Failed to build the site
Error: Failed to render single term test page.
Reason: Failed to render 'test/single.html'
Reason: Variable `taxonomy.permalink` not found in context while rendering 'test/single.html'
```

## Step to reproduce
- `zola init`
- add a taxonomy to `config.toml`
- add page with taxonomy
- create templates for taxonomy
- access `taxonomy.permalink` in `single.html`

**Comment by timharek** [comment]
This seems to be the case.

You can acheive the same result by;
```html
{% set full_taxonomy = get_taxonomy(kind=taxonomy.name) %}
{% set taxonomy_url = full_taxonomy.permalink %}
```

Then you will have the correct `permalink` in your `single.html`.

**Comment by Keats** [comment]
That should be an easy fix if someone wants to try

**Comment by mwcz** [comment]
I'll take a look (the day after...) tomorrow.

**Comment by mwcz** [comment]
I looked into this a bit.  I don't have a fix yet but I think I found the cause.  `TaxonomyConfig` doesn't contain `lang` or `permalink` as the documentation suggests.  Here are some notes.

There are two `Taxonomy` structs in Zola:

 - a "parent" `Taxonomy` struct in [components/config/src/config/taxonomies.rs](https://github.com/getzola/zola/blob/2aac1633eeed28c516c34f84193db1d5728c8e46/components/config/src/config/taxonomies.rs).  Fields: `kind`, `lang`, `slug`, `permalink`, `items`.  The `kind` field's type is the other `Taxonomy` struct...
 - a "config" `Taxonomy` struct in [components/library/src/taxonomies/mod.rs](https://github.com/getzola/zola/blob/2aac1633eeed28c516c34f84193db1d5728c8e46/components/library/src/taxonomies/mod.rs#L130-L137) which is usually used `as TaxonomyConfig`.  Fields: `name`, `paginate_by`, `paginate_path`, `feed`.

The second one, `TaxonomyConfig` is always passed to tera in the `"taxonomy"` context, which explains why `lang` and `permalink` are missing.  `slug` and `items` from the first struct aren't documented as being available in templates, but seem like they could be useful.

I'd like to propose explicitly renaming the second struct to `TaxonomyConfig` to clear up confusion around its type, and remove the need for `use Taxonomy as TaxonomyConfig` each time its imported.

But as for making `permalink`'s availability match the documentation, is there a way with Tera to piecemeal-add more fields to an existing context?  Something like...

```rust
context.insert("taxonomy", &self.kind);
context.append("taxonomy", "permalink", &self.permalink); // add .permalink to the existing taxonomy context
```

Alternatively, we could move `permalink` and `lang` into `TaxonomyConfig`.  Should we make a new `TaxonomyContext` struct with the exact fields that should be passed into tera?

**Comment by Keats** [comment]
> is there a way with Tera to piecemeal-add more fields to an existing context? Something like...

Not possible like that. You can write some temp struct that will hold all the data like many places in Zola do.

Taxonomies are probably one of the least efficient/most confusing part of Zola, I would probably wait for the work on 0.16 to start to clean this up properly. It should happen soon, just need one more bugfix release before that.

**Comment by Keats** [comment]
So I've just updated the docs on next to remove `lang`/`permalink` from `TaxonomyConfig`. In practice, you always have the lang/permalink when you get a taxonomy so it would be redundant to add them imo.
