### ISSUE TITLE
Generic taxonomy template

### ISSUE THREAD

**Issue by marcodpt** [Keats/gutenberg#1630]
This is by far in my opinion the best static site generator that i worked with.

Thanks a lot for the awesome work!

In the documentation it says : 
Zola will look up the following files in the templates directory:

    $TAXONOMY_NAME/single.html
    $TAXONOMY_NAME/list.html

I want to know if it is possible to use a fallback to ./single.html and ./list.html in case $TAXONOMY_NAME is not present.
For example, look at this theme:
[Zulma](https://github.com/Worble/Zulma/tree/master/templates)

It would work out of the box perfectly with a **movie** site with **directors** and **release** instead of **authors**, **catogories** and **tags**

Themes working out of the box to most use cases imaginable is a great thing for a static site generator

**Comment by Keats** [comment]
Thanks!

This is not possible currently but I agree it would make sense.

**Comment by BezPowell** [comment]
> Thanks!
> 
> This is not possible currently but I agree it would make sense.

I've just had a go at implementing this, and while it does work, the code is a bit messy. It also relies on running a string.ends_with() each time render_template() is called which I imagine would slow it down. My updated code for render_template() is below, if there's some interest in merging it I am happy to open a pull request.
```
pub fn render_template(
    name: &str,
    tera: &Tera,
    context: Context,
    theme: &Option<String>,
) -> Result<String> {
    // check if it is in the templates
    if tera.templates.contains_key(name) {
        return tera.render(name, &context).map_err(std::convert::Into::into);
    }

    // check if it is part of a theme
    if let Some(ref t) = *theme {
        let theme_template_name = format!("{}/templates/{}", t, name);
        if tera.templates.contains_key(&theme_template_name) {
            return tera.render(&theme_template_name, &context).map_err(std::convert::Into::into);
        }
    }

    // check if it is part of ZOLA_TERA defaults
    let default_name = format!("__zola_builtins/{}", name);
    if tera.templates.contains_key(&default_name) {
        return tera.render(&default_name, &context).map_err(std::convert::Into::into);
    }

    // check if it is a taxonomy list
    if name.ends_with("list.html") {
        // Check for generic list.html
        if tera.templates.contains_key("list.html") {
            return tera.render("list.html", &context).map_err(std::convert::Into::into);
        }
        // Check for theme generic list.html
        else if let Some(ref t) = *theme {
            let theme_template_name = format!("{}/templates/list.html", t);
            if tera.templates.contains_key(&theme_template_name) {
                return tera
                    .render(&theme_template_name, &context)
                    .map_err(std::convert::Into::into);
            }
        }
    }

    // check if it is a single taxonomy entry
    if name.ends_with("single.html") {
        // Check for generic single.html
        if tera.templates.contains_key("single.html") {
            return tera.render("single.html", &context).map_err(std::convert::Into::into);
        }
        // Check for theme generic single.html
        else if let Some(ref t) = *theme {
            let theme_template_name = format!("{}/templates/single.html", t);
            if tera.templates.contains_key(&theme_template_name) {
                return tera
                    .render(&theme_template_name, &context)
                    .map_err(std::convert::Into::into);
            }
        }
    }

    // maybe it's a default one?
    match name {
        "index.html" | "section.html" => render_default_tpl!(
            name,
            "https://www.getzola.org/documentation/templates/pages-sections/#section-variables"
        ),
        "page.html" => render_default_tpl!(
            name,
            "https://www.getzola.org/documentation/templates/pages-sections/#page-variables"
        ),
        "single.html" | "list.html" => {
            render_default_tpl!(name, "https://www.getzola.org/documentation/templates/taxonomies/")
        }
        _ => bail!("Tried to render `{}` but the template wasn't found", name),
    }
}
```
Though I suspect that even if that approach was acceptable, splitting out some of the checks into other functions would be a good idea to avoid repeating logic.

**Comment by Keats** [comment]
You need to do the template check before calling render_template, in the taxonomy handling code. This ways you can do it once per taxonomy

**Comment by BezPowell** [comment]
Thanks Keats. I tried that initially, but the fallback didn't work when using a paginator. I'll have another crack at it soon and see whether I can figure it out.

**Comment by timharek** [comment]
Hasn't this been added @Keats? 
In my setup I have fallback templates called `taxonomy_list.html` and `taxonomy_single.html`, and those work perfectly fine now 😄

**Comment by Keats** [comment]
Ah yes, i forgot to close it. Thanks for the ping
