### ISSUE TITLE
Allow "text" as a syntax highlighting language

### ISSUE THREAD

**Issue by ericseppanen** [Keats/gutenberg#1633]
# Bug Report

I frequently use this syntax to disable syntax highlighting. It works on other markdown implementations (e.g. github):
````
```text
some text here
```
````

The `text` language is the one I've seen recommended most frequently.

Zola only allows `txt` for this purpose.  Would it be possible to allow `text` as well?

## Environment

Zola version: 0.14.1

## Expected Behavior
Using `text` syntax highlighting is disabled.

## Current Behavior

When I run `zola build` I get many warnings of the form
```text
Warning: Highlight language text not found in foo.md
```

**Comment by mwcz** [comment]
I could be wrong, but I think that change would need to be made in [sublimehq/Packages/blob/master/Text/Plain text.tmLanguage](https://github.com/sublimehq/Packages/blob/master/Text/Plain%20text.tmLanguage).

**Comment by Keats** [comment]
You can probably add an alias in https://github.com/getzola/zola/blob/master/components/config/examples/generate_sublime.rs but tbh there's already `txt` so I'm inclined to not add `text`
