### ISSUE TITLE
Get section with a given lang.

### ISSUE THREAD

**Issue by pcoves** [Keats/gutenberg#1637]
The [`get_section`](https://www.getzola.org/documentation/templates/overview/#get-section) function *only* takes a `path`.

So, I **know** that the `path` has the language embedded, can't argue with that.
But, sometime, it'd be really handy to ask for section in a given language without having to build a `path` beforehand.

At the moment, I rely on the following code:

```
    {% set section = get_section(path=get_section(path="_index.md") | get(key="translations") | filter(attribute="lang", value=lang) | first | get(key="path")) %}
```

Obviously, this would fail if the given section in the given language does not exists.
So would `get_section(path="_index.md", lang=lang)` and I'm fine with it.

Is this something stupid to ask and should I stick to my ad-hoc code?

Many thanks in advance!
> P.

**Comment by Keats** [comment]
Can you somehow do some string manipulations on the path if you have the lang?
Something like
```
{% set path = "_index.md" %}
{% set pre_path = path | split(pat=".") | first %}
{{ pre_path ~ "." ~ lang ~ ".md" }}
```

**Comment by pcoves** [comment]
Sure thing, my first version looked a bit like yours.
I just happen to like one-liners (I know, bad right, still, they look *smarter*).

By opening this issue I was more wondering if such a feature would make any sense.
Like, if one calls `get_section` on a non-existing section, an error happens.
Why not adding this `lang` option as well which would fail the same way if needed?

Regards

> P.

**Comment by Keats** [comment]
> I just happen to like one-liners (I know, bad right, still, they look smarter).

This one is much less efficient though as you serialize a section and clone a few things multiple times vs a string concatenation.
I'm hesitant of adding the lang param since the `path` parameters refers to the physical path but I think it *should* be fine

**Comment by pcoves** [comment]
Agreed: IMHO it *looks* smarter but it *is* dumber.

Well, I'd love to see this feature in `zola` if you're ok with it.
Also, I'm pretty sure the *path* manipulation part would be more efficient on the `rust` side.

Regards

> P.

**Comment by pcoves** [comment]
I close here.

The *manual* way works just fine.
I reverted to *smart* multi-liners and am happy with it after all.
