### ISSUE TITLE
zola serve doesn't work with (all) non-ascii paths

### ISSUE THREAD

**Issue by jplatte** [Keats/gutenberg#1639]
# Bug Report

The changelog for 0.13 says

> * Fix `zola serve` having issues with non-ascii paths

but this doesn't seem to be truly fixed.

## Environment

Zola version: 0.14.1

## Expected Behavior

`zola serve` serving the non-ascii pages fine, like other webservers.

## Current Behavior

A page containing `ä` is not accessible with `zola serve` while being accessible with nginx or `python3 -m http.server`.

## Step to reproduce

Check out https://gitlab.com/flipdot/nusite, in particular `content/projekte/cnc-fräse.md`. It [works on GitLab pages](https://nusite.flipdot.org/projekte/cnc-fr%C3%A4se/) or when running `python3 -m http.server` in the build directory created by `zola build`, but with `zola serve` you get a 404.

**Comment by Keats** [comment]
It might be an issue with https://github.com/getzola/zola/blob/next/src/cmd/serve.rs#L78 ?

**Comment by jplatte** [comment]
Seems likely. I'll add some logging and check what happens.

**Comment by jplatte** [comment]
That is not the issue, decoding works but the lookup of `path` in `SITE_CONTENT` fails. I'll investigate further.

**Comment by jplatte** [comment]
Okay, so I was testing with an outdated version of the site where that page didn't exist yet 🤦🏼

It turns out I can't even reproduce this on the machine I'm currently using. I'll close ths and investigate further / hopefully post a PR with a fix if I encounter this again.
