### ISSUE TITLE
Strongly typed Tera alternative

### ISSUE THREAD

**Issue by broccolihighkicks** [Keats/gutenberg#1647]
Hello,

Is there an alternative to the Tera template engine?

The main issue is that I do not want to learn the language (functions, arguments  and data types), if possible.

I know Rust, and would prefer to be able to just write a strongly typed Rust function for each template that is needed that takes the context as function args, and returns the HTML string. This would enable me to use the IDE suggestions for functions, args and data types.

Would WASM based themes be possible, where Zola dynamically reads and runs a WASM module which represents the functions that can generate the HTML output from data input?

**Comment by Keats** [comment]
You can try https://github.com/djc/askama

Tera is often used for user-defined templates so it's not really the usecase

**Comment by broccolihighkicks** [comment]
Thanks, would I have to fork Zola and add that to use something like that?

**Comment by Keats** [comment]
No, for Zola you can't use compiled templates like that. At this point it would be easier to build your own custom SSG
