### ISSUE TITLE
Accessing extra data from paginated section?

### ISSUE THREAD

**Issue by sztomi** [Keats/gutenberg#1648]
zola version: 0.14.1

In the front matter for a paginated section's _index.md I added an extra data field:

```
+++
paginate_by = 50
sort_by = "weight"

[extra]
hero_text = "Hello this is my text"
+++
```

I've tried accessing this field in a template as:

  * `section.extra.hero_text` 
  * `paginator.extra.hero_text`
  * `section.hero_text`

but none of those work. Is this not how that's supposed to be accessed? The documentation mentions an `extra` field for section so I thought this should work.

**Comment by sztomi** [comment]
Sorry I just realized that this is better suited for the forum. Moving there.

**Comment by sirodoht** [comment]
This moved here: https://zola.discourse.group/t/accessing-extra-data-from-section-template/1076
