### ISSUE TITLE
Initialization of Dictionaries/Objects?

### ISSUE THREAD

**Issue by Ssloto** [Keats/gutenberg#1654]
Hi!

For a few of the more complicated functions on my site, I'm interested in being able to use shortcodes that take more complicated input, e.g a dictionary/JSON object, or the TOML equivalent.

It's easy enough for me to define these in the header, like
`[extra.example]
place = "null island"
longitude = 0
latitude = 0`

or something like:

`[extra]
example = {  place = "null island", longitude = 0, latitude = 0 }́

But, I can't define variables within shortcodes that evaluate to this type, nor can I write them in line in functions.

Within a markdown file, `foo(input=page.extra.example)` works out okay for either of the two inputs (the first would make more sense with multiple entries, but w/e), however it is invalid in zola for me to write `foo(input= {  place = "null island", longitude = 0, latitude = 0 }})`, or any permutation that I'm aware of.

I feel like it's kind of inconsistent/annoying that I can initialize this data structure in the header, but not inline. Is this an intentional/philosophical choice, or just an edge case I'm running up against? :)

The main reason I would want to do this is so I could use an array of objects as an input to a shortcode, which could have optional attributes, and which are much cleaner to keep bunched together, than say, input as a set of lists where each index corresponds to a single item. 

I.e., a place could have a picture or something, but not necessarily.

**Comment by Keats** [comment]
It's more of a https://github.com/keats/tera issue, it doesn't support dict defintion

**Comment by Ssloto** [comment]
Ahhh that makes sense. Thanks.
