### ISSUE TITLE
newline inside shortcode body generates a paragraph

### ISSUE THREAD

**Issue by Geal** [Keats/gutenberg#1655]
# Bug Report

I have a HTML shortcode I want to use to display code examples, but not using Zola's builtin highlighting, because I need more features, like in browser execution with wasm, and I'm using a web component providing that.
I want to use the shortcode's body to hold the code. Unfortunately, every time I add an empty line in the example code, zola generates a paragraph. This is really puzzling :sweat_smile: 

The shortcode:

```html
<bc-authorizer-example>        
  <code>{{ body | safe}}</code>
</bc-authorizer-example>       
```

the page (I'm writing that in the `content` part of my index page):

```
{% examplecode %}
some code;
more code;

other code here;
{% end %}
```

The generated HTML:

```
<bc-authorizer-example>        
  <code>some code; more code;</code>
  <p><code>other code here;</code></p>
</bc-authorizer-example>
```

What I would expect:

```
<bc-authorizer-example>        
  <code>some code;
more code;

other code here;
</code>
</bc-authorizer-example>
```

## Environment

Zola version: 0.14.1

**Comment by Keats** [comment]
I believe this will be fixed in the next release, there's a big PR revamping shortcodes entirely (https://github.com/getzola/zola/pull/1640). I'll add that as a testcase

**Comment by Geal** [comment]
Awesome! Don't hesitate to ping me if you want me to test it once it's there

**Comment by Keats** [comment]
@Geal can you try the `next` branch? It should work

**Comment by Geal** [comment]
I get the following error message:
```
Failed to check the site
Error: Failed to render content of /home/geal/dev/biscuit/website/content/_index.md
Reason: Found usage of a shortcode named `datalog` but we do not know about. Make sure it's not a typo and that a field name `datalog.{html,md} exists in the `templates/shortcodes` directory.
```

the file `templates/shortcodes/datalog.html` exists

**Comment by Geal** [comment]
the code is here if you need to reproduce the issue: https://github.com/biscuit-auth/website

**Comment by Keats** [comment]
ah yes I think I've just pushed the fix for that a couple of minutes ago.
I'll try it tomorrow.

**Comment by Geal** [comment]
with 51784aa6 ? I just tried it, everything works now, thanks :)

**Comment by Keats** [comment]
Yep, nice to hear!

**Comment by Geal** [comment]
Do you have a timeline for the release of those fixes?  Not to pressure you on anything, just to know if I should wait for it, or update my CI to build that branch for now

**Comment by Keats** [comment]
Tomorrow unless someone finds a big bug

**Comment by Geal** [comment]
Great! I'll do my best to avoid bugs :grin:

**Comment by Geal** [comment]
I actually got another minor one, sorry :sweat_smile: 

When running `zola serve`, the `config.title` value is not used by the templates: in https://github.com/biscuit-auth/website/blob/main/templates/macros/header.html#L7 I see "Biscuit" from the [config file](https://github.com/biscuit-auth/website/blob/main/config.toml#L10) with the latest release, but "Adidoks" with the "next" branch

**Comment by Keats** [comment]
It's weird that it worked before, in theory macros have a clean scope so you shouldn't be able to access `config` at all without passing it explicitely 🤔

**Comment by Geal** [comment]
I don't know why either.apparently the adidoks theme is built like that https://github.com/aaranxu/adidoks/blob/main/templates/macros/header.html#L7
