### ISSUE TITLE
Norwegian characters render incorrectly

### ISSUE THREAD

**Issue by kflak** [Keats/gutenberg#1657]
# Bug Report
Norwegian characters render incorrectly

## Environment
Arch linux

Zola version:
0.14.1

## Expected Behavior
The characters should render correctly

## Current Behavior
The characters æ ø å renders as Ã¦ Ã¸ Ã¥

## Step to reproduce
This is my config.toml: 
```
base_url = "https://roosnaflak.com"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
extra_syntaxes = ["syntaxes"]

[extra]
author = "RoosnaFlak"
```
Using this template: 
```
{% extends "base.html" %}

{% block content %}
<h1>
  {{ page.title }}
</h1>

<p><strong>{{ page.extra.author }}</strong> {{ page.date }}</p>
{{ page.content | safe }}
{% endblock content %}
```

I have probably overlooked something really basic, but can't find any mention in the docs...

**Comment by Keats** [comment]
With `zola serve`? Does your HTML template use utf-8 encoding?

**Comment by kflak** [comment]
Yes, using `zola serve`... I have 
```    
<meta charset="utf-8">
``` 
in my `base.html`, so I believe that part should be OK.

**Comment by Keats** [comment]
If you do `zola build`, do you see the right characters in the HTML in the output dir?

**Comment by kflak** [comment]
Ah, my bad! I'm a bit of a noob to web development, and it simply turns out I need to put the meta tag before anything else in the head tag!
