### ISSUE TITLE
No docker image of version 0.14.1 

### ISSUE THREAD

**Issue by agluszak** [Keats/gutenberg#1661]
The (semi-?)official repository contains no tag for version 0.14.1
https://hub.docker.com/r/balthek/zola/tags

**Comment by Keats** [comment]
Hm its really weird, the push should be done automatically on tagging, was it somehow broken again...?

**Comment by Keats** [comment]
It looks like they made it so automated builds require a pro Docker account and I'm not going to get one.
Anyone else want to maintain the Docker image?

**Comment by Keats** [comment]
It's one GHRC now.
