### ISSUE TITLE
Internal Anchor link checker ignores simple intra-file anchors

### ISSUE THREAD

**Issue by ajyoon** [Keats/gutenberg#1676]
# Bug Report

## Environment

Zola version: 0.14.1

## Expected Behavior

I would expect internal anchor links to be checked regardless of how they are declared.

## Current Behavior

Internal links created with simple anchor links not specifying the markdown file are not checked by the link checker. Links which specify markdown files are checked.

In my specific use-case, I'm writing a documentation website with fairly long markdown files that contain lots of internal intra-file anchor links. If I want to leverage Zola's link-checker, I need to specify all these links with the redundant and needlessly verbose path syntax.

## Step to reproduce
1. `zola init` a bare site
2. Create a `content/index.md` with the following contents:
```md
+++
+++
# foo

[broken internal link, which is skipped](#abcd)
[broken internal link, which is checked](@/index.md#1234)
[working internal link, which is checked](@/index.md#foo)
```
3. `zola check`, giving the following output:
```
Checking site...
Checking all internal links with anchors.
> Checked 2 internal link(s) with anchors: 1 target(s) missing.
Failed to check the site
Error: The anchor in the link `@/index.md#asdkfjn` in /home/ayoon/tmp/content/index.md does not exist.
```
4. Note how only 2 internal links were checked, and only the path-defined link errored. By deleting the `#1234` line, the link checker now completely passes.

**Comment by Keats** [comment]
It should be fixed with the commit above.

**Comment by ajyoon** [comment]
Awesome, I've just confirmed that branch works for my site, thank so much!
