### ISSUE TITLE
Can't find a list of included highlighting themes.

### ISSUE THREAD

**Issue by SamYouatt** [Keats/gutenberg#1679]
# Documentation issue

## Summary
There is nowhere I can find that gives a complete list of the included highlighting themes.

## Proposed solution
The documentation page for code highlighting could provide a link to a list of available syntax themes.

**Comment by Keats** [comment]
It's on the configuration page since it's an option of the configuration: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
There should probably be a link back to it on https://www.getzola.org/documentation/content/syntax-highlighting/ though

**Comment by Jieiku** [comment]
you can also browse the repository for a list of them: https://github.com/getzola/zola/tree/master/sublime/themes

I have some that I modified from the originals for more contrast: https://github.com/Jieiku/abridge/tree/master/highlight_themes

I also created the css counterparts for when using `highlight_theme = "css"`: https://github.com/Jieiku/abridge/tree/master/sass/syntax
