### ISSUE TITLE
[Feature Request] Publish Zola to Winget

### ISSUE THREAD

**Issue by Kixiron** [Keats/gutenberg#1686]
Publishing Zola to [Winget](https://docs.microsoft.com/en-us/windows/package-manager/) would be really neat as an alternative way to install it on Windows ([Guide](https://docs.microsoft.com/en-us/windows/package-manager/package/))

**Comment by Keats** [comment]
It looks like anyone can do it via a PR on their repo right?

**Comment by Kixiron** [comment]
I believe so, you just make a manifest and then PR it into the repo

**Comment by leotsarev** [comment]
Hi!
I created PR for this 
https://github.com/microsoft/winget-pkgs/pull/79060

But winget now can't extract binaries from zip.
For winget working, you have either:
1. Publish .exe in release (not zipped .exe) — seems to be easy
2. Or publish full .msi / .msix — seems to be hard.

Winget will add "zip + portable exe" support, but in unspecified future version.

Please add .exe into release and I'll update PR.

@Keats 

P.S. Thank you for your awesome project!

**Comment by Keats** [comment]
I don't use Azure enough to know the answer but it might be just adding another section like https://github.com/getzola/zola/blob/master/azure-pipelines.yml#L117-L123 where it's just copying the exe on release?

**Comment by leotsarev** [comment]
@Keats hm, I'm not sure, but probably it's something like https://github.com/getzola/zola/pull/1987

**Comment by leotsarev** [comment]
Seems that we just could put this on hold. winget soon will be able to extract from zip

**Comment by Keats** [comment]
Looks like waiting wins again

**Comment by leotsarev** [comment]
Ok, I managed to get .zip working. But here is another issue. 
https://github.com/microsoft/winget-pkgs/pull/79060#issuecomment-1456455967

zola requires Microsoft.VCRedist.2015+.x64 and if there is some dependency (even so trivial and common), it not considered "single-file" .exe by winget standarts.

What if CRT will be statically linked on Windows?  How it will increase file size? 
https://stackoverflow.com/questions/31770604/how-to-generate-statically-linked-executables/44387312#44387312

**Comment by leotsarev** [comment]
and please assign this issue to me

**Comment by Keats** [comment]
Hmm where is that coming from though. I didn't think we needed anything special after replacing libsass. I think we can try the stackoverflow comment but I don't have a Windows machine to check the new file size

**Comment by leotsarev** [comment]
Rust std requires some libc. And for Windows, libc is VCRedist.

Haha, I tried to checkout zola on my Windows machine and failed because of https://github.com/Martin819/sublime-jinja2/pull/1

**Comment by leotsarev** [comment]
M.b,, you'll try to push this change to CI?

**Comment by leotsarev** [comment]
Another intresting thing that CI DO NOT pull submodules :-) Why you need them?

**Comment by Keats** [comment]
> Another intresting thing that CI DO NOT pull submodules :-) Why you need them?

For keeping track of highlighting syntaxes. I usually build them manually but CI doesn't need them. If you are not going to add syntaxes, you do not need to pull submodules

**Comment by leotsarev** [comment]
Yes, I skipped them and install rust chain locally. I'll get back with numbers

**Comment by leotsarev** [comment]
I did't managed to get zola compiled with static CRT on Windows. My rust and C++ simply not enough. We'll have to wait to another next version of winget.

**Comment by leotsarev** [comment]
@codgician added zola to winget repository, so this issue could be closed.
See https://github.com/microsoft/winget-pkgs/pull/106744
