### ISSUE TITLE
`config.title` doesn't make it to templates for mono-lingual sites on 0.15.0

### ISSUE THREAD

**Issue by cbiffle** [Keats/gutenberg#1687]
# Bug Report

## Environment

Zola version: 0.15.0 (Arch Linux package)

## Expected Behavior

My templates correctly display the site title and description using `{{ config.title }}` and `{{ config.description }}`, respectively, on 0.14.0

## Current Behavior

Both those variables now interpolate as empty strings.

Amusingly I can "fix" this by adding `default_language = "fi"`. Setting it to `en` doesn't change anything. My system locale is `en_US.UTF-8`.

I'm electing to "fix" this by downgrading to 0.14.1 instead.

## Step to reproduce

I believe this issue was actually demonstrated in #1634, but that was a multi-lingual site so it was diagnosed as a docs issue. If you take that site and switch the default language and/or remove the translation and default language, it repros on 0.15.0.

**Comment by cbiffle** [comment]
Oh, `config.generate_feed` also doesn't appear to make it through to templates in 0.15.0, interestingly.

**Comment by Keats** [comment]
That's a big one!

**Comment by cbiffle** [comment]
This is not the first time a Zola update has hosed my templates. What's the regression test process for a release look like?

**Comment by Keats** [comment]
> What's the regression test process for a release look like?

Mostly me running it on the docs and various people trying the `next` branch + tests. There are not enough integration tests right now and I'd like 0.16 to be focused on refactoring + testing.

The issue should be fixed in the `next` branch.

**Comment by swaits** [comment]
Will you push a new release for this, please?

**Comment by cbiffle** [comment]
> > What's the regression test process for a release look like?
> 
> Mostly me running it on the docs and various people trying the `next` branch + tests. There are not enough integration tests right now and I'd like 0.16 to be focused on refactoring + testing.
> 
> The issue should be fixed in the `next` branch.

Good to know. I'll switch away from using my distro's package then, since Arch doesn't support partial up/downgrades and it seems I need to go through a manual testing process before changing Zola versions.

Thanks for the quick fix.

**Edit:** ...huh, zola does not appear to be on crates.io and is thus not available for `cargo install`. Is that deliberate?

**Comment by Keats** [comment]
I'll do a release later today.

>  Is that deliberate?

Yes.
