### ISSUE TITLE
get_image_metadata and shortcode in path 

### ISSUE THREAD

**Issue by DamianHayden** [Keats/gutenberg#1696]
### What i want to do

I want to execute the following shortcode, but it seems that the shortcode cannot be used in {% %}.
Are there any other alternatives? 

`[picture.html]`
```
{% set meta = get_image_metadata(path=static/images/{{ name }}.jpg %}
<img src="{{ config.base_url }}/images/{{ name }}.{{ meta.format }}" width="{{ meta.width }}" height="{{ meta.height }}">
```

**Comment by Keats** [comment]
`{% set meta = get_image_metadata(path="static/images/ " ~ name  ~ ".jpg" %}` should work as the current template is invalid.  What's the error?

**Comment by DamianHayden** [comment]
I didn't understand tera's notation correctly.
Also, in the code I posted, `")"` was missing at the end of the path. I apologize. 

This worked fine. thank you.
`{% set meta = get_image_metadata(path="static/images/" ~ name ~ ".jpg") %}`
