### ISSUE TITLE
zola serve --fast throws error - Taxonomies Related

### ISSUE THREAD

**Issue by WilliamHuey** [Keats/gutenberg#1700]
# Bug Report

## Environment

Zola version: 0.15.2

## Expected Behavior
Running ```zola serve --fast``` should not error out with ```get_taxonomy(kind="categories", required=false)``` defined in a template when making changes to markdown files while the server is running.

## Current Behavior
I am only getting this issue when I attempt to make changes to my markdown files whiling serving content with zola use the ```--fast``` option . The normal ```zola serve``` is behaving as expected without this problem.

### Errors out when using ```zola serve --fast```

```console
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', components/library/src/library.rs:402:29
stack backtrace:
   0:     0x564133e0be5a - <unknown>
   1:     0x56413390c75c - <unknown>
   2:     0x564133e0a7b4 - <unknown>
   3:     0x564133e0af10 - <unknown>
   4:     0x564133e0a28a - <unknown>
   5:     0x564133e2b1c6 - <unknown>
   6:     0x564133e2b166 - <unknown>
   7:     0x564133e2b122 - <unknown>
   8:     0x5641336ed220 - <unknown>
   9:     0x5641336ed37c - <unknown>
  10:     0x564133aff12a - <unknown>
  11:     0x564133e753ef - <unknown>
  12:     0x564133eb6db1 - <unknown>
  13:     0x564133eacd48 - <unknown>
  14:     0x564133ebd9d7 - <unknown>
  15:     0x564133f540b8 - <unknown>
  16:     0x564133f53021 - <unknown>
  17:     0x564133fa6016 - <unknown>
  18:     0x564133df1a80 - <unknown>
  19:     0x564133806652 - <unknown>
  20:     0x564133812cd0 - <unknown>
  21:     0x5641337aa1e3 - <unknown>
  22:     0x5641338161d9 - <unknown>
  23:     0x7fa7a9e52b25 - __libc_start_main
  24:     0x56413376d8ee - <unknown>
  25:                0x0 - <unknown>

```

## Step to reproduce
1) Set ```required=false``` in call of ```get_taxonomy``` in template:
```{% set types_list = get_taxonomy(kind="categories", required=false) %}```

2) Run ```zola serve --fast```.

3) Make changes to any markdown file.

4) Throws error in console.

### My config.toml taxonomies settings 

```toml
# ...

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

# ...
```
This issue is also happening with version of zola prior to 0.15.2.

**Comment by Keats** [comment]
I believe it might be fixed in the `next` branch by coincidence

**Comment by WilliamHuey** [comment]
Yes, it is fixed on the next branch. 😊 Thanks Keats. ✨

Should I keep this issue topic open until this change gets into master?

**Comment by Keats** [comment]
Let's keep it open to avoid duplicates if other people run into that
