### ISSUE TITLE
Nested directory globs with ignored_content

### ISSUE THREAD

**Issue by austinbutler** [Keats/gutenberg#1701]
What I'd like to do is have this work: `ignored_content = ["albums/**/*.{jpg,jpeg,png}"]`. Basically ignore any images in `content/albums` _and_ all sub-folders of that. This does not work.

`ignored_content = ["*.{jpg,jpeg,png}"]` works, but it ignores all images in `content` basically.

I think https://github.com/getzola/zola/issues/481 says this should work, but it may just be referring to specifying a particular folder.

I'm using `v0.15.2`.

**Comment by Keats** [comment]
Right now the ignored content only work on a file basis, it strips the path before checking the glob: https://github.com/getzola/zola/blob/master/components/library/src/content/mod.rs#L56-L64

`ignored_content` was added for tmp files by editors really, it could be extended to support that usecase though.

**Comment by kartva** [comment]
I _also_ need `ignored_content` to ignore entire folders; I'd be happy to implement it. 

Additionally, how about ignoring stuff from `.gitignore` (if it exists) as well? Might be a nice addition.

**Comment by Keats** [comment]
> Additionally, how about ignoring stuff from .gitignore (if it exists) as well? 

Hmm not entirely sure how I feel about that. You'd need a config option to turn it off so I think I prefer to not do that.

**Comment by kartva** [comment]
Then adding in support for directory paths in `ignored_content` is a go? (we get globbing for free on Linux as well - though if you think that globbing support on Windows should also be a part of the PR, I did find a few crates for that purpose.)

**Comment by Keats** [comment]
Yep it's fine to add, but it should work on every platforms. We're using `globwalk` somewhere else so it's probably good to use that.

**Comment by kartva** [comment]
Well, turns out we didn't even need `globwalk` - the `globset` crate has support for Unix path globbing, which includes subdirectory globbing and matching on directories.

**Comment by austinbutler** [comment]
Haven't gotten around to testing it, but it looks like this was resolved by https://github.com/getzola/zola/pull/1738 :raised_hands: .
