### ISSUE TITLE
Links to images broken in summary

### ISSUE THREAD

**Issue by Yaroslav-95** [Keats/gutenberg#1705]
# Bug Report

Before version 0.15.0 zola would correctly generate links to any images that belonged to a page (e.g. a blog post) that were contained in a summary and rendered outside that page (e.g. the index page). From version 0.15.0 onward this is broken. 

Inside the page, the link is generated correctly, but outside it, in the summary, it is not; instead of something like `/blog/post/image.jpg` you get `image.jpg`.

## Environment

Zola version: 0.15.0, 0.15.1

## Expected Behavior

The link in the summary should be something like `/blog/post/image.jpg`.

## Current Behavior

zola renders something like `image.jpg` instead.

## Step to reproduce

Build a site with a post that has a picture in its summary and whose template renders summaries. An example of such a site: <https://git.yaroslavps.com/yaroslavps.com/> under `/food/`.

**Comment by theowenyoung** [comment]
Same as you.

**Comment by Keats** [comment]
Closing as there is also https://github.com/getzola/zola/issues/1772 and #1779 about this

**Comment by Yaroslav-95** [comment]
After finding myself with some free time, I decided to try to tackle
this issue on my own. So far I have found the culprit to be commit
4086b075 merged in PR #1582 "Support colocating subfolders". The commit
for this feature broke the functionality that this issue is about.

I'll soon open a PR with a fix.

**Comment by Keats** [comment]
That should be fixed in 0.16?
