### ISSUE TITLE
Allowed tags excluded from escape 

### ISSUE THREAD

**Issue by DamianHayden** [Keats/gutenberg#1714]
Currently, the display of the text displays an article by using `{{Page.Content | Safe}}`.
However, the `SAFE` element does not escape all tags and is delivered as it is.
Therefore, scripts can also be performed.
However, if there is no `SAFE`, all tags are escaped, so it will not be used.

I was thinking of doing joint writing with multiple people using ZOLA, but I am abandoned for security.

Is permitted tags not escaped or alternative functions?

**Comment by Keats** [comment]
it's not possible nor planned no.

**Comment by DamianHayden** [comment]
OK, I see thank you.
