### ISSUE TITLE
Single binary claim is inaccurate

### ISSUE THREAD

**Issue by jart** [Keats/gutenberg#1718]
On the website it's claimed that zola comes as a single binary. But the project distributes three separate binaries for Linux, WIndows, and Macintosh. Therefore if I use multiple operating systems I need to download multiple binaries. 

Consider using https://github.com/jart/cosmopolitan otherwise you may want to update the claim wording to be something like "you only need a single binary on your system"

**Comment by Keavon** [comment]
@Keats just to help you with triage and issue cleanup, you should probably close this issue for obvious reasons.
