### ISSUE TITLE
custom robots.txt not rendered

### ISSUE THREAD

**Issue by t3link** [Keats/gutenberg#1721]
# Bug Report

## Environment

Zola version: 0.15.2

## Expected Behavior
It should output my custom `robots.txt` in theme templates directory

## Current Behavior
Always render same content with built-in one.

## Step to reproduce
My blog source code is [here](https://github.com/t3link/t3link.github.io)

A custom robots.txt file is in the theme's templates directory. `./themes/DeepThought/templates/robots.txt`
```bash
λ cat themes/DeepThought/templates/robots.txt
User-Agent: *
Disallow: /*
Allow: /$
Allow: /archives/

Sitemap: {{config.base_url}}/sitemap.xml
```

After run `zola build` or `zola serve`, In the public output directory, `robots.txt` always be
```
λ cat public/robots.txt
User-agent: *
Allow: /
Sitemap: https://docs.tothetracker.link/sitemap.xml
```

**Comment by Keats** [comment]
It's probably just not checking the themes directory first, that should be an easy fix.

**Comment by mwcz** [comment]
I took a stab at this and it looks like the theme's robots.txt was being added to tera with the wrong name.  Potential fix in the PR up there. :point_up:

**Comment by mwcz** [comment]
@t3link The fix for this was merged and I think will go out with the next release.

**Comment by t3link** [comment]
:+1:  thanks~
