### ISSUE TITLE
Extra syntaxes not working

### ISSUE THREAD

**Issue by arnau** [Keats/gutenberg#1723]
# Bug Report

## Environment

Zola version: 0.15.2

## Expected Behavior

I would expect a `config.toml` like:

```toml
[markdown]
extra_syntaxes = ["syntaxes"]
```

to load and apply the syntaxes in the `syntaxes` folder as described in the [config documentation](https://www.getzola.org/documentation/getting-started/configuration/).

In case it helps:

- [the full config file](https://github.com/arnau/seachess/blob/main/website/config.toml)
- [the extra syntaxes](https://github.com/arnau/seachess/tree/main/website/syntaxes)

Note that the exact code linked above works well with zola version **0.14.1**.

## Current Behavior

Both `zola --root website serve` and `zola --root website build` work as expected except for warnings such as:

```
Warning: Highlight language rfc8288 not found in notes/dive-into-the-link-header.md
Warning: Highlight language abnf not found in notes/dive-into-the-link-header.md
```

With the resulting HTML not highlighting codeblocks labelled as `rfc8288` or `abnf`.

## Step to reproduce

A simple `zola serve` on [this minimal test](https://github.com/arnau/zola-test) should suffice.

**Comment by Keats** [comment]
Ah the snippet hasn't been updated, it should be `extra_syntaxes_and_themes` as mentioned later on the page

**Comment by arnau** [comment]
Ah! I saw it, tried it on my website but didn't work and forgot to try it on the minimal test.

So, when I tried on my website it failed again so after digging a bit I found that if I add `highlight_theme = "css"` it fails again. I updated the repo with the small test which reproduces the issue.

**Comment by jk-ozlabs** [comment]
Seeing the same issue here, and thought I'd have a go at fixing it. Let me know if you need any details.
