### ISSUE TITLE
taxonomy_list.html being ignored

### ISSUE THREAD

**Issue by medwards** [Keats/gutenberg#1724]
# Bug Report

## Environment

Zola version: `0.14.1`

## Expected Behavior
Defining taxonomies + theme:
```
 theme = "my_theme"
 taxonomies = [
   { name = "category" },
   { name = "tag" },
 ]
```

And placing `taxonomy_list.html` in `themes/my_theme/templates` should result in successful site generation.

## Current Behavior

I get
```
Failed to build the site
Error: Failed to render a list of tag page.
Reason: Tried to render `tag/list.html` but the template wasn't found
```

Additionally I see some weirdness in which taxonomy is shown in the error. I assume this is because the taxonomy is a hashmap and so the order they are evaluated in is non-deterministic?

## Step to reproduce
See expected behaviour.

**Comment by Keats** [comment]
`taxonomy_list.html` was added in 0.15 I believe?

**Comment by medwards** [comment]
Yup, just grabbed 0.15.2 from here and it worked fine. Sorry about that, 0.14.1 is the default from Ubuntu rn.
