### ISSUE TITLE
Asset colocation does not copy files without an extension

### ISSUE THREAD

**Issue by tsheinen** [Keats/gutenberg#1731]
# Bug Report

## Environment

Zola version: zola 0.15.2

## Expected Behavior

Asset/section colocation should work when the assets in question have no file extension.

## Current Behavior

Files inside a section with no extension are not copied into the output folder

## Step to reproduce

Create two files in a section; one with an extension (i used *.jpg) and one without and then build.

**Comment by Keats** [comment]
Fixed in 0.15.3
