### ISSUE TITLE
Set RSS Feed Image

### ISSUE THREAD

**Issue by colinkiama** [Keats/gutenberg#1736]
Currently on feed readers, feeds generated with Zola don't have an icon.

It would be great to have the option.

**Comment by DamianHayden** [comment]
The feed can be customized.
Place the atom.xml you created in the template directory.
However, as you say, it might be better to display the icons as default.

[https://github.com/getzola/zola/blob/master/components/templates/src/builtins/atom.xml](https://github.com/getzola/zola/blob/master/components/templates/src/builtins/atom.xml)
[https://www.getzola.org/documentation/templates/feeds/](https://www.getzola.org/documentation/templates/feeds/)

**Comment by timharek** [comment]
What kind of icon are you talking about?

Which RSS reader have you tried?

An RSS reader like NetNewsWire or Nextcloud News returns an icon if the page have a Favicon :)

**Comment by DamianHayden** [comment]
It was exactly what you said.
Basically, the browser looks for `favicon.ico` directly under the public directory and displays it.

**Comment by Keats** [comment]
So is anything needed there? I would expect readers to just check the favicon of the website by default

**Comment by colinkiama** [comment]
This seems to have been a bug with Feedly then. I see the favicon now.

Thank you for your patience.
