### ISSUE TITLE
[Search][I18n] Bad search_index.{{lang}}.js content if lang is not en

### ISSUE THREAD

**Issue by pcoves** [Keats/gutenberg#1740]
# Bug Report

## Environment

Zola version: 0.15 (was already present in 0.14)

## Expected Behavior

Generation of the `search_index.{{lang}}.js` should not post-fix `pipelines` array with `-{{lang}}`.

## Current Behavior

When you set the *default language* to `"en"` and generate the *search index* you have something like `"pipeline":["trimmer","stopWordFilter","stemmer"]` close to the file's beginning.

But if you set de *default language* to, say, `"fr"` you get such a content: `"pipeline":["trimmer-fr","stopWordFilter-fr","stemmer-fr"]`.
Not the `-fr` post-fixes.

Now, if you ever add the following lines to a *template* file:

```
<script src="{{ get_url(path="/elasticlunr.min.js") }}"></script>
<script src="{{ get_url(path="/search_index." ~ lang ~ ".js") }}"></script>
<script src="{{ get_url(path="/search.js") }}"></script>
``` 

With `search.js` containing the single following line:

```
const index = elasticlunr.Index.load(window.searchIndex);
```

You get the following error: `Uncaught Error: Cannot load un-registered function: trimmer-fr`.

Removing all `-{{ lang }}` in the `search_index.{{lang}}.js` solves the problem.

**Comment by pcoves** [comment]
For what it's worth, changing [this line](https://github.com/getzola/zola/blob/master/components/search/src/lib.rs#L137) from 

```
let mut index = Index::with_language(language, &build_fields(&language_options.search));
```
to

```
let mut index = Index::with_language(Language::English, &build_fields(&language_options.search));
```

fixes the issue.

Not sure if it's the right approach tho.

**Comment by Keats** [comment]
Can you try adding the French stemmer of elasticlunr to see if that solves it: https://github.com/MihaiValentin/lunr-languages ? Or https://github.com/weixsong/lunr-languages I'm not sure if the first one is meant to work with elasticlunr

**Comment by pcoves** [comment]
To be fair I've no idea what you're asking me to do right now.

I'd gladly give it a try if I ever catch what you mean.

**Comment by Keats** [comment]
Only the english version is built-in afaik, for other languages you need to add an additional JS like shown in https://github.com/weixsong/lunr-languages#in-a-web-browser

**Comment by pcoves** [comment]
Okay, you mean to change the code in my `zola` site.
I thought you wanted me to patch an external dependency of `zola` itself.

I'll give it a try asap.

**Comment by pcoves** [comment]
```
<script src="{{ get_url(path="/elasticlunr.min.js") }}"></script>
<script src="{{ get_url(path="/search_index." ~ lang ~ ".js") }}"></script>
<script src="{{ get_url(path="/lunr-languages/lunr.stemmer.support.js") }}"></script>
<script src="{{ get_url(path="/lunr-languages/lunr." ~ lang ~ ".js") }}"></script>
<script src="{{ get_url(path="/search.js") }}"></script>
```

It works just fine using https://github.com/weixsong/lunr-languages#in-a-web-browser.

Thanks a lot!

**Comment by Keats** [comment]
Just re-opening to make sure it's added to the docs

**Comment by pcoves** [comment]
I'm not really aware of licensing stuff but this repo is under MPL.

Do you have any idea if one could ship it with a `zola` generated website without issue?

**Comment by Keats** [comment]
It should not be an issue
