### ISSUE TITLE
[Feature Request] Make shortcodes available in templates

### ISSUE THREAD

**Issue by sirthias** [Keats/gutenberg#1748]
It looks like shortcodes currently (0.15.3) cannot be used in templates (e.g. "templates/page.html").
Tera macros work, but are more cumbersome (need import, cannot have a body).

It there a reason why shortcodes shouldn't be available in templates?

(Also: This limitation doesn't appear to be mentioned in the documentation. It took me a while to figure out, why shortcodes don't work for me...)

**Comment by Keats** [comment]
> cannot have a body

This should be fixed with Tera v2 but no timeline on that at all.

> It there a reason why shortcodes shouldn't be available in templates?

They don't really make sense in the context of a template, some of them output Markdown after all. They also have access to some variables that are only present while rendering the Markdown.

> (Also: This limitation doesn't appear to be mentioned in the documentation. It took me a while to figure out, why shortcodes don't work for me...)

Isn't that the first paragraph of https://www.getzola.org/documentation/content/shortcodes/ ?

**Comment by sirthias** [comment]
>> cannot have a body
>
> This should be fixed with Tera v2 but no timeline on that at all.

Ok, thank you!

>> It there a reason why shortcodes shouldn't be available in templates?
>
> They don't really make sense in the context of a template, some of them output Markdown after all.
> They also have access to some variables that are only present while rendering the Markdown.

Hmm... ok.

>> (Also: This limitation doesn't appear to be mentioned in the documentation. It took me a while to figure out, why shortcodes don't work for me...)
>
> Isn't that the first paragraph of https://www.getzola.org/documentation/content/shortcodes/ ?

I had to reread that paragraph three times more, before realizing that, yes, you are right!
It does mention this limitation, if you look for it.
For some reason I didn't pick it up at all, despite rereading several times.

Maybe the following change would make things even clearer?

```
s/
In our case, a shortcode corresponds to a template defined in the templates/shortcodes directory or a built-in one that can be used in a Markdown file.
/
In our case, a shortcode corresponds to a template defined in the templates/shortcodes directory or a built-in one.
It can only be used in Markdown files, not other templates.
/
```
