### ISSUE TITLE
load_data appears to always try to load a local file

### ISSUE THREAD

**Issue by piedoom** [Keats/gutenberg#1753]
# Bug Report

## Environment
Windows, GH Actions

Zola version: 0.15.3 (appears to affect 14.1, haven't tested earlier)

## Expected Behavior

This should request "https://en.wikipedia.org/wiki/Commune_of_Paris" (and deserialize it if it is a specific filetype)

```
{% set data = load_data(path="https://en.wikipedia.org/wiki/Commune_of_Paris") %}
```

## Current Behavior

It appears the URL is always appended to the local path, e.g. 

```
Reason: Function call 'load_data' failed
Reason: `load_data`: /github/workspace/https://vaporsoft.net/feed.toml doesn't exist
```

## Step to reproduce

Use any load_data fn with an external URL

**Comment by Keats** [comment]
Ah the docs are wrong :( 
Try `{% set data = load_data(url="https://en.wikipedia.org/wiki/Commune_of_Paris") %}`, `path` is only meant to be used for local files.

**Comment by Jieiku** [comment]
Here is an example of using it as a shortcode:

`{{ showdata(src="../theme.toml" type="toml" key="min_version") }}`
https://github.com/Jieiku/abridge/blob/master/templates/shortcodes/showdata.html
