### ISSUE TITLE
Zola considers empty-anchor links to be broken

### ISSUE THREAD

**Issue by jplatte** [Keats/gutenberg#1754]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior

Empty anchor links (`[foo](#)`) should be allowed. I'm using them on one site to indicate links to no-longer-existant things like a mailing list that was referenced in an old blog post (like `go [~~here~~](#)`).

## Current Behavior

Zola errors when encountering an empty anchor link:

```
Error: The anchor in the link `@/file.md#` in /home/jplatte/repo/path/content/file.md does not exist.
```

**Comment by Keats** [comment]
Hmm when I had this issue in my sites, I normally keep the URL in plain text and mention it's no longer existant in parenthesis or something. Empty anchor links`#` should just be skipped though.

**Comment by mwcz** [comment]
This was becoming a problem in the site I'm working on too, so I took a stab at fixing it.

**Comment by jplatte** [comment]
I'll close this since #1756 was merged.
