### ISSUE TITLE
gist shortcode does not display "file" sub-gists

### ISSUE THREAD

**Issue by brainstorm** [Keats/gutenberg#1758]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior

This gist should only display the `firmware_unpack-txt` gist:

https://gist.github.com/brainstorm/5f5902a8e35b50f6cae322d891169f2a#file-firmware_unpack-txt

Zola does not render it properly when provided it this way:

```markdown
{{ gist(url="https://gist.github.com/brainstorm/5f5902a8e35b50f6cae322d891169f2a#file-firmware_unpack-txt") }}
```

But it does render the whole list of sub-gist-files when this url is passed (as expected):

```markdown
{{ gist(url="https://gist.github.com/brainstorm/5f5902a8e35b50f6cae322d891169f2a") }}
```

## Current Behavior

The `gist` shortcode does not render the `#file-` variation of gist shortcodes and does not seem to support the sub-gist.

**Comment by Keats** [comment]
The gist shortcode hasn't been touched in 4 years and is only: https://github.com/getzola/zola/blob/master/components/templates/src/builtins/shortcodes/gist.html
I don't think I'll update it though, it was more meant as an example shortcode and i would actually prefer removing all built-in shortcodes tbh

**Comment by brainstorm** [comment]
If you remove them all, where are they supposed to be? As templates or themes? I'm curious about how it'd work in the future, to be ready (I'm a new user).

**Comment by Keats** [comment]
I'm not planning to remove them any time soon but if you need customisation it's better to write your own.
It could be either in themes or templates, it really depends on the shortcode type.

**Comment by brainstorm** [comment]
My bad, I wasn't passing file= argument properly, sorry for the confusion/noise, this shortcode works fine and as expected ;)
