### ISSUE TITLE
Extraneous newline with custom anchor link

### ISSUE THREAD

**Issue by alexrutar** [Keats/gutenberg#1759]
# Bug Report
When customizing the anchor link by adding the file `templates/anchor-link.html`, an extraneous newline is inserted into the rendered HTML.

Note that this is in contrast to the HTML generated when no custom `anchor-link.html` is specified. Usually, the newline does not matter, but it can sometimes cause issues depending on the CSS applied.

Thanks for your time!

## Environment

Zola version: 15.3

## Expected Behavior
There should be no newline:
```
<h2 id="header"><a class="zola-anchor" href="#header" aria-label="Anchor link for: header">🔗</a>Header</h2>
```

## Current Behavior
A newline is inserted into the generated HTML:
```
<h2 id="header"><a class="zola-anchor" href="#header" aria-label="Anchor link for: header">🔗</a>
Header</h2>
```

## Step to reproduce
1. Follow the [Zola example setup](https://www.getzola.org/documentation/getting-started/overview/#first-steps-with-zola) to create a minimal site.
2. Add the option `insert_anchor_links = "left"` to `contents/blog/_index.html`.
3. Create a file `templates/anchor-link.html` with the contents `<a class="zola-anchor" href="#{{ id }}" aria-label="Anchor link for: {{ id }}">🔗</a>`.
4. Add a header to `content/blog/first.md` like `## Header`.
4. Run `zola build`, and inspect the HTML file `public/blog/first/index.html`.

**Comment by Keats** [comment]
Hmm I'll have to try it, I don't understand why a newline would be added

**Comment by Keats** [comment]
I can't seem to reproduce it?

**Comment by alexrutar** [comment]
Hi @Keats , sorry about the delay here! I tested this out again on the newest Zola version and I still have the same issue. To streamline things a bit, I set up a git repository, which you can find here: [https://github.com/alexrutar/zola-issue--1759](https://github.com/alexrutar/zola-issue--1759). It's made using the reproduction steps I listed above.

In addition, I ran a build on my local device, and copied the output to the `public-build` directory (in that repository). The file with the link issue is exactly here: [https://github.com/alexrutar/zola-issue--1759/blob/master/public-build/blog/first/index.html](https://github.com/alexrutar/zola-issue--1759/blob/master/public-build/blog/first/index.html)

**Comment by alexrutar** [comment]
Looks like this was my error: if someone in the future sees this, it was caused since some text editors (such as vim) always insert a trailing newline.

Perhaps it would be reasonable to have a convenient way to trim whitespace on shortcodes? Regardless this seems to be beyond the scope of this issue.

**Comment by alexrutar** [comment]
The workaround which I am currently using is to use a no-op tag at the end of the shortcode, like
```
< shortcode contents >{% set a=0 -%}
```
which strips the trailing newline. Unfortunately an expression like `{% -%}` seems to be invalid. If anybody has any suggestions for a more reasonable way to do this, I would be happy to hear it!
