### ISSUE TITLE
Commenting shortcodes in articles doesn't work

### ISSUE THREAD

**Issue by kartva** [Keats/gutenberg#1762]
# Bug Report
Minimum reproducible example:

(in `content/article/index.md`)
```
+++
title = "Title"
+++

{%/*
{{shortcode()}}
*/%}
```
The above fails to render, with the message:

```
Failed to build the site
Error: Failed to render content of content/article/index.md
Reason: Found usage of a shortcode named `shortcode` but we do not know about. Make sure it's not a typo and that a field name `shortcode.{html,md} exists in the `templates/shortcodes` directory.
Done in 16ms.
```

## Environment

Zola version:
zola 0.15.3

## Expected Behavior
The shortcode should've rendered.

## Current Behavior
Zola errors.

**Comment by Keats** [comment]
The commented shortcode applied to the `{% %}` one, you will need to do the same for the inner shortcode: `{{/*shortcode()*/}}`

**Comment by kartva** [comment]
Yes, https://github.com/getzola/zola/blob/90bddf0ef5e10f7f2e2b3f95532628f2a58a64f0/components/rendering/src/shortcode/parser.rs#L307-L317

clarifies that.

It might be worth updating the documentation to be less ambiguous nonetheless.
