### ISSUE TITLE
[Feature Request] Deserializing XML from load_data

### ISSUE THREAD

**Issue by piedoom** [Keats/gutenberg#1763]
Currently, the `load_data` function will automatically deserialize toml, json, csv, and bibtex files. For my usecase, I am consuming an atom feed from another Zola site to build out pages. In the interim, I've rendered some stuff I need to a [TOML feed](https://github.com/piedoom/vaporsoft/blob/3c2b5da201da9b860e22c45d70b50e230234b3f2/templates/feed.toml) instead, but it would be nice to just directly consume. From my understanding, this should not require any extra dep as we can already generate XML. Assuming the functionality for [this lives here](https://github.com/getzola/zola/blob/96db5231e74599815df381fbf90d499c2d5b3814/components/templates/src/global_fns/load_data.rs#L40), I might be able to get this running if it sounds like something you'd want to include.

**Comment by Keats** [comment]
We generate XML via Tera templates, not a XML lib so I believe this would add a dependency. I don't mind adding XML to load_data though, as long as it stays basic
