### ISSUE TITLE
minify_html=true does not minify embedded CSS and JS

### ISSUE THREAD

**Issue by JeremyBarbosa** [Keats/gutenberg#1765]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior
When setting `minify_html = true` in `config.toml`, it is expected that the entire generated HTML file would be minified, as mentioned in the documentation for the `minify_html`:
"When set to "true", the generated HTML files are minified."

 For example, the following code block:
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    p {
      color: white;
      margin-left: 10000px;
    }
  </style>
  <script>
    alert("Hello World!");
    console.log("Some information: %o", information);
  </script>
</head>
<body>


    <p>Example blog post</p>

  FOO BAR
</body>
</html>
```

Should create this:

```html
<!doctype html><html><head><meta charset=utf-8><style>p{color:#fff;margin-left:10000px}</style><script>alert("Hello World!"),console.log("Some information: %o",information);</script><body><p>Example blog post</p> FOO BAR
```

## Current Behavior
Currently, embedded CSS and JavaScript (in things such as <style> and <script> tags) are not minified. For example, the following code block:

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    p {
      color: white;
      margin-left: 10000px;
    }
  </style>
  <script>
    alert("Hello World!");
    console.log("Some information: %o", information);
  </script>
</head>
<body>


    <p>Example blog post</p>

  FOO BAR
</body>
</html>
```

Creates this:

```html
<!doctype html><html><head><meta charset=utf-8><style>p {
      color: white;
      margin-left: 10000px;
    }</style><script>alert("Hello World!");
    console.log("Some information: %o", information);</script><body><p>Example blog post</p> FOO BAR
```

## Step to reproduce
1. Include embedded CSS or JS in an HTML template
2. Set `minify_html = true` in `config.toml`
3. Inspect the output of `zola build`

**Comment by Keats** [comment]
This won't be fixed for now. The minifier lib we're using requires bundling Go.

**Comment by JeremyBarbosa** [comment]
Great news! The minifier library no longer relies on `js-esbuild` and therefore the Go compiler! It instead uses its own `js-minify` library now.
