### ISSUE TITLE
Syntax highlighting for code blocks that contain more than just the language name in the header

### ISSUE THREAD

**Issue by alice-i-cecile** [Keats/gutenberg#1770]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior

```
```rust,no_run
use bevy::prelude::*;

fn main() {
    App::new()
        .add_system(hello)
        .run();
}

fn hello() {
    println!("Hello, Bevy!")
}
\```
```

This code should be have syntax highlighting, like [Github does](https://github.com/bevyengine/bevy-website/blob/982d2a672e48a615235b41ae5bcf291e47b9333f/content/learn/book/welcome/apps/_index.md).

## Current Behavior
No highlighting occurs.

## Workaround

Reverse the order of `no_run` and `rust`, so then the language occurs last.

## Step to reproduce

1. Create a code block with anything after the language in the ```lang header.
2. Build zola.
3. Observe lack of highlighting.

## Context
We're using this as part of a workflow to automatically compile-check Rust code in Zola: https://github.com/bevyengine/bevy-website/pull/281

**Comment by XXXMrG** [comment]
Have you checked `highlight_theme` in config.toml is in markdown section?

In my case, I use a old theme, after i update zola to 0.15.2, the syntax highlighting not work. 
Cased by the old config.toml `highlight_theme` field is in the root section.

hope it can help you

**Comment by kvnyng** [comment]
I updated to 0.15.3, and all my highlighting has disappeared. I was originally using 0.13. Might this be a general code highlighting issue?

**Comment by Keats** [comment]
you probably need to set it up in the `markdown` section: https://github.com/getzola/zola/blob/master/docs/config.toml#L8

**Comment by kvnyng** [comment]
Yeah that worked for me!

**Comment by Keats** [comment]
Did that work for you as well @alice-i-cecile ?
