### ISSUE TITLE
Have a blog section and list it on the homepage

### ISSUE THREAD

**Issue by jamen** [Keats/gutenberg#1771]
Can you have pages like `/`, `/about` and `/blog/hello-world`, but list the blogs on the `/` page instead of a `/blog` page?

Or can you have pages like `/about` and `/2022-02-16-hello-world`, and filter the section down to blog pages when listing them?

**Comment by Keats** [comment]
You can make the blog section `transparent` to achieve that

**Comment by jamen** [comment]
Thanks!

For listing only the blogs, I used `{% for page in section.pages | filter(attribute="date") | sort(attribute="date") | reverse %}`. But with `transparent` I can also filter with `{% if page.path is starting_with("/blog/") %}`. I briefly tried using taxonomies to filter, but because that's not their intended use it didn't work out great.
