### ISSUE TITLE
Adding classed to HTML tags (again!)

### ISSUE THREAD

**Issue by rimutaka** [Keats/gutenberg#1773]
Adding classes to HTML tags during MD->HTML conversion makes using CSS frameworks like Bootstrap or Tailwind a lot easier. This was suggested in #1222 by @matiasilva and #1462 by @pinpox. I think it would be a widely used feature, specially by the "front-end challenged" like myself.

The first **solution that comes to mind** is to add a config section with a map of tags/classes and insert them into the HTML markup similar to how _ids_ are inserted in https://github.com/getzola/zola/blob/master/components/rendering/src/markdown.rs#L431 .

An extension to this would be an option to add any attributes, not just `class`. It would complicate the config somewhat, though.

### Alternatives

1. **Using mixins in custom SCSS files.** This works out of the box for Bootstrap. It should work for other frameworks, but there is no guarantee it will always work as expected.

2. **Using @extend**, e.g.  `h1 {@extend .text-center;}` is the same as `<h1 class='text-center'>`.  It kind of give us the same result with what we already have. The downside of this method is having to add the entire CSS framework to the project.

3. Something else?

@Keats , is it a problem worth solving? Do you see any pitfalls? I don't mind adding this feature myself. It doesn't seem to be too involved. If [2] is the best option here, OK if I add a few lines to the docs?

**Comment by Keats** [comment]
pulldown-cmark added that for headers recently actually: https://docs.rs/pulldown-cmark/latest/pulldown_cmark/struct.Options.html#associatedconstant.ENABLE_HEADING_ATTRIBUTES !
I'm planning to upgrade the lib while refactoring and will enable that option so it it will work with headers at least. It's probably next on my TODO list, I'll ping here once it's implemented.

**Comment by rimutaka** [comment]
Looks like we'll have to have those classes in the markdown for ENABLE_HEADING_ATTRIBUTES to work. 

`# text { #id .class1 .class2 }`

Given the verbosity of Bootstrap or Tailwind the source documents will be unreadable. Imagine something like this in your .md file:
```
#### My little level 4 heading {#csharp-devs .bg-light .text-dark .p-1 .rounded .mb-3 .border .me-4}
```

**Comment by Keats** [comment]
Isn't it more of an issue with utility classes? You can wrap them in your scss into a single class if needed. I'm planning to stick with what this `ENABLE_HEADING_ATTRIBUTES` / pulldown-cmark  offers though

**Comment by Animeshz** [comment]
Um, why is this not possible in any generic paragraph? [Jekyll allows this](https://digitaldrummerj.me/styling-jekyll-markdown/).

**Comment by Keats** [comment]
As the link mention it's an extension feature of the Markdown parser they use. You can make a feature request to https://github.com/raphlinus/pulldown-cmark to add it for all blocks
