### ISSUE TITLE
`zola serv` doesn reload _index.md

### ISSUE THREAD

**Issue by emdete** [Keats/gutenberg#1776]
# Bug Report

if i change `_index.md` that change has no effect until i stop and restart `zola serv`

## Environment

Zola version: zola 0.15.3

## Expected Behavior

if `zola serv` is running it should recognize all changes of all files.

## Current Behavior

The old content is used instead.

## Step to reproduce

Rename a file in `template/` and adapt that change in `_index.md`, i got a message that the file isnt available, the filename was the previously used filename.

**Comment by Keats** [comment]
Are you changing `_index.md` or a template? I'm not sure what's the issue, `zola serve` will rebuild the whole site on change most of the time. Do you get the old content after a browser refresh?

**Comment by emdete** [comment]
i changed _index.md, yes. the browser normally shows immediatly any changes i did. in  that case there is no change, not even after (cache circumventing) reload of the page.

it would be so helpful if zola would have an access log to see the reload...

**Comment by Keats** [comment]
Access log wouldn't be that helpful, it just loads url + `index.html`

**Comment by spaetz** [comment]
Using the current release (0.15.3), I can say that modifying _index.md is reflected immediately on a browser reload, using `zola serve`

**Comment by emdete** [comment]
Great! Yes, i can confirm this.
