### ISSUE TITLE
logging of `zola serv`

### ISSUE THREAD

**Issue by emdete** [Keats/gutenberg#1777]
`zola serv` doesnt log anything but reload of content. it would be nice to have an access log and a log about what zola did to serv the request (for example shich files where considered).

this feature could be optional and enabled by a command line option.

cause for this request:

i had a page that showed a 404 with no further notice from `zola serv`. when i ran `zola build` an error was shown. it would speed up debugging if that error would be shown in `zola serv` as well.

**Comment by Keats** [comment]
> i had a page that showed a 404 with no further notice from zola serv. when i ran zola build an error was shown.

Do you have a way to reproduce that? `zola build` and `zola serve` call the same functions to build the site.

**Comment by emdete** [comment]
mainly `zola serve` doesnt log anything here when serving files. its just silent. it logs errors when files change but it doesnt seem to logg all. 

i often ran into the problem that i have zola serve running but if i restart it it doesnt come up again complaining with an error.  so either errors should stop zola or errors should not prevent from starting. sometimes that error wasnt shown before.

i havent figured out yet which errors arent shown - need some more expirience with zola :)

**Comment by Keats** [comment]
Ah I think i remember a similar issue where the Tera errors were not properly unrolled on reload, i'll have a look

**Comment by Keats** [comment]
Were you using 0.15.3?

**Comment by Keats** [comment]
I won't add logging to `zola serve`, it would be too much of a mess with all the parallelism anyway.
