### ISSUE TITLE
"No such file or directory" without printing its path

### ISSUE THREAD

**Issue by DuckDuckWhale** [Keats/gutenberg#1782]
# Bug Report

## Environment

Zola version: built on `e07c8c9a84fe0928a86930334fead6c806c18053`

## Expected Behavior
Actual path along side file not found error

## Current Behavior
Says `Error: No such file or directory (os error 2)` but doesn't say where, making it very frustrating to debug.

## Step to reproduce
I tried but was unable to reproduce :( I encountered this many times by simple changes (making an invalid date, saving, adding a line to the html, saving, etc.), but I was unable to reproduce this when I actually try to do it. I was able to get it to be stuck on the state of showing no such file or directory, but I can't reproduce that either. However the terminal scrollback was there so there had to be a code path that leads towards this.

## Log

```
user@host:~/repo$ zola serve
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 1 pages (0 orphan) and 1 sections
Done in 7ms.

Web server is available at http://127.0.0.1:1111

Listening for changes in /home/user/repo{config.toml, content, sass, static, templates}
Press Ctrl+C to stop

Change detected @ 2022-02-26 23:48:56
-> Template changed /home/user/repo/templates/blog.html
Reloading only template
Done in 0ms.

Change detected @ 2022-02-26 23:49:01
-> Template changed /home/user/repo/templates/blog.html
Reloading only template
Done in 0ms.

Change detected @ 2022-02-26 23:49:12
-> Content changed /home/user/repo/content/blog/first.md
Failed to build the site
Error: Error when parsing front matter of page `/home/user/repo/content/blog/first.md`
Reason: data did not match any variant of untagged enum MaybeDatetime for key `date` at line 1 column 1
Done in 0ms.

Change detected @ 2022-02-26 23:49:16
-> Content changed /home/user/repo/content/blog/first.md
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 1 pages (0 orphan) and 1 sections
Done in 2ms.

Change detected @ 2022-02-26 23:49:22
-> Template changed /home/user/repo/templates/blog.html
Reloading only template
Failed to build the site
Error: No such file or directory (os error 2)
Done in 0ms.
```

**Comment by Keats** [comment]
This is odd, we have our own fs utils that do the same thing as std but do print the filename on error. I guess we must have missed some places.

**Comment by eatse21** [comment]
Hi, I was able to reproduce and find the issue:

## Steps to reproduce
1. Create the basic blog structure [showed in the tutorial](https://www.getzola.org/documentation/getting-started/overview/)
2. Run `zola serve`
3. **_With `vi`_**, edit `content/blog/first.md` (add a space somewhere that’s it), save `:w`, **_then quit_** `:q` (seems to work when doing `:wq`)
4. This time edit `templates/base.html` (again, a space somewhere), and save.

This is what you should get
```
$ zola serve 
Building site...
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 56ms.

Listening for changes in /home/vagrant/myblog{config.toml, content, sass, static, templates}
Press Ctrl+C to stop

Web server is available at http://0.0.0.0:1111

Change detected @ 2022-04-17 13:17:42
-> Content changed /home/vagrant/myblog/content/blog/first.md
-> Creating 2 pages (0 orphan), 1 sections, and processing 0 images
Done in 29ms.

Change detected @ 2022-04-17 13:17:51
-> Template changed /home/vagrant/myblog/templates/base.html
Reloading only template
Failed to build the site
Error: No such file or directory (os error 2)
Done in 3ms.
```

## The issue
Vi creates a temporary hidden file when editing, with the same path but ending with `.swp`, and deletes it when it’s not useful anymore.
Creating and deleting files inside the folders that `zola serve` is watching, _and_ during rebuilding, seems to mess up with how `zola` handles files to process.

The problem triggers here https://github.com/getzola/zola/blob/3dcc080f9d3558e9f811b442ebe09699f363f930/components/utils/src/fs.rs#L92
The `metadata` function is called directly from `std::fs` without any wrapper, and so returns a basic `Error` without the filename.

After adding a `map_err` on the 2 `metadata` calls, and also `set_file_mtime`, I get this:
```
$ ZOLA_PERF_LOG=1 zola serve
[…]

Change detected @ 2022-04-17 13:37:58
-> Template changed /home/vagrant/myblog/templates/base.html
Reloading only template
Cleaned folder took 0ms
Compiled own Sass took 0ms
Built search index took 7ms
Rendered aliases took 0ms
Failed to build the site
Error: Was not able to obtain metadata for file /home/vagrant/myblog/public/blog/.first.md.swp
Reason: No such file or directory (os error 2)
Done in 21ms.
```
See https://github.com/abdullahibnnadjo/zola/commit/540b813e9c8e4b3da11cc67098b65e03885cf2aa

**Comment by Keats** [comment]
Ah thanks for finding it out! The commit will be different on `next` because it switched a few libraries etc

**Comment by Keats** [comment]
I've updated the error on the `next` branch. Looking at the snippet above, it seems to be some text editor files causing issues?

**Comment by eatse21** [comment]
Yeah, for now I only got this issue with vi with its `.swp` files. @DuckDuckWhale, do you also use vi ?
The `next` branch prints correctly the error now !

**Comment by DuckDuckWhale** [comment]
I did use Vim. I wonder by hidden files are included for consideration? Would `.gitignore` also prevent the build? Maybe it's best to ignore all hidden files, in that case?

**Comment by Keats** [comment]
There's already a function to detect tmp files in the serve command, we probably want to re-use that when copying static assets

**Comment by Keats** [comment]
I'm going to close this as the initial is solved. Please open another issue if you're still having issues with vi files
