### ISSUE TITLE
Relative Links to Markdown Files

### ISSUE THREAD

**Issue by judgeNotFound** [Keats/gutenberg#1784]
In my documentation, I have the following style of links:
```
[My Link](subdirectory/my-file.md)
```
When building my documentation website, I get something like the following directory structure:
```
file-with-link
|---- index.html
subdirectory
|---- my-file
        |---- index.html
```
In the generated `my-file/index.html` file, there will be the abovementioned link:
```
<a href="subdirectory/my-file.md">My Link</a>
```
This link does not work, since the file name changed in the build, while the target of the link did not change.

Is there a convenient way to either **change the name of the folder in the build** or the **target of the link**, so the link works again? It is no option to change the abovementioned link.

**Comment by Keats** [comment]
I think you're looking for https://www.getzola.org/documentation/content/linking/#internal-links ?

**Comment by judgeNotFound** [comment]
@Keats Thank you for the answer. Sadly, this forces me to change every link I have. But this is too much effort for the documentation I have to migrate with. Is there a different way, which only requires a configuration change?

**Comment by Keats** [comment]
Nope, if you don't use `@/` it assumes you know what you are linking to and won't change anything

**Comment by theowenyoung** [comment]
This is the most painful for me on Zola. I don't want to bind Zola deeply, this will let Zola become the only service to understand my document. 

I like Zola in everything, it's a thoughtful framework. I don't know if I can do anything about this feature.

**Comment by theowenyoung** [comment]
As an alternative method, I changed the Zola source code to support internal links, but not for the relative link, it can only support absolute links, 

Then I can use `content/xxx.md` for internal links, this will work well both local and Zola serve.

Change: https://github.com/theowenyoung/zola/commit/b0b463adb21c2bfe2ea71664459a6967d6a7208a

Forum Post: https://zola.discourse.group/t/custom-content-dir/1242
