### ISSUE TITLE
Simplify documentation with GH action deployment

### ISSUE THREAD

**Issue by piedoom** [Keats/gutenberg#1785]
# Documentation issue

## Summary

It is unnecessary to create a personal access token when deploying to GH actions

## Proposed solution

I recently learned that `secrets.GITHUB_TOKEN` is accessible, negating the need to create a personal access token, simplifying several steps + removing potential security issues that come with PATs.

[This commit](https://github.com/piedoom/doomy/commit/64069ffe3f98210ccf1dfbf765edbb3e987a267a) demonstrates my repository works when my previous `secrets.TOKEN` (which was manually set in secrets) is replaced by `secrets.GITHUB_TOKEN`, which is automatically set by actions. Fixing this documentation would necessitate removing a few sections regarding PATs.

**Comment by Keats** [comment]
I believe PATs might only be needed now if you are publishing from a different repo, I'll have to double check.
