### ISSUE TITLE
Getting started example does not properly deploy to github pages

### ISSUE THREAD

**Issue by psarka** [Keats/gutenberg#1786]
# Documentation issue

## Summary
If one follows the getting started example, the resulting page does not deploy to github pages - the link on the index.html points to
`http://username.github.io/blog` rather than to `http://username.github.io/repo/blog`, even though the `base_url` is configured to the `http://username.github.io/repo/`.

Check out the repro:

https://github.com/psarka/zola-repro-1
https://psarka.github.io/zola-repro-1/

## Proposed solution
Probably `<p>Click <a href="/blog/">here</a> to see my posts.</p>` at the end of  https://www.getzola.org/documentation/getting-started/overview/ should be replaced by something `base_url` aware.

**Comment by Keats** [comment]
Yes, it shouldn't hardcode urls

**Comment by milkspace** [comment]
> Yes, it shouldn't hardcode urls

I solve this problem so:
```
<p>Click <a href="{{ config.base_url }}/blog/">here</a> to see my posts.</p>
```

**Comment by brleinad** [comment]
Thanks @milkspace! I just opened #1811 with your solution. 
I tested it out in a fork of psarka's [repo](https://github.com/brleinad/zola-repro-1).
