### ISSUE TITLE
[Question] - Is there a way to generate internal links without the base_url prefix ?

### ISSUE THREAD

**Issue by thomascenni** [Keats/gutenberg#1791]
Hello,
Zola generates full urls, I didn't find in the documentation a way to generate relative urls.
This is very important when you generate deploy previews of a PR or branch using services like Netlify or Cloudflare Pages, when the url of the website is not the production one.
Thanks!

**Comment by Keats** [comment]
You can use normal relative links but those won't get checked.
For the specific preview usecase though, you can just use the --base-url switch like so: https://github.com/getzola/zola/blob/master/netlify.toml#L9-L10

**Comment by thomascenni** [comment]
Thanks for the rapid answer!
Would it be possible in the future to have an option to check the links but to use relative links?

**Comment by Keats** [comment]
Probably not, relative links can point to anything, including things added after the build

**Comment by thomascenni** [comment]
Hi, may be I was not clear, something like:

**get_relative_url**(path="@/services.md")

similar to the current function get_url(path="@/services.md") which checks the page and inserts the full url.

**Comment by Keats** [comment]
Ah no, it's not planned.
