### ISSUE TITLE
IInconsistencies with syntax highlighting

### ISSUE THREAD

**Issue by videbar** [Keats/gutenberg#1792]
# Bug Report

## Environment

Zola version: 0.12.2

## Expected Behavior
According to the [configuration documentation](https://www.getzola.org/documentation/getting-started/configuration/), syntax highlighting can be turned on inside the `[markdown]` section:

```
# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = false
```

## Current Behavior
The the only way of turning on syntax highlighting is by specifying `highlight_code = false` *outside* of the `[markdown]` section, otherwise it just doesn't work.

## Step to reproduce
Place the `highlight_code = true` inside the `[markdown]` section.

**Comment by Keats** [comment]
The documentation is for the current version, 0.15.
