### ISSUE TITLE
Provide path of the file from which the shortcode was invoked

### ISSUE THREAD

**Issue by agluszak** [Keats/gutenberg#1793]
I'm trying to write a shortcode which includes a syntax-highlighted code from a file. I'm using the new colocation feature.

My shortcode currently looks like this:
````
{% set text = load_data(path=path, format="plain") -%}
{% set file_name = path | split(pat="/") | last -%}

```{{ language }}
{{ text }}
```

(Download the source code for this example: [here]({{ file_name }})
````
Given that file `content/lessons/4_enums/enums.rs` exists, in `content/lessons/4_enums/index.md` I write
```
{{ include_code_sample(path="lessons/4_enums/enums.rs", language="rust") }}
```

Ideally I'd like to be able to write 
```
{{ include_code_sample(path="enums.rs", language="rust") }}
```

I think for that it would be necessary to provide the path of the file from which the shortcode was invoked. 

Unless there is some other way to achieve that, I would be happy to implement the change myself if you provide some guidance.

**Comment by agluszak** [comment]
It *may* be related (because of colocation), so I'll ask the question here:
it appears that you cannot use `get_url` with colocated resources.
In the example above `get_url(path="content/lessons/4_enums/index.md")` works, but `get_url(path="content/lessons/4_enums/enums.rs")` does not

**Comment by Keats** [comment]
See https://github.com/getzola/zola/pull/1779 for the colocation, it might affect you.

As for adding the map to the shortcode context, it's doable but it's probably better to wait till it's a bit cleaned up: https://github.com/getzola/zola/blob/next/components/rendering/src/context.rs#L34 as right now it only passes the path to the .md file to the context I believe?
