### ISSUE TITLE
[Question] Shortcode that relies on taxonomies

### ISSUE THREAD

**Issue by idubrov** [Keats/gutenberg#1796]
Hello!

I want to calculate some "totals" aggregated by a specific taxonomy, and use a shortcode to embed these aggregates in Markdown.

Say, I have a taxonomy "projects" and every page with "projects" assigned has `extra.total` variable with hours spent on the project. I want shortcode that would render a table with all the projects and total hours spent on each.

The issue is that I don't see a way to pass taxonomies to a shortcode.

1. Shortcodes cannot use `get_taxonomy` function.
2. I cannot pass variable like this: `{{ totals(components = get_taxonomy(kind = "projects")) }}`

Are there any workarounds that would allow me to have my page with totals to be written as a Markdown content with totals page included somehow? 

I mean, I can always design my page with totals as a standalone template, but I would prefer to have content written in Markdown.

**Comment by Keats** [comment]
That's not possible currently. The `get_taxonomy` fn needs the internal `library` which is filled after rendering Markdown. There are no workarounds that I'm aware of

**Comment by idubrov** [comment]
Understood. Thank you!
