### ISSUE TITLE
Taxonomies in multilanguage sites seem to be broken

### ISSUE THREAD

**Issue by vorot** [Keats/gutenberg#1797]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior
Tell us what should have happened.

* Have a 3-language site. define 2 taxonomies for the default language (tags,authors) and one for each other language (tags)
* Build site
* Taxonomies are generated

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.

* Taxonomies are empty
 
## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

See above.

The commit that seems to fix this problem: https://github.com/vorot/zola/commit/91ebc467c4a5a6a2e3a991e1a0be22275d1c500a

**Comment by Keats** [comment]
Weird that there are no tests covering that, we do test that the pages are created but not that there is content. Taxonomies are due for a full rewrite in the next version, I'll make sure it is tested thoroughly. I think your commit is fine as is though
