### ISSUE TITLE
[Feature Request] HTML Minification Alternate mode.

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1798]
I just recently migrated my blog from Hugo to Zola.
I also built a new css framework and a new zola theme, both of which I plan to publish after testing a while longer.

One thing I am wondering about is the zola minification.
```
# When set to "true", the generated HTML files are minified.
minify_html = false
```

On my old hugo site there was a way to minify my html so that indentation, blank lines, and comments were removed, but it would do so without cramming it all onto one line, keeping all the code on their respective lines. For example this:
```html
  <nav>

    <header>
        <h1><a href="https://www.example.com">EXAMPLE</a></h1>
    </header>

    <div overflow>
        <ul>
            <!-- The main site. -->
            <li><h2><a href="https://www.example.com/about/">About</a></h2></li>
            
        </ul>
    </div>

  </nav>
```

would become:

```html
<nav>
<header>
<h1><a href="https://www.example.com">EXAMPLE</a></h1>
</header>
<div overflow>
<ul>            
<li><h2><a href="https://www.example.com/about/">About</a></h2></li>
</ul>
</div>
</nav>
```

Would absolutely love a feature like this in zola.

**Comment by Keats** [comment]
I don't think this is possible in the minify library we're using: https://docs.rs/minify-html/latest/minify_html/struct.Cfg.html

**Comment by Jieiku** [comment]
ah ok, appreciate the quick response. Will see if I can find any other crates that might do the job.

**Comment by Jieiku** [comment]
Is this the same minify-html? https://github.com/wilsonzlin/minify-html

I noticed on the page it says it has 3 modes:
collapse whitespace
destroy whitespace
trim whitespace

the trim whitespace is the one I am looking for, collapse even looks like it might work, its the destroy option I don't like.

hmmm I just re-read that page, it sounds as though minify-html automatically decides  which mode to use, so three modes are there but are not exposed as options....

**Comment by Keats** [comment]
Yeah exactly it doesn't expose it. To be honest, I don't think I would expose that as an option even if it was the case.

**Comment by GlenDC** [comment]
Would there be a way to disable the "minification" all together. I honestly do not really mind if content is not minified, for payload compression solves already the biggest part of the problem IMHO.

**Comment by Keats** [comment]
minification is opt-in, so you should not see any minification unless you set `minify_html = true` in your config.toml

**Comment by Jieiku** [comment]
I reached out to the developer of minify-html and mentioned not condensing it down to one line as an additional mode. They suggested I use a formatter instead(https://github.com/wilsonzlin/minify-html/issues/74). I have unfortunately not found a good html formatter yet. My plan was to have the formatter run after zola build finishes. If anyone knows of a good html formatter please let me know.

**Comment by Jieiku** [comment]
# Update:

When I was first starting with Tera, I really should have searched for a way to fix the formatting, I just assumed it was a shortcoming of tera templates.

This is the proper way to fix formatting: https://tera.netlify.app/docs/#whitespace-control

Anyone finding this post that wants nicely formatted code without minification should take the time to properly set the whitespace control. Unfortunately a lot of themes do not do this properly, but if they are simply using minify = true then it probably dont matter to them. I am currently going through my Theme and fixing all the indentation and whitespace.

(prettier can still be useful for spotting validation issues in your html code which is why I did not remove this info from the post.)

# OLD:

Currently I am using this:

```bash
sudo npm install --global prettier

zola build && cd public && prettier --bracket-same-line true --print-width 9999999 --write . && find . -type f -name '*.html' -exec sed -i '/^$/d' {} +
```

`--bracket-same-line true` this keeps it from splitting tags across mutiple lines
`--print-width 9999999` this also keeps it from splitting tags across multiple lines, very apparent with meta tags
`--write .` this makes it rewrite the files recursively in the current directory.
`find . -type f -name '*.html' -exec sed -i '/^$/d' {} +` this strips the empty lines from all html files recursively

This does a good job of validating/correcting tags and also proper indentation, and sed takes care of the empty lines.
