### ISSUE TITLE
Zola 0.16.0 thread 'main' panicked at 'could not find directory containing config file'

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1802]
# Bug Report

I was using Zola 0.14.0 over the last few months, as I learned to use zola and tera templates.
Yesterday I wanted to do cache busting on my css, but there was a bug in 0.14.0 that was fixed in 0.14.1, so I decided to update.

so I updated my previously built zola, and so far it has worked without issue for my existing zola sites, but today I tried to generate a new site which is generating an error:

thread 'main' panicked at 'could not find directory containing config file', src/main.rs:23:28

## Environment

Zola version: 0.16.0
OS: Kubuntu 21.10

## Expected Behavior
When I was on 0.14.0 it did not have this error.

## Current Behavior
```bash
zola init mysite
thread 'main' panicked at 'could not find directory containing config file', src/main.rs:23:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried setting the environment variable, but it does not seem to provide any additional info unless im doing it wrong:
```bash
RUST_BACKTRACE=1
echo $RUST_BACKTRACE
1
zola init mysite
thread 'main' panicked at 'could not find directory containing config file', src/main.rs:23:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Step to reproduce

```bash
zola -V
zola 0.16.0
zola init mysite
thread 'main' panicked at 'could not find directory containing config file', src/main.rs:23:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Jieiku** [comment]
I just noticed that 0.16.0 is newer than any release listed here: https://github.com/getzola/zola/tags

so I think I must be on the dev branch.... going to git clone using the 0.15.3 tag and try again.

edit: git branch reports that I am on the master branch

edit2! downgrading to 0.15.3 and the problem is gone:

```bash
cd ~/zola
git checkout tags/v0.15.3
cargo build --release
chmod a+rx ~/zola/target/release/zola
sudo cp ~/zola/target/release/zola /usr/local/bin/zola
zola -V
zola 0.15.3
zola init mysite
```

**Comment by Keats** [comment]
Yep, see https://github.com/getzola/zola/pull/1741#discussion_r829486813 I'll fix it the next time I work on the project. Closing as it's already mentioned on the next PR.

**Comment by Jieiku** [comment]
awesome! thank you!
