### ISSUE TITLE
get_env() always fails

### ISSUE THREAD

**Issue by timharek** [Keats/gutenberg#1805]
# Bug Report

## Environment

Zola version: 0.15.3

### Scenario 1
When dotenv (`.env`) is defined `get_env()` should be able to retrieve the variables defined inside.

### Scenario 2
When a variable is exported to global env using `export <variable-name>`, `get_env()` should be able to retrieve variables stored there.

## Current Behavior
When doing either scenario 1 or 2, I get:
```
Error: Failed to render section '<project_path>'
Reason: Failed to render 'index.html'
Reason: Function call 'get_env' failed
Reason: Environment variable `<token_name>` not found
```

However, I'm able to get enviroment variables that always are stored in as env's, not new ones.

## Step to reproduce
Using `get_env()` anywhere in any template to try to retrieve an enviroment variable from etiher a dotenv-file or from a newly exported variables using `export`.

**Comment by Keats** [comment]
> When dotenv (.env) is defined get_env() should be able to retrieve the variables defined inside.

It shouldn't no. Zola doesn't know anything about .env files, if you want to use them you need to load them in some way.

**Comment by timharek** [comment]
But I still can't access newly added env variables that has been exported. Is `get_env()` only meant for variables like `$USER` etc?

**Comment by Keats** [comment]
It is only for environment variables yes

**Comment by mwcz** [comment]
> But I still can't access newly added env variables that has been exported. Is `get_env()` only meant for variables like `$USER` etc?

Maybe try:

```
source .env && zola build
```

**Comment by timharek** [comment]
Thanks for the reply @mwcz!

But that doesn't work either, I can't access the variables for some strange reason. I also tried `source .env && zola serve` with no luck.
