### ISSUE TITLE
Add syntax highlighting for SystemVerilog

### ISSUE THREAD

**Issue by KennethWilke** [Keats/gutenberg#1810]
Hi there! I wanted to put in a request for SystemVerilog highlighting support. I'm still learning Zola and not familiar with the syntax highlight format, but I did find a plugin for Sublime Text that looks like it has the right stuff:

https://github.com/TheClams/SystemVerilog/blob/master/SystemVerilog.sublime-syntax

I'm trying to use this one locally but haven't quite figured it out, but will continue to tinker with it

**Comment by KennethWilke** [comment]
Ah, my issue was trying to use `extra_syntaxes` instead of `extra_syntaxes_and_themes`. I'm guessing this was renamed but maybe not updated at https://github.com/getzola/zola/blob/master/docs/content/documentation/getting-started/configuration.md?plain=1#L97 ?

**Comment by Keats** [comment]
Yep, it looks like documentation needs to be updated.
