### ISSUE TITLE
page.taxonomies should return array of TaxonomyTerm

### ISSUE THREAD

**Issue by mishushakov** [Keats/gutenberg#1815]
currently page.taxonomies returns `HashMap<String, Array<String>>`, but i suggest that instead `Array<TaxonomyTerm>` should be returned as it contains more information about the tag

**Comment by Keats** [comment]
This is just getting the information you set in the front-matter via `page.meta.taxonomies`. I'm a bit afraid of adding taxonomies in 2 places on the object, it's a bit confusing.
