### ISSUE TITLE
Themes site, some of the themes are missing.

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1818]
# Documentation issue
This has to do with themes site: https://www.getzola.org/themes/

## Summary
I took the time to browse through all of the pull requests and see if there were any missing themes, I found a few. At first I thought maybe it was because there were issues with these themes, but some of them I think look really nice.

## Proposed solution
The original authors of all these themes already submitted pull requests, but maybe some of them did not properly add it as a git submodule, something certainly stopped them from being listed. I would be willing to create new pull requests for all/some of these if it would be helpful:

| Theme | Original Pull Request | Repository | Demo |
| --- | --- | --- | --- |
| hermit | https://github.com/getzola/themes/pull/16 | [Repo](https://github.com/VersBinarii/hermit_zola) | [Demo](https://versbinarii.gitlab.io/blog/) |
| particle | https://github.com/getzola/themes/pull/42 | [Repo](https://github.com/svavs/particle-zola) | [Demo](https://particle-zola.vercel.app/) |
| hephaestus | https://github.com/getzola/themes/pull/46 | [Repo](https://github.com/BConquest/hephaestus) | [Demo](https://bryantconquest.com/) |
| emily | https://github.com/getzola/themes/pull/60 | [Repo](https://github.com/kyoheiu/emily_zola_theme) | [Demo](https://emily-zola-theme.netlify.app/) |
| nasm | https://github.com/getzola/themes/pull/54 | [Repo](https://github.com/lucasnasm/nasm-theme) | [Demo](https://lucasnasm.github.io/) |
| soapstone | https://github.com/getzola/themes/pull/56 | [Repo](https://github.com/MattyRad/soapstone.git) | [Demo](https://mattyrad.github.io/soapstone/) |
| zolastrap | https://github.com/getzola/themes/pull/71 | [Repo](https://github.com/marcodpt/zolastrap) | [Demo](https://marcodpt.github.io/zolastrap/) |
| zhuia | https://github.com/getzola/themes/pull/72 | [Repo](https://github.com/gicrisf/zhuia) | [Demo](https://zhuia.netlify.app/) |

When I submitted Abridge theme I had trouble but eventually figured it out: https://github.com/getzola/themes/pull/76

These were the steps I took:

create a fork of: https://github.com/getzola/themes

Now we will clone that fork, create a new branch, add our new theme as submodule, commit and push this change:
(anyone finding this should replace Jieiku with their own github username, and replace abridge with the name of your theme.)

```bash
git clone https://github.com/Jieiku/themes
cd themes
git branch new-theme
git checkout new-theme
git submodule add https://github.com/Jieiku/abridge abridge
git commit -am "new-theme"
git push --set-upstream origin new-theme
```

Then create the pull request.

**Comment by Keats** [comment]
At least 3 of them are missing metadata (https://github.com/getzola/themes/runs/5735537879?check_suite_focus=true)
As for the others maybe there's a bug in the generating script? Anyway that's more a bug on the https://github.com/getzola/themes repo than zola itself.

**Comment by Jieiku** [comment]
It is not obvious to me which 3 are missing metadata from your link, but if there is anything I can do to help just let me know.

**Comment by Keats** [comment]
You can pull the themes repo, run the generating script and look for missing ones by adding some print statement in the script probably

**Comment by Jieiku** [comment]
This was part of the reason I had trouble following the official readme when I submitted my theme.

The instructions on the [readme](https://github.com/getzola/themes) say to do this:

```bash
git clone https://github.com/getzola/themes
git submodule update --init --recursive
python generate_docs.py DESTINATION_FOLDER
git submodule update --remote --merge
```

when I do that a lot of stuff fails with Permission denied:

```
Cloning into '/home/jieiku/.installs/themes/DeepThought'...
Cloning into '/home/jieiku/.installs/themes/Ergo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:InsidiousMind/Ergo.git' into submodule path '/home/jieiku/.installs/themes/Ergo' failed
Failed to clone 'Ergo'. Retry scheduled
Cloning into '/home/jieiku/.installs/themes/Zulma'...
Cloning into '/home/jieiku/.installs/themes/abridge'...
Cloning into '/home/jieiku/.installs/themes/adidoks'...
git@github.com: Permission denied (publickey).
```

I looked a little closer as to the cause of this:

```
Submodule 'DeepThought' (https://github.com/RatanShreshtha/DeepThought.git) registered for path 'DeepThought'
Submodule 'Ergo' (git@github.com:InsidiousMind/Ergo.git) registered for path 'Ergo'
Submodule 'Zulma' (https://github.com/Worble/Zulma) registered for path 'Zulma'
Submodule 'abridge' (https://github.com/Jieiku/abridge) registered for path 'abridge'
Submodule 'adidoks' (git@github.com:aaranxu/adidoks.git) registered for path 'adidoks'
```

notice the ones that fail... Ergo and adidoks, they dont have a URL they instead show git@github.com:InsidiousMind/Ergo.git.. etc

Is it intentional that the one that look like that should fail? there are quite a few of them.
Would it not be better to change those to the url path of the git repository? instead of that username syntax?

Maybe this is an issue with my git environment, I am not super experience with git, if it is somehow my fault then i am not sure what I have done wrong.

**Comment by Keats** [comment]
It should only be http, `git@..` will fetch via ssh which might not work as you can see

**Comment by Jieiku** [comment]
ok, maybe this is something I can fix and submit a pull request for, will see what I can figure out.
