### ISSUE TITLE
No mention that height variable is needed in resize_image shortcode

### ISSUE THREAD

**Issue by adamdewey** [Keats/gutenberg#1821]
# Documentation issue

## Summary
Took me a loooooong time to realise that I needed to add `height=0` in this code: 

`{{ resize_image(path="/docs/getting-started/folder/image.png", width=100, height=0, op="fit_width") }}`

There is no mention of the variable in the [docs](https://www.getzola.org/documentation/content/image-processing/), in fact it says you don't need it:

>Resizes the image such that the resulting width is width and height is whatever will preserve the aspect ratio. The height argument is not needed.

 But my build kept failing with the following message until I added in the height variable: 

`Reason: Variable 'height' not found in context while rendering 'shortcodes/resize_image.html'`

## Proposed solution
A quick explanation of what you would like to see to solve the issue.
If you want to add content, please explain what you were looking for and what was
your process while looking at the current documentation.

**Comment by Keats** [comment]
It should be optional, looks like a bug.

**Comment by kartva** [comment]
I've tried to replicate your report by writing a few tests in the codebase and trying it in an actual Zola project but have failed so far.

It seems you've written a shortcode which calls the `resize_image` function internally. Did you make sure to check if `height` was passed to your shortcode and exists as a variable (`if height is defined`) before attempting to pass `height` as an argument to `resize_image`?

**Comment by kartva** [comment]
The way I've been able to replicate the error is:

File `templates/shortcodes/resize_image.html`
```
{{ resize_image (path=path, height=height) }}
```

And then calling it without a height:

File `index.md`
```
{{ resize_image(path="static/tree_picture.jpg", width=100) }}
```


```
Reason: Failed to render resize_image shortcode
Reason: Failed to render 'shortcodes/resize_image.html'
Reason: Function call 'resize_image' failed
Reason: Variable `height` not found in context while rendering 'shortcodes/resize_image.html'
```

Instead, what you might want to do is:
File `templates/shortcodes/resize_image.html`
```
{%- if height is defined -%}
	{{ resize_image (path=path, height=height, op="fit_height") }}
{%- elif width is defined -%}
	{{ resize_image (path=path, width=width, op="fit_width") }}
{%- endif -%}
```

**Comment by adamdewey** [comment]
Apologies - it must have been called by the theme I am using. 

Thanks for looking into it!

Will try your suggestions :)
