### ISSUE TITLE
Unable to generate ToC in a page

### ISSUE THREAD

**Issue by segeljakt** [Keats/gutenberg#1825]
# Documentation issue

## Summary
I want to add a table of contents in my page but I can't get it to work.

The docs https://www.getzola.org/documentation/content/table-of-contents/ tell me to use a template.

In `templates/shortcodes/generate_toc.html` I have added the following:

```
{% if page.toc %}
    <ul>
    {% for h1 in page.toc %}
        <li>
            <a href="{{ h1.permalink | safe }}">{{ h1.title }}</a>
            {% if h1.children %}
                <ul>
                    {% for h2 in h1.children %}
                        <li>
                            <a href="{{ h2.permalink | safe }}">{{ h2.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endif %}
```

In my `content/blog/test.md` I have:
```
+++
title = "Test"
date = 2022-04-12
+++
# Foo

{{ generate_toc() }}

## Bar

## Baz
```

## Proposed solution

When I run `zola serve` I can see that zola finds and runs the shortcode, but no table of contents is generated. It seems `page.toc` is empty. Is there an example somewhere of how to get it working? I also tried using `section.toc` but that gives a compilation error.

**Comment by Keats** [comment]
You can't use the table of content in a shortcode: the shortcodes are rendered while parsing the Markdown so in your example we would have only seen Foo so far.

**Comment by segeljakt** [comment]
Hmm, ok. How do I use it in this case? Forgive me but I don't understand where I should put the code shown in the docs 👀

**Comment by Keats** [comment]
In the template directly, you can use the snippet from https://www.getzola.org/documentation/content/table-of-contents/

**Comment by segeljakt** [comment]
Perfect 👍 it works!
