### ISSUE TITLE
Overriding built-in shortcodes doesn't work

### ISSUE THREAD

**Issue by shadiradio** [Keats/gutenberg#1832]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior
Zola includes some built in shortcodes for very common functionality (like YouTube), and the documentation says these can be overridden by placing a file with the same name in the templates/shortcodes path.

## Current Behavior
I could not get this to work using Zola 0.15.3. If I place a "youtube.html" file in the templates/shortcodes path, Zola serve & build will still use the built-in YouTube shortcode generator.

## Step to reproduce
- Place a custom "youtube.html" shortcode file in templates/shortcodes
- Use the shortcode in some content
- Run "zola serve" and notice the custom code is not output

**Comment by Keats** [comment]
Looks like a regression in the template loading that changed recently, I'll handle it.
