### ISSUE TITLE
dependency on mime_guess is too loose

### ISSUE THREAD

**Issue by jonassmedegaard** [Keats/gutenberg#1845]
`Cargo.conf` declared a dependency on `mime_guess` 2.0 but `src/cmd/serve.rs` calls function `.essence_str()` which was introduced in v2.0.2.

**Comment by jonassmedegaard** [comment]
Ahh, it is not really `mime_guess` but its pulling in `mime` which needs to be at least v0.3.15.

So the most loose declaration is to add a (tightened) dependency on `mime`, like this:
```
# For mimetype detection in serve mode
mime_guess = "2.0"
# For essence_strr() function
mime = "0.3.15"
```

**Comment by Keats** [comment]
When is that an issue?

**Comment by jonassmedegaard** [comment]
When building without following `Cargo.lock` - e.g. when building in a constrained environment where only a subset of the revisions released at crates.io is available.

Concretely I am working on packaging zola for official inclusion in Debian.  There is still about 100 crates missing, including mime v0.3.16 (Debian has only mime v0.3.9 which fails to build complaining that function essence_str() is undefined.
