### ISSUE TITLE
Consolidating search related Javascript Files.

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1846]
I just finished integrating the search into the [Abridge theme](https://abridge.netlify.app/)

Currently when you `zola build` with `build_search_index = true` you get two files:

elasticlunr.min.js
search_index.en.js

and to make use of these you also need to integrate a search into your site.

you could use this: https://github.com/getzola/zola/blob/master/docs/static/search.js

but I recommend this one: https://github.com/aaranxu/adidoks/blob/main/static/js/search.js

So that is a total of 3 javascript files. I would like to consolidate these down to a single javascript file. The problem is that they all use function and var names `e`. I assume this is because of the minification mangle.

I manually edited the search.js file and changed occurrences of `e` to `k`  but `zola build` automatically generates `elasticlunr.min.js` and `search_index.en.js`

I am wondering how Zola generates these files, is there a way they could use different function and variables names, so that they do not both use `e`

**Comment by Keats** [comment]
`elasticlunr.min.js` is the build from the elasticlunr library, `search_index.en.js` is generated by https://github.com/mattico/elasticlunr-rs and the last one is hand written. The first 2 are generated by Zola so it's unlikely that you will be able to combine them easily.

**Comment by Jieiku** [comment]
Thanks, I managed to consolidate `elasticlunr.min.js` and `search.js` into a single [search.min.js file](https://github.com/Jieiku/abridge/blob/master/static/search.min.js).

The `search_index.en.js` is still a separate file, ran into to many problems trying to bundle this.

**Comment by Jieiku** [comment]
I have it working now, the issue with bundling the index with the other js files is that the index needs to be in the file FIRST.

You can see it in action at the [abridge theme demo](https://abridge.netlify.app/) It now only loads a single javascript file.

`elasticlunr.min.js` and `search.js` are small enough that by merging them with the index file into a single js file you get more out of the gzip compression, and the benefit of only needing to load a single js file.
