### ISSUE TITLE
[Feature Request] configuration option to append js files to index js file.

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1850]
Currently when you `zola build` with `build_search_index = true` you get two files:

search_index.en.js
elasticlunr.min.js

and you also need a search file to integrate it into your site: https://github.com/aaranxu/adidoks/blob/main/static/js/search.js

These javascript files can be combined into a single javascript file, so long as the index is at the top of the file.

You can see it in action here: https://abridge.netlify.app/

I am suggesting a new config.toml option to specify js files to append to the end of the `search_index.en.js` file

You can of coarse do this manually now, but it will only work for `zola build`, not for `zola serve` which is why I am requesting this feature.

```toml
build_search_index = true

search_index_append = [
    {file = "/src/elasticlunr.min.js"},
    {file = "/src/search.min.js"},
]
```

**Comment by Keats** [comment]
This won't be added, it's something very specific and whether the resulting JS file would work depend on whatever minification you've done.

**Comment by Jieiku** [comment]
When I first started down this journey I was under the impression that you had to rename functions and variables because of how many issues I was having, but I have since found that you do not have to do any trickery or special minification, you just have to combine the files in the correct order.

So now you can simply cat the files together and it all works:

`cat search_index.en.js elasticlunr.min.js search.min.js > out.js`

I used the `search_index.en.js` and `elasticlunr.min.js` that zola itself creates with `zola build`

here is the `search.min.js` that I used: https://github.com/Jieiku/abridge/blob/master/static/search.min.js

I just rebuilt the [abridge demo site](https://abridge.netlify.app/) using only `cat` to combine the files: [single js file from cat](https://abridge.netlify.app/search.min.js)

@Keats could you please consider this feature? Also if you are simply to busy for this feature but wouldn't mind a pull request let me know and I will try my hand at adding it.

**Comment by Keats** [comment]
> could you please consider this feature? 

I don't want Zola to be in the business of managing JS files, that's not going to be added.

**Comment by Jieiku** [comment]
Fair enough, does zola support any kind of custom pre execution?

If so I could build the index and merge the js files there in my own custom script...

I just am not sure how to go about this since `zola build` and `zola serve` are what create the `search_index.en.js` file.

**Comment by Keats** [comment]
> Fair enough, does zola support any kind of custom pre execution?

Not currently.

> I just am not sure how to go about this since zola build and zola serve are what create the search_index.en.js file.

This file will change everytime you update your content, you probably don't want to include it with the libraries. If you do, repeat visitors will never use cached resources (elasticlunr and your site JS).

**Comment by Jieiku** [comment]
You are absolutely correct, for some reason it had not occurred to me that the index will change every time you add content but the other files will not.

Thanks for chatting with me about this, sometime you don't think of something until somebody else points it out.
