### ISSUE TITLE
minifying html causes linenos to break

### ISSUE THREAD

**Issue by EvilMuffinHa** [Keats/gutenberg#1854]
# Bug Report

## Environment
Firefox on Archlinux

Zola version: 0.15.3

## Expected Behavior

When minifying html, the the codeblock with linenos should not break.

## Current Behavior

Currently, when writing a codeblock with linenos with `minify_html = true` on, it seems to overflow and go on into other sections of the article. 
Without minify_html, the code looks like this:
![image](https://user-images.githubusercontent.com/47578209/167283709-bfc4fed9-e97d-4a79-a4cc-ea5d78e68dac.png)

When minify is added, it now looks like this:
![image](https://user-images.githubusercontent.com/47578209/167283702-a534bf0c-fc69-4fee-922c-e5ab48d9e0c8.png)

## Step to reproduce
Create a zola project and add `minify_html = true` to the config. Then create a codeblock in a markdown page with linenos and text afterwards.

**Comment by Keats** [comment]
I believe this is already fixed in the `next` branch, can you try to build it?

**Comment by mwcz** [comment]
Original issue for reference https://github.com/getzola/zola/issues/1743

**Comment by Keats** [comment]
Yep, closing as duplicate.

**Comment by EvilMuffinHa** [comment]
> I believe this is already fixed in the `next` branch, can you try to build it?

Yep, tried it and it works with the fix. Thanks a lot!
