### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1857]
The Paginator causes a redirect when you click page 1

- to reproduce go one of these: [deepthought](https://deepthought-theme.netlify.app/posts/page/2/) or [blow](https://tchartron.com/categories/it/page/2/)
- scroll down to the paginator, click page 1

Interestingly the Previous and Next page does not have this problem, you can click previous to page 1 and it works correctly.

The other issue is the links in the paginator are missing the trailing slash.

If you inspect the links you will notice:

https://deepthought-theme.netlify.app/posts/page/1
https://deepthought-theme.netlify.app/posts/page/2
https://deepthought-theme.netlify.app/posts/page/3

When you click them you see that the trailing slash gets added by most web servers, however on some nginx configurations this will actually cause the page load to just timeout because of the missing trailing slash.

It might be that this is part of the design, and I just needed to use something like the solution that I have, if so just close this, I was not sure so I thought I should make a report just incase.

I have just found that the page 1 redirect issue does NOT exist on [Zolastrap](https://marcodpt.github.io/zolastrap/articles/page/2/), and it appears they use a paginator macro, they do have the trailing slash issue, so maybe I will extend their paginator so it also takes care of the trailing slash.

Here is the Macro I am using to resolve these issues (extended/modified from zolastrap):

```html
{%- macro pagination(paginator)%}
  {%- if paginator.number_pagers > 1 %}
      <nav>
        <div>{%- if paginator.previous %}<a href="{{ paginator.previous | safe }}">&#60; Previous</a> {% endif %} </div>
        <div>
          <ul>
            {%- for i in range(start=1, end=paginator.number_pagers+1) %}
            <li>
              {%- if i == paginator.current_index %}
              <a class="cnav">{{i}}</a>
              {%- elif i > 1 %}
              <a href="{{paginator.base_url | safe }}{{i ~ '/'}}">{{i}}</a>
              {%- else %}
              <a href="{{paginator.first | safe }}">{{i}}</a>
              {%- endif %}
            </li>
            {%- endfor %}
          </ul>
        </div>
        <div>{%- if paginator.next %}<a href="{{ paginator.next | safe }}">Next &#62;</a>{% endif %} </div>
      </nav>
  {%- endif %}
{%- endmacro %}
```

**Comment by Keats** [comment]
I believe this is working as intented?

**Comment by Jieiku** [comment]
If you say it is, then it is! Your certainly the expert on what it should or should not be doing.

I just noticed something with my current paginator macro, on a small blog starting out its fine, but with 100s of pages it wont be, Say I am on page 8 of 200, it needs to be like this:

1 .. 7 8 9 .. 200

instead of like this:

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ....... all the way to 200 lol

**Comment by Keats** [comment]
> Say I am on page 8 of 200, it needs to be like this:
> 1 .. 7 8 9 .. 200

Yep, I would just have like you do: first/prev/current/next/last

**Comment by Jieiku** [comment]
I resolved this: https://abridge.netlify.app/

https://github.com/Jieiku/abridge/blob/master/templates/macros/macros.html
