### ISSUE TITLE
Simplify Theme Discountinued

### ISSUE THREAD

**Issue by cosmicqbit** [Keats/gutenberg#1863]
# Simplify Theme Github URL not found

## Summary
The theme is still being indexed on [getzola.org](https://www.getzola.org/themes/simplify/) despite it has been [taken down](https://github.com/tarunjana/simplify) by the author.   

## Suggestion
Remove the mention of Simplify Theme from the documentation. 

Thank you :)

**Comment by Keats** [comment]
Ah, looks like my automated themes PR system doesn't delete things, I'll need to fix that
