### ISSUE TITLE
extra_syntaxes_and_themes does not appear to work unless in base directory?

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1865]
# Bug Report

This works:

```toml
[markdown]
extra_syntaxes_and_themes = ["highlight_themes"]
```

nested deeper does not appear to work:

```toml
[markdown]
extra_syntaxes_and_themes = ["themes/abridge/highlight_themes"]
```

## Environment 
Manjaro KDE

Zola version: 0.15.3

## Expected Behavior
Would be killer if the highlight themes could be loaded from my sites theme.

## Current Behavior

```zsh
zola serve
Building site...
Error: Highlight theme ayu-dark-abridge not available.
You can load custom themes by configuring `extra_syntaxes_and_themes` to include a list of folders containing '.tmTheme' files
```

## Step to reproduce
- try to reference a nested path as the themes folder
-  zola build

**Comment by Jieiku** [comment]
Would also be useful if you could specify a directory that may not exist, then you could cover both basis in a theme.

```toml
[markdown]
extra_syntaxes_and_themes = ["highlight_themes", "themes/abridge/highlight_themes"]
highlight_code = true
highlight_theme = "ayu-dark-abridge"
```

without this error:

```
Building site...
Failed to build the site
Error: IO error for operation on /home/jieiku/.dev/abridge/themes/abridge/highlight_themes: No such file or directory (os error 2)
```

I did think of one possible solution, which is to just submit the themes to the root zola project, but I still think this is worthwhile to implement

**Comment by Keats** [comment]
I think a directory not existing should be an error but the usecase in the original post should be fixed

**Comment by Jieiku** [comment]
Two people confirmed that a sub directory DOES work.

I have been coding all day every day so I must have just gotten foggy eyes and overlooked something, it does actually work.

I apologize for the noise. Thank You!
