### ISSUE TITLE
get_image_metadata values for width and height are backwards for SVG images

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1877]
# Bug Report
Zola version: 0.15.3

It seems that get_image_metadata gets the width and height backwards? It may only be for svg images.

I was extending the imghover shortcode that I wrote, so that width and height are optional parameters, (since we can query this data with get_image_metadata)

You can see the result here: https://abridge.netlify.app/overview-images/#usage-same-path-1

and here is the repository: https://github.com/Jieiku/abridge

and here is the shortcode: https://github.com/Jieiku/abridge/blob/master/templates/shortcodes/imghover.html

```rs
      {%- set metafile = page.path ~ path ~ sourcepath %}
      {%- set meta = get_image_metadata(path=metafile) %}
      {%- set padding = meta.height / meta.width * p %}
      /* height={{meta.height}} width={{meta.width}} (THIS IS BACKWARDS!?) */
```

The image in question is 600 width and 400 height, but get_image_metadata() report it the other way around.

![2022-05-27_00-55-45](https://user-images.githubusercontent.com/106644/170656439-e93d11a6-e223-4d2a-8cbd-f3a3b50a0045.png)

**Comment by Keats** [comment]
yep it looks reversed in the code

**Comment by mre** [comment]
Sorry about that; quite embarrassing. I can send a PR to fix it later today. Alternatively you can fix it by swapping `w` and `h` at the end of this line: https://github.com/getzola/zola/blob/96db5231e74599815df381fbf90d499c2d5b3814/components/imageproc/src/lib.rs#L587
There's also a typo in "Unfortunately" below that line that we could fix as well.

**Comment by Jieiku** [comment]
@mre is swapping the w and the h the proper way of fixing this, or just a workaround that I could do?

If that is the proper way of fixing it then I can do the pull request for you.

(love rust! but still a newbie at using it)

**Comment by mre** [comment]
Yes, please go ahead. It's the proper way to do it in my opinion because my SVG Metadata crate returns the dimensions in swapped order and I don't want to change that because of other use cases. Perhaps you'd like to add a comment about that fact as well so people don't confuse it for a typo.
