### ISSUE TITLE
Unable to reliably get the current URL on a multilang site

### ISSUE THREAD

**Issue by bemyak** [Keats/gutenberg#1878]
# Bug Report

There two ways of getting the current web-page URL:

* Use `current_url` variable
* Call `get_url(path=current_path, lang=lang)` function

Both of these work identically for the default language, however, the behavior is different and sometimes unexpected for a secondary language (`fi` in the examples below).

## Environment

Zola version: 0.15.3, `next`

## Expected Behavior

URLs reported by `current_url` and `get_url(path=current_path, lang=lang)` match each other and the actual URL

## Current Behavior

* `/fi/`
  *  get_url = /fi/fi
  *  current_url = /fi/
* `/fi/post`
  *  get_url = /fi//fi/post
  *  current_url = /fi/post/
* `/fi/tags` **this is the most problematic part**
  * get_url = /fi//tags
  * current_url = /tags/  <-- lang is missing
* `/fi/tags/fi-tag/`
  *  get_url = /fi//tags/fi-tag
  *  current_url = /tags/fi-tag/ <-- lang is missing again

For most pages, `current_url` gives the correct result, except for taxonomies, where it misses the language part, so `get_url` is _more_ correct here.

This messes up setting the "canonical URLs" for webpages, so some search engines are not happy with it.

## Step to reproduce

Checkout the [attached site](https://github.com/getzola/zola/files/8786693/test-site.zip)

**Comment by Keats** [comment]
This should be an easy fix if someone wants to try.
