### ISSUE TITLE
highlight_themes_css syntect generating invalid css font-style: underline; should be text-decoration: underline;

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#1886]
# Bug Report

If you use css for syntax highlighting and that syntax theme makes use of font-style: underline, then syntect generates invalid css.

```toml
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]
```

![2022-05-31_13-30-36](https://user-images.githubusercontent.com/106644/171279473-2d1c1f4f-0670-45d8-8a77-eede886b7733.png)

## Environment

Zola version: 0.15.3

## Expected Behavior
I do understand that syntect is stuck on an old version, but still felt it was good to document this issue that I ran into today, did not find any other issues mentioning this.

I fixed all of [my css files](https://github.com/Jieiku/abridge/tree/master/sass/syntax) like this:

```shell
sed -i 's/font-style: underline/text-decoration: underline/g' ~/.dev/abridge/sass/syntax/*.scss
```

**Comment by Keats** [comment]
You probably want to report that one to [syntect](https://github.com/trishume/syntect/issues) directly.

**Comment by Jieiku** [comment]
I will, thanks!
