### ISSUE TITLE
Sections in zola

### ISSUE THREAD

**Issue by daveads** [Keats/gutenberg#1893]
Zola version:
Current

## Expected Behavior :
Is there a way to do individualise categories and tags based of a particular section ?

**Comment by Keats** [comment]
I don't understand what you mean sorry

**Comment by daveads** [comment]
Is there a way I could display a taxonomy of a particular section with out including other sections ?

This was the original question...

But I just got my answer to this...

**Comment by Keats** [comment]
Not possible no.

**Comment by daveads** [comment]
Yea not possible except you give that particular section a taxonomy of it's own...
