### ISSUE TITLE
Slowdown in 0.16

### ISSUE THREAD

**Issue by Keats** [Keats/gutenberg#1902]
See https://github.com/getzola/zola/issues/1896#issuecomment-1159227136 for initial speed difference, on https://github.com/theowenyoung/blog

My personal site and the Zola docs seem to build roughly at the same speed, but it might be because they build in <500ms the change is less visible.
The `huge-blog` benchmark in components/site/benches is the same on both master and next for me as well.

**Comment by Keats** [comment]
Anyone seeing the same slowdown? I would like to figure it out before releasing the next version ideally

**Comment by c-git** [comment]
Could you point me to where I can find instructions needed to test and give feedback. I should be able to test on the weekend and provide feedback.

> Anyone seeing the same slowdown? I would like to figure it out before releasing the next version ideally

**Comment by Keats** [comment]
You can git clone this repo, and then `cargo build --release`then running the executable `./target/release/zola` on your site

**Comment by c-git** [comment]
ok that's easy enough will do on the weekend and get back to you.

**Comment by theowenyoung** [comment]
https://github.com/theowenyoung/blog/commit/ee3ee98538ee3b327ed3c0a3f82e4e11fad9b5d0

@Keats it seems that I figured this out. I placed some heavy logic in the `base.html`, it seems that the stable version didn't care that? and the next version could be recalculate many times?

but anyway, I shouldn't write that logic in the `base.html`, when I move it out to the specific pages, the building time is immediately down.

```bash
# ee3ee98538ee3b327ed3c0a3f82e4e11fad9b5d0 commit 

green@green ~/blog (main) $ ../inbox/zola/target/release/zola build
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 138 pages (12 orphan) and 6 sections
Done in 2.0s.
```

Then, I tried the stable version continually, but it was still faster than the next version.

```bash
# ee3ee98538ee3b327ed3c0a3f82e4e11fad9b5d0 commit
green@green ~/blog (main) $ ../inbox/zola/target/release/zola-stable build
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 138 pages (12 orphan) and 6 sections
Done in 1.3s.
```



I also tried the previous heavy logic version, which is `51a4bb92` commit:

The next branch:

```bash
# 51a4bb92 commit 
green@green ~/blog ((51a4bb92...)) $ ../inbox/zola/target/release/zola build
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 138 pages (12 orphan) and 6 sections
Done in 6.6s.
```

The stable branch:

```bash
green@green ~/blog ((51a4bb92...)) $ ../inbox/zola/target/release/zola-stable build
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 138 pages (12 orphan) and 6 sections
Done in 3.0s.
```


Then, I continue to check the heavy logic of my blog, I think `activity.html` may be the suspect template, when I disabled the render of `activity.html`, the next branch will be much faster.

```bash
green@green ~/blog (main) $ ../inbox/zola/target/release/zola build
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 138 pages (12 orphan) and 6 sections
Done in 1.1s.

green@green ~/blog (main) $ ../inbox/zola/target/release/zola-stable build
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 138 pages (12 orphan) and 6 sections
Done in 896ms.
```

The `activity.html` indeed has a heavy logic, cause I need to match the web mention JSON file to  the right post, so I can show the post meta on the [page](https://www.owenyoung.com/en/activity/):

Here is the heavy logic template code:

https://github.com/theowenyoung/blog/blob/ee3ee98538ee3b327ed3c0a3f82e4e11fad9b5d0/templates/activity.html#L16-L43

**Comment by Keats** [comment]
Thanks for the breakdown, I'll investigate!

**Comment by Keats** [comment]
So it's really in the `activity.html` that the slow down happens as you mention, I get the same speed on my machine for building the site with zola 0.15.3 and next by removing the body of the template. I don't really see what would cause so much slowdown from that template though

**Comment by theowenyoung** [comment]
https://github.com/theowenyoung/blog/blob/ee3ee98538ee3b327ed3c0a3f82e4e11fad9b5d0/templates/activity.html#L36-L43

I think the giant pig is here,  it loops all mentions, and every item calls `filter`  to match the post metadata, n^2.

but anyway, it's my own specific logic, I totally accept its speed now.  just confused about why the next branch is slower than stable with the same logic.

**Comment by mwcz** [comment]
@Keats FWIW, my giant site is building on `next` in ~38s on a fairly fast machine.  That's 143,000 pages, syntax highlighting on, no taxonomies.  Is there anything specific you'd like me to test?  Anything that's likely to not scale well on large sites?

The build used to be ~17s and is up to ~38s but I don't think it's related to `next`, just gradually increasing complexity in our templates.  For instance, there is a tera macro for tables of contents in one of our templates that added a lot to the build time.

**Comment by c-git** [comment]
> @Keats FWIW, my giant site is building on `next` in ~38s on a fairly fast machine. That's 143,000 pages, syntax highlighting on, no taxonomies. Is there anything specific you'd like me to test? Anything that's likely to not scale well on large sites?
> 
> The build used to be ~17s and is up to ~38s but I don't think it's related to `next`, just gradually increasing complexity in our templates. For instance, there is a tera macro for tables of contents in one of our templates that added a lot to the build time.

Is that 17s on the current main version compared to 38s on next? (What I'm curious about is, are those times on the same version of the site or is it that it used to be 17s in the past on an older version of your site).

**Comment by Keats** [comment]
You would need to run both zola on the last commit that worked on both to compare but I think @mwcz uses many of the new features of the next branch

**Comment by Stanko** [comment]
On my Mac (M1 Pro) it is about the same (I've run multiple tests). Version 0.16.0 is installed using brew, and I just downloaded 0.15.3 from github releases.

### zola 0.16.0
```
Building site...
Checking all internal links with anchors.
> Successfully checked 13 internal link(s) with anchors.
-> Creating 154 pages (0 orphan) and 3 sections
Done in 759ms.
```

### zola 0.15.3
```
Building site...
Checking all internal links with anchors.
> Successfully checked 13 internal link(s) with anchors.
-> Creating 154 pages (0 orphan) and 3 sections
Done in 834ms.
```
<img width="982" alt="Screen Shot 2022-07-18 at 11 16 09 AM" src="https://user-images.githubusercontent.com/776788/179481095-0c6e67a9-5f62-44de-b349-c09b0661340e.png">
