### ISSUE TITLE
Use entire heading as anchor link

### ISSUE THREAD

**Issue by alice-i-cecile** [Keats/gutenberg#1903]
When [enabling anchor links](https://www.getzola.org/documentation/content/linking/#anchor-insertion), I want to turn the entire heading into a link, rather than having a seperate clickable element.

This is related to but distinct from #795; simply removing the body of the link means there's nothing to click on.

**Comment by jcarvajal-dev** [comment]
[Relevant forum post](https://zola.discourse.group/t/render-headings-as-anchors/1116) 😄

**Comment by alice-i-cecile** [comment]
😆 Consider this a +1 from me then!

**Comment by Keats** [comment]
What would it look like in practice?
Something like `insert_anchor_links = "title"`? What does the anchor template does then?

**Comment by alice-i-cecile** [comment]
> Something like insert_anchor_links = "title"

This would work great for me. `left` | `right` | `none` | `title` would be quite natural and easy to explain.

> What does the anchor template does then?

I would personally be fine with this having no effect; if I want to further style the links I can just add a style to the header.

**Comment by Keats** [comment]
One thing I realised while starting to implement this: headings can already be link so that option might be incompatible in some cases without any way to turn it off. Not a blocker imo but that's annoying.

**Comment by Keats** [comment]
Implemented in https://github.com/getzola/zola/pull/1916
It still uses the anchor template in the end so you can customise what the tag looks like/change the language for the aria tag etcd.
Let me know if that works for you, and happy to rename things if they are not clear

As an aside, can you compare the speed of that PR for a build of your site vs 0.15? There is a perf regression (https://github.com/getzola/zola/issues/1902) but I can only reproduce it for a single site :/

**Comment by alice-i-cecile** [comment]
I've left my review comments there :) Looks great. I'll see if I can get to testing the before / after for the build times over the next couple days.
