### ISSUE TITLE
`resize_image` doesn't work with WebP images

### ISSUE THREAD

**Issue by bemyak** [Keats/gutenberg#1904]
# Bug Report

## Environment

Zola version: `0.15.3`

## Expected Behavior

`resize_image` function is able to process WebP input images

## Current Behavior

When trying to supply a WebP image to `resize_image` function I get this error:

```bash
$ zola build
Building site...
Failed to build the site
Error: Failed to render content of <path>/content/post.md
Reason: Failed to render img shortcode
Reason: Failed to render 'shortcodes/img.html'
Reason: Function call 'resize_image' failed
Reason: `resize_image`: Failed to read image: <path>/content/zola.webp
```

## Step to reproduce

Try to build the [attached website](https://github.com/getzola/zola/files/8943469/zola-webp-bug.zip). Then replace `zola.webp` to `zola.png` and observe the expected behavior.

**Comment by Keats** [comment]
Hmm it works for me?

**Comment by bemyak** [comment]
I messed something up a bit when I was testing this. The issue **doesn't** occur on the `next` version, only on `0.15.3` (haven't tried earlier versions).

Guess it can be closed then.
