### ISSUE TITLE
Page translation path contains base_url

### ISSUE THREAD

**Issue by timharek** [Keats/gutenberg#1907]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior
Querying `{{ page.translations[0].path }}` should return path without its whole `pwd`. 

## Current Behavior
Querying `{{ page.translations[0].path }}` returns its whole `pwd`. 

## Step to reproduce
1. Have a site with multiple languages.
2. Output `{{ page.translations[0].path }}` in one template that has a translated page.

## Comment

Is this its expected behavior? I cannot recall seeing this anywhere else where the variable `path` is being used. Also the documentation says
```
// The path to the markdown file; useful for retrieving the full page through
// the `get_page` function.
```

Isn't is sufficient to leave out `/home/<username>/<path-to-project>/content/...`? 😅

**Comment by Keats** [comment]
That's the expected behaviour yes, we use the full file path as index. We could use the relative one instead - just no particular reason it's using the full path.

**Comment by timharek** [comment]
Alright, because the absolute/full path doesn't work with `get_url()`. I don't get any errors, but it gives me the `base_url` two times in a row for some reason.

So a relative path would probably work better since that's what all other `path`'s use, correct?

**Comment by Keats** [comment]
`get_url` is more for static assets. Full path should work with `get_page`/`get_section`.

**Comment by timharek** [comment]
Oh, I thought it was also usable for checking link integrity in templates (I just tested and that did not work 😅). Would that be a feature to consider?

**Comment by Keats** [comment]
To link to content with `get_url`, you need to use the form `get_url(path="@/my/file.md")` so it understands you want the output URL. In practice, if the path is in the translations it means the file exists/URL is fine. You do get the permalink from the translations though so you can do `{{ page.translations[0].permalink }}`

**Comment by timharek** [comment]
Yes, that works! 😊 I've been using that, but when I going around my links I noticed that it outputs an absolute link instead of a relative link. But as you said, it's expected behavior. I guess we could close the issue, thanks for the replies and explaination - really appreciate it!
