### ISSUE TITLE
[Feature Request] Use `load_data()` with body variable in a shortcode

### ISSUE THREAD

**Issue by neagle** [Keats/gutenberg#1909]
I am trying to use a shortcode to parse some `toml` and output it in my `.md` file. I can accomplish this by having a separate `.toml` file and parsing it with `load_data(path=...)`.

My shortcode file (`configItems.md`):
```html
<div class="configuration-lists">
{% set data = load_data(path=path) %}
{% for c in data.config_item %}
  ...
{% endfor %}
</div>
```

My page:
```html
{{ configItems(path="data/some-file.toml") }}
```

However, I'd _like_ to be able to have that `toml` content just in the page itself, as the shortcode's body.
```html
{% configItems() %}
  [some_stuff]

  [[ config_item ]]
  env_var = "host"
  default = false
  description = "..."
  type = "String"
{% end %}
```

And then use the `body` as the data. But it doesn't look like it's possible, at present, to use `load_data` with anything but an external file. Is there a way I'm missing to use `load_data` or another mechanism to parse string content like this into data?

**Comment by Keats** [comment]
It's already implemented in the `next` branch if you want to try it: `{% set data = load_data(literal=body, format="toml") %}` should work like you expect

**Comment by neagle** [comment]
That will be perfect. Thanks: looking forward to that release! 🥂
