### ISSUE TITLE
[Feature] Gemini support

### ISSUE THREAD

**Issue by Arteneko** [Keats/gutenberg#1910]
I have some websites with a mix of markdown and gemini documents.

If I were to implement gemini support into a fork of zola, would you be up to merge it and maintain it ?

The format is pretty simple [as documented in the protocol specification section 4](https://gemini.circumlunar.space/docs/specification.gmi), and can be implemented with 2 regexes and a few substring lookups, as I did [on a small rust project I made to parse gemini](https://git.aphrodite.dev/ArtemisNeko/gemrs/src/branch/main/src/main.rs).

**Comment by Keats** [comment]
No, Gemini won't be supported in Zola.

**Comment by Arteneko** [comment]
Thanks for the fast answer. I'll work on my side to have something more tailored to my needs, then.
