### ISSUE TITLE
Failure to compile SASS

### ISSUE THREAD

**Issue by aleksanderkrauze** [Keats/gutenberg#1915]
# Bug Report

Zola seems to have a problem with compiling SASS. More specifically it can't refer to variable defined in another SASS module.
When I try to do that I get the following error message and building of the site fails:

```
Error: Error: Invalid CSS after "...r: gruvbox-dark": expected expression (e.g. 1px, bold), was ".$background;"
        on line 3:33 of sass/style.scss
>> $background-colour: gruvbox-dark.$background;

   --------------------------------^
```

Zola version: 0.15.3

## Step to reproduce

Here is my code.

File `sass/_gruvbox-dark.scss`:
```
$background: #282828;
```

File `sass/style.scss`:
```
@use 'gruvbox-dark';

$background-colour: gruvbox-dark.$background;

body {
	background-color: $background-colour;
}
```

**Comment by aleksanderkrauze** [comment]
Bonus bug. In the error message phrase `Error:` occurs two times, which is definitely not intended.

**Comment by Keats** [comment]
Zola is using Libsass which does not support that feature.

I'm planning to switch to another Sass implementation (https://github.com/getzola/zola/issues/1535) when they are ready - it might be for 0.17 I'm not sure yet I haven't tried them.

**Comment by Keats** [comment]
Closing as it will be handed by the issue mentioned above and no actionable thing to do right now for Zola.
