### ISSUE TITLE
Update Rust Crate

### ISSUE THREAD

**Issue by bkmgit** [Keats/gutenberg#1919]
# Bug Report

The Rust crate available at https://crates.io/crates/zola/0.1.1 is outdated

## Environment

Zola version: 0.1.1

## Expected Behavior
Update the crate, perhaps using a [GitHub action](https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1)

## Current Behavior
Not applicable

## Step to reproduce
Not applicable

**Comment by Keats** [comment]
I'm not going to upload it to crates.io unless there's a way to group workspace dependencies into a single crate transparently.

**Comment by bkmgit** [comment]
Ok.

**Comment by c-git** [comment]
@Keats sorry to bother you, could you explain what you mean? I'm curious what is happening and what you think should be happening

**Comment by Keats** [comment]
Zola is divided in sub crates (https://github.com/getzola/zola/tree/master/components) to make it easier to test/faster to compile. To publish to crates.io atm, I would need to publish all those irrelevant crates that are inter-dependent and have no use outside of Zola. There has been some proposals to consider those internal crates as implementation details and allow pushing a single crate to crates.io but not implemented so far.

**Comment by c-git** [comment]
Thank you for taking the time to explain (Interestingly enough this morning I was reading about workspaces in rust)

**Comment by damccull** [comment]
I know this is old, but is it possible to set up the single zola crate such that its dependencies are pointing at git repos, and therefore only need to publish the one zola crate? I guess that'd probably make it more difficult to maintain though, so maybe not worth it.

> Zola is divided in sub crates (https://github.com/getzola/zola/tree/master/components) to make it easier to test/faster to compile. To publish to crates.io atm, I would need to publish all those irrelevant crates that are inter-dependent and have no use outside of Zola. There has been some proposals to consider those internal crates as implementation details and allow pushing a single crate to crates.io but not implemented so far.
