### ISSUE TITLE
support for fenced code attributes

### ISSUE THREAD

**Issue by ayushnix** [Keats/gutenberg#1921]
Hi! Thanks for creating Zola.

I want to use [entangled](https://github.com/entangled/entangled#syntax-markdown-side) for literate programming in markdown. This feature is also mentioned in [pandoc's manual](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes). However, it seems that writing fenced code attributes doesn't work with zola and everything written after the three backtics is translated as `<pre class="language-{.lua file=init.lua}"><code>....`.

It would be awesome if fenced code attributes are supported so that I can write my documentation and publish it using zola.

**Comment by Keats** [comment]
That can't be supported, Zola already overrides fenced code attributes  for its own usage.

**Comment by ayushnix** [comment]
I understand.
