### ISSUE TITLE
Can't build a simple website using a theme

### ISSUE THREAD

**Issue by wmstack** [Keats/gutenberg#1927]
# Documentation issue
I want to make a simple markdown viewer. I downloaded `zola` via scoop. I ran `zola init` to make a website with the default settings.
I then saw that I needed either a template or a theme from the front page. I then went ahead, followed the documentation, and installed `after-dark` in the `themes` directory, being careful to write it in the `config.toml`. And I still got an error.
```
-> Config changed. The browser needs to be refreshed to make the changes visible.
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 0 pages (0 orphan) and 0 sections
Failed to build the site
Error: Failed to render section '...\zola-test\content\_index.md'
Reason: Failed to render 'index.html'
Reason: Variable `paginator.pages` not found in context while rendering 'index.html'
```

Now It doesn't matter why it failed. I encountered no error when setting the most simple mdbook, so I assume it is just inacceptable to get an error message when you followed the documentation loyally. That is one of the things that makes me give up on trying new projects: lack of documentation and unsightly error messages. On going to the server, it doesn't even seem to have noticed that I have set up a theme.

## Summary
The documentation is unclear; the program needs to get a bit of extra context. It needs to understand that you have installed a theme, not just tell you that you need to either get a template or install a theme, even after you have already installed one. That is very odd indeed. I don't know how to get the theme working after installing it.

## Proposed solution
Elaborate on the documentation on what needs to happen *after* installing a theme, just after installing a project. Also, give a more useful error message in the console for why `serve` is not working correctly after installing a theme.

**Comment by Keats** [comment]
>  so I assume it is just inacceptable to get an error message when you followed the documentation loyally. 

Have you done the part mentioned in the README of  https://github.com/getzola/after-dark 

> This theme requires your index section (content/_index.md) to be paginated to work:
> paginate_by = 5
?

The error message indicates that the index is not paginated.

> Elaborate on the documentation on what needs to happen after installing a theme, just after installing a project

That's up to the theme to do that, zola has no way of knowning what's needed.

**Comment by wmstack** [comment]
Not till now. I put the `paginate_by = 5` in the `config.toml` and it still gives the same error message.

Edit: after I add a `content/blog/_index.md`, with everything, it says this:
```
Error: Couldn't find front matter in `.../content/blog\_index.md`. Did you forget to add `+++` or `---`?
```

I do have a front matter with a `+++` and a `---`, I don't know what is going on. Also it is weird that the slashes are not consistent. I also put the `paginate_by` in the front matter of the `_index.md` and it isn't working either.

Edit: Apparently I had `+++` for the beginning of the front-matter and `---` for the end, and it couldn't interpret it. I made them the same, and then I get this error message:
```
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 1 pages (0 orphan) and 1 sections
Error: Failed to render section '...\content\_index.md'
Reason: Failed to render 'index.html'
Reason: Variable `paginator.pages` not found in context while rendering 'index.html'
```

I didn't think I would need *both* a template `index.html` *and* a theme. What is going on? Do I need to have both?

**Comment by c-git** [comment]
Is the site posted somewhere that I could see what is happening?

However IMO the documentation is great. I've followed the documentation and got up and running without issue. If you follow the instructions in the [overview](https://www.getzola.org/documentation/getting-started/overview/) then you don't need a theme.

**Comment by wmstack** [comment]
Thanks for your help! Cheers.
