### ISSUE TITLE
Extending Zola Text processing to create Custom HTML output

### ISSUE THREAD

**Issue by jbcurtin** [Keats/gutenberg#1937]
Hi, 

  After a quick search, I wasn't able to find any language on outputting custom HTML from the markdown parser. I'd like to start of by saying the Zola product is very well done and I'm extremely happy with all the features the engine provides.

  I'm interested in creating a text-element that can be recognized and an image will be rendered in its place. Is something like this possible with the Zola product?

**Comment by Keats** [comment]
You might be able to do it with shortcodes? Hard to say.

**Comment by jbcurtin** [comment]
shortcodes seems to bee what I need, thank you for the point!
