### ISSUE TITLE
Zola Shortcodes don't support markdown

### ISSUE THREAD

**Issue by jbcurtin** [Keats/gutenberg#1938]
# Bug Report

## Environment

Zola version: 0.15.3

## Expected Behavior
Unable to put links into a shortcode snippet using markdown link syntax.

## Current Behavior
The contents of the shortcode is rendered as is, without any html.

## Step to reproduce
* Create a shortcode with body
* Add contents, including [link to something](google.com)
* Render the page using zola

### Example
<img width="655" alt="Screen Shot 2022-07-23 at 3 44 27 PM" src="https://user-images.githubusercontent.com/45219/180593863-63fa8c84-f757-4c0b-b03a-10c78ff401a5.png">
e page

**Comment by Keats** [comment]
It's lacking context but shortcodes as in with .html extension will render HTML. If you want to render Markdown, use .md shortcodes: https://www.getzola.org/documentation/content/shortcodes/

**Comment by MaxIhlenfeldt** [comment]
What about reference-style links? e.g. something like this:

```
{% foo() %}
    [Text][link]
{% end %}

[link]: https://example.com
```

This currently doesn't seem to work.

**Comment by Keats** [comment]
No, shortcodes are isolated from the main markdown content.

**Comment by MaxIhlenfeldt** [comment]
I suppose that is by design and something like that will never work?

**Comment by Keats** [comment]
Is your example using a .md shortcode? Looking back at it it should probably work in my mind?

**Comment by MaxIhlenfeldt** [comment]
I first had an HTML shortcode that used the `markdown` filter, because I didn't know .md shortcodes were possible, but I also can't get it to work with a .md shortcode.

**Comment by Keats** [comment]
Hm I would expect the .md shortcodes to work, can you open an issue?

**Comment by MaxIhlenfeldt** [comment]
@Keats sorry, this got buried in my inbox for way too long... finally opened https://github.com/getzola/zola/issues/2710.
