### ISSUE TITLE
Built-in shortcodes don't work in markdown

### ISSUE THREAD

**Issue by Bytekeeper** [Keats/gutenberg#1944]
# Bug Report

## Environment

Zola version: 
```
zola --version
zola 0.16.0
```

## Expected Behavior
A call to `resize_image`.

## Current Behavior
```
Error: Reason: Found usage of a shortcode named `resize_image` but we do not know about. Make sure it's not a typo and that a field name `resize_image.{html,md} exists in the `templates/shortcodes` directory.
```

## Step to reproduce
Use `{{ resize_image(...) }}` in a markdown file:
```
zola init demo
echo +++\n+++\n'{{ resize_image(path="file.png", width=100, height=100, op="scale") }}' > content/
_index.md
zola check
```

**Comment by Keats** [comment]
Using it like that would be calling a shortcode, not the Tera function.
Have a look at https://www.getzola.org/documentation/content/shortcodes/ to see how to write a shortcode and then you can just use `resize_image` in it, like the Zola docs do: https://github.com/getzola/zola/blob/master/docs/templates/shortcodes/resize_image.html

In that case the shortcode is also called resize_image but it doesn't need to.

**Comment by Bytekeeper** [comment]
Ok thanks, I guess I misunderstood https://www.getzola.org/documentation/content/image-processing/#using-resize-image-in-markdown-via-shortcodes - it gave the impression of working in markdown as well without adding a custom shortcode.
