### ISSUE TITLE
Inconsistent shortcode rendering

### ISSUE THREAD

**Issue by bemyak** [Keats/gutenberg#1947]
# Bug Report

## Environment

Zola version: `0.16.0`, `next`
OS: Linux

## Expected Behavior
Shortcodes should render the same way each invocation

## Current Behavior
The `youtube` shortcode in the attached website produces different results from build to build. Sometimes it renders correctly into:
```html
<figure class="image is-16by9">
    <iframe class="has-ratio" frameborder="0" allowfullscreen width="100%"
        src="https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ"></iframe>
</figure>

<div class="comment">
    <em><p>test</p>
</em>
</div>
```

Sometimes it's just
```html
<div >
    <iframe src="https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>
```

## Step to reproduce
Unzip the [archive](https://github.com/getzola/zola/files/9229055/bug-inconsistent-shortcodes.zip), and run `zola build && cat public/post/index.html` around 5-10 times. Observe that the output is slightly different.

**Comment by bemyak** [comment]
@Keats, any tips here? I'm not sure how to debug this, it looks like a concurrency issue :shrug:

**Comment by Keats** [comment]
Looks like it's somehow conflicting with the built-in youtube shortcode and rendering that one instead, which is weird as it should have been replaced by the custom one.
