### ISSUE TITLE
Footer navigation links to previous and next posts not showing up

### ISSUE THREAD

**Issue by learnbyexample** [Keats/gutenberg#1951]
# Bug Report

## Environment

Zola version: 0.16.0 (Linux, binary used from `zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz`)

## Expected Behavior

Footer should have links to previous/next posts.

## Current Behavior

Footer doesn't show links to previous/next posts. This issue isn't seen in versions `v0.15.3` and below.

## Step to reproduce

Failing case:

```bash
$ git clone https://github.com/getzola/even.git
$ cd even/
$ zola --version
zola 0.16.0
$ zola serve
```

As an example, screenshot for "Tenth post" is shown below (footer has only the tags, no navigation links to previous/next posts):

![image](https://user-images.githubusercontent.com/17766317/182363161-8f141fad-ef6d-4e69-b7b9-2008cfe8d662.png)

Passing case:

```bash
$ zola --version
zola 0.15.0
$ zola serve
```

Screenshot (footer has expected navigation links):

![image](https://user-images.githubusercontent.com/17766317/182363360-9997d6b3-bba7-4baa-9352-4bcd9a73fa95.png)

**Comment by Keats** [comment]
That should be moved to the even theme, can you open it there? There was a change for the prev/next in 0.16 which means I need to update those themes.

**Comment by learnbyexample** [comment]
Oh ok, didn't realize it was theme issue. Opened an issue there now.
