### ISSUE TITLE
Allow to load_data from yml in addition to yaml?

### ISSUE THREAD

**Issue by bast** [Keats/gutenberg#1958]
This is not a bug report but rather a change proposal which I could possibly code/send.

Zola allows to `load_data` from yaml files (in addition to other formats) and this is a really nice recent addition (thanks!):
https://www.getzola.org/documentation/templates/overview/#load-data

But many YAML files end with `*.yml` and not `*.yaml` and Zola does not seem to recognize these as YAML files.

Would it make sense to `load_data` from files/URLs ending with either `*.yaml` or `*.yml` via the YAML parser? If yes, I could try to send a patch.

But maybe this already works and I just misunderstood the documentation and/or sources and/or my local testing of a page.

**Comment by Keats** [comment]
That's a very simple patch, no issues doing a PR for it.
