### ISSUE TITLE
Fixing anchor links checks and generation

### ISSUE THREAD

**Issue by hamidrezakp** [Keats/gutenberg#1960]
# Bug Report
I had a problem with `zola check` that it complains about internal links and anchors not existing.
After some research and test, i have found the problem.

Zola will do a slugification on anchors and links, so for non ASCII characters (ex. in Persian) we write some heading like this:
```
# تست
```
and the zola will make this slug: #test
thus we have to slugify the heading manually to get over the checks and this is annoying.

## Environment

Zola version: 0.15.3

## Expected Behavior
when checking or generating slugs, slugify the references to headings and other internal links.

## Current Behavior
Error on `zola check`
```
Checking site...
Checking all internal links with anchors.
> Checked 262 internal link(s) with anchors: 1 target(s) missing.
Failed to check the site
Error: 
The anchor in the link `@/edition-2/posts/12-async-await/index.fa.md#معایب` in /home/hamid/dev/rust/websites/blog_os/blog/content/edition-2/posts/12-async-await/index.fa.md does not exist.
```

## Step to reproduce
write following post text:
```
# پارسی
the heading is [this](#پارسی)
```

**Comment by Keats** [comment]
> Zola will do a slugification on anchors and links

That depends on your configuration, see the slugify portion of https://www.getzola.org/documentation/getting-started/configuration/ and https://www.getzola.org/documentation/getting-started/configuration/#slugification-strategies

**Comment by hamidrezakp** [comment]
> > Zola will do a slugification on anchors and links
> 
> That depends on your configuration, see the slugify portion of https://www.getzola.org/documentation/getting-started/configuration/ and https://www.getzola.org/documentation/getting-started/configuration/#slugification-strategies

Yes, i have read that section.
I want to use slugification, it's a nice-to-have thing, the problem is that zola should slugify all references and then check them (CMIIW).

**Comment by Keats** [comment]
This is the expected behaviour if you're slugifying though, you have to link to the slug

**Comment by hamidrezakp** [comment]
Exactly.
The problem is with languages that do not use Latin character set, the slug is somehow unexpected or some extra step to manually do.

For English, it's easy, `Some Thing` would be `some-thing`, we can predict it, or it is easy to just write it in this format.
but for Persian, `یک چیز تستی‍‍` can not be easily determined, because of conversion between Persian characters to Latin characters.
it can be `yek-chize-testi`  or `yk-chze-teste` or any other possible form of it. ( humans have hard time to guess this conversion. i know the slug library is doing the mapping and it is always 1-to-1 mapping).

i propose we add a pre-compile step for md to slugify the references  so we can use this in templates:
```md
# What if 1 < 3 ?
# تست و تست

link to first heading is [this](#"What if 1 < 3 ?")) 
link to second heading is [this](#"تست و تست")
```
(I know this syntax is horrible, it is just for the example)

**Comment by hamidrezakp** [comment]
Maybe adding a pre-build hook can help here.
Or we must use some other build tool to convert references before calling `zola build`

**Comment by c-git** [comment]
Some IDE's also provide support for giving you the slug in auto completion like PyCharm but I've never tried it with Persian.

**Comment by Keats** [comment]
You can always specify the slug of the headers manually so you don't have to guess.

**Comment by hamidrezakp** [comment]
>  Some IDE's also provide support for giving you the slug in auto completion like PyCharm but I've never tried it with Persian.

hmm, this is good, but will not solve the problem, but thanks for mentioning.

**Comment by hamidrezakp** [comment]
> You can always specify the slug of the headers manually so you don't have to guess.

We are currently doing this method, i just wanted to to remove this manually specifying slugs

**Comment by Keats** [comment]
FYI just using the title will not work in practice. How would you link to the second header in the following snippet:

```md
## Test

## test

##     TEST   
```
?
The reason we use slugs for linking is that they are unique

**Comment by hamidrezakp** [comment]
Hmm, you are right. i'm convinced that my solution is actually not a solution.
What if we have this feature only for non-unique links? (we can always report ambiguous usage of this auto translate to slug).
Therefore users can manually set `{#link}` for this cases.

This can be an optional feature that can be enabled per-post.

**Comment by Keats** [comment]
I don't think this is worth adding as an option.
