### ISSUE TITLE
External links that do not follow the post `http(s)://` scheme

### ISSUE THREAD

**Issue by JoelMon** [Keats/gutenberg#1967]
Hello everyone,

Are Markdown links that start with `www.` legal? If so, I propose allowing links beginning with `www.` also.

## Code Snippet

https://github.com/getzola/zola/blob/195b6bdff070913129f310f4fe68b42b5c8ba0a6/components/markdown/src/markdown.rs#L133-L136

## Test

https://github.com/getzola/zola/blob/195b6bdff070913129f310f4fe68b42b5c8ba0a6/components/markdown/src/markdown.rs#L597-L609

**Comment by Keats** [comment]
It's probably fine?

**Comment by pqcfox** [comment]
Would love to give this a shot if it'd still be helpful!

**Comment by Keats** [comment]
Go for it

**Comment by Keats** [comment]
Turns out it probably shouldn't be added: https://github.com/getzola/zola/pull/2100#issuecomment-1449415039
