### ISSUE TITLE
Cannot get values for keys if the key contains a period.

### ISSUE THREAD

**Issue by Ssloto** [Keats/gutenberg#1988]
# Bug Report

I'm not sure if this belongs here, or over with Tera, but this is basically an issue with accessing key value pairs in blob's/objects where the key contains a period.

Basically, I wanted to store some extra metadata to go with particular members of a taxonomy, and for my purposes, I'm more than happy to do that in an external json file, which I load with a call to the built-in `get_data()` method.

One of my keys happens to be the name of a provincial park in Canada. More specifically, its name is "Mt. Robson Provincial Park."

Right now, the `single.html ` page for the taxonomy contains the following blocks:

```
{% set tag_info = load_data(path="/data/tag_info.json") %}
{% if term.name in tag_info %}
<span class="tag_info">
	{{tag_info[term.name]['description']  | linebreaksbr | safe}}
</span>
<br>
<br>
{% endif %}
```

In tag_info.json, I've added a block as such:

```
  "Mt. Robson Provincial Park": {
    "description": "blah blah blah blah blah blah."
  },
```

What happens is that the first call, to check if term.name is in tag_info (where term.name == "Mt. Robson Provincial Park") succeeds. 

However, we are unable to access "description." Instead, we get the following error:

```
Error: Failed to serve the site
Error: Failed to render single term tags page.
Error: Reason: Failed to render 'tags/single.html'
Error: Reason: Variable `tag_info[term.name]['description']` not found in context while rendering 'tags/single.html': the evaluated version was `tag_info.Mt. Robson Provincial Park."description"`. Maybe the index is out of bounds?
```

Note that this works perfectly fine for tag names that do not contain periods.

## Environment

Zola version: 14.1, but reproduced in 16.1

## Expected Behavior
Should be able to return the description string from the obj

## Current Behavior
```
Error: Failed to serve the site
Error: Failed to render single term tags page.
Error: Reason: Failed to render 'tags/single.html'
Error: Reason: Variable `tag_info[term.name]['description']` not found in context while rendering 'tags/single.html': the evaluated version was `tag_info.Mt. Robson Provincial Park."description"`. Maybe the index is out of bounds?
```

## Step to reproduce
Load data & try accessing a key-value pair with a "." in the key, or alternatively, just do what I've done above.

**Comment by Ssloto** [comment]
Turns out I already have a workaround for this that I was using elsewhere in my site. 

Unlike the code block above, this one works:

```
{% if tag_info is containing(tag) %}
    {% set this_tag_info = tag_info | get(key=tag) %}
    <div class="post__taginfo">
        <div class="post__taginfo__title"><h3>{{title}}</h3></div>
        <span class="tag_info">
            {{this_tag_info["description"]  | linebreaksbr | safe }}
        </span>
{% endif %}
```

**Comment by Keats** [comment]
That's a Tera bug that needs to be fixed!

**Comment by Keats** [comment]
Ok, it should be fixed in the `next` branch.
