### ISSUE TITLE
Permit secondary sort

### ISSUE THREAD

**Issue by jhpratt** [Keats/gutenberg#1992]
Zola version: 0.16.1

Would it be possible to accept an array of values for sorting a section? I would like to sort by date first, but if I have more than one item with the same date I want to sort it manually by using weight. As far as I can tell this is not currently possible.

**Comment by Keats** [comment]
Very unlikely to be added. 

>  if I have more than one item with the same date I want to sort it manually by using weight

You can use a full datetime, you can make it work by having the same date but different hours/mins/secs.

**Comment by jhpratt** [comment]
Neat; I didn't even consider that times might be accepted as well. That solves my use case. Closing as such.
