### ISSUE TITLE
Invalid HTML link generation with zola >0.15

### ISSUE THREAD

**Issue by mikhailantoshkin** [Keats/gutenberg#1993]
# Bug Report

## Environment

Zola version: 0.15.1, 0.16.1 (and possible version between those two) on WSL

## Expected Behavior
Linking colocated files in markdown produces valid links in HTML

## Current Behavior
When using colocation for files and linking them in markdown, generated html `<a>` tag does not contain valid links
Directory structure is like this:
```
.
└── content
    └── test
        ├── qwe.js
        └── test.md
```
contents of `test.md`:
```
+++
title="Test"
template="test-page.html"
+++

[link](qwe.js)
```

## Step to reproduce
I've created [repo](https://github.com/mikhailantoshkin/zola-test) with basic project structure to reproduce the issue. Running `zola build` with 0.14.1 produces html with valid links, in this case `<a href="https://testblog.com/test/qwe.js">link</a>`. But running `build` command with 0.15.1 and 0.16.1 produces invalid link `<a href="qwe.js">link</a>`

**Comment by Keats** [comment]
Can you test with the `next` branch?
