### ISSUE TITLE
No option to disable port appending when developing site on environment with a reverse proxy

### ISSUE THREAD

**Issue by ProximaB** [Keats/gutenberg#2002]
# Bug Report
When using cloud development environment like gitpod.io, it allows exposing your ports via public links, behind the scene it uses a reverse proxy, that translate e.g. localhost:1234 into 1234-devenv.gitpod.io. That causes a problem because zola generated URLs that have port appended to it `1234-devenv.gitpod.io:1234/...`, that of course makes the address invalid in that scenario. The resolution would be an ability to disable that behave with a flag on a serve command `--appendPort=false`.  Hugo also support that option [gohugoio/.../server.go](https://github.com/gohugoio/hugo/blob/a066e98851dfbd78c17c98f0878c2e8b84a10f50/commands/server.go#L713) 

## Environment

Zola version: 0.16.1

## Expected Behavior
Do not append port to urls when requested.
Expected script to run on gitpod `zola serve -p 1313 -i 0.0.0.0 -u $(gp url 1313) --appendPort false`

## Current Behavior
Appending ports behind gitpod reverse proxy makes URL invalid.

## Step to reproduce
Open new workspace on gitpod.io (it's free), install zola with brew, init new zola project, `zola serve -p 1313 -i 0.0.0.0 -u $(gp url 1313) --appendPort false`

**Comment by ffrizzo** [comment]
https://github.com/getzola/zola/pull/2003

**Comment by Keats** [comment]
If the option is only ever used for the negation, it makes more sense to have `zola serve --no-port-appending` instead (or whatever name is better)

**Comment by ProximaB** [comment]
That’s true, but setting the parameter should be possible also through configuration.
Adding property to yaml appendPort: false seems to be follow current convention of sharing same names. But indeed it looks better for cli use

**Comment by Keats** [comment]
> but setting the parameter should be possible also through configuration.

It's not the case in zola. An option only for use in `zola serve` will not be available from the config file.

**Comment by ProximaB** [comment]
I agree with you, it’s not the case with Zola. it’s has much more sense to use no-port-appending than appendPort with default true.

**Comment by ffrizzo** [comment]
Interesting discussion. So we can tell the best option is to use `--no-port-append`?

**Comment by ProximaB** [comment]
Yes, I think we have reached a consensus --no-port-append. Now It depends if it's ok with you and other contributors.

**Comment by ffrizzo** [comment]
Sounds good to me. I will make propper changes on my PR
