### ISSUE TITLE
Minifier inserts extra div

### ISSUE THREAD

**Issue by famfo** [Keats/gutenberg#2004]
# Bug Report

## Environment
Zola version: 0.16.1

## Expected Behavior
The minifier minifies the HTML and the page still looks the same as unminified. 

## Current Behavior
The minifier inserts an extra `div` when any non-HTML tag with `<>` is present in the markdown file. This breaks things, for example grid boxes:
Without minifying the HTML:
![image](https://user-images.githubusercontent.com/44938471/195845859-cdcd134b-3237-4659-af00-9147f15a48de.png)
With minifying the HTML:
![image](https://user-images.githubusercontent.com/44938471/195845891-22b56a93-462c-4e44-8568-6b8049560a3d.png)

## Step to reproduce
I wrote a small [example](https://git.lemonsh.moe/famfo/minify-div) to showcase the issue.

**Comment by Keats** [comment]
Can you reproduce the issue with https://github.com/wilsonzlin/minify-html directly?

**Comment by famfo** [comment]
Yes I can, it produces the same undesired result.

**Comment by Keats** [comment]
Can you create an issue with the testcases there then? I'll update Zola once this is fixed (if needed).

**Comment by famfo** [comment]
Alright, will do that.

**Comment by Keats** [comment]
Closing as it's not related to Zola directly.
