### ISSUE TITLE
Underscores in LaTeX expressions parsed incorrectly

### ISSUE THREAD

**Issue by thomasantony** [Keats/gutenberg#2019]
# Bug Report

## Environment

Zola version: 0.16.1

## Expected Behavior

When I have certain latex strings embedded in markdown text with underscores in them, such as:

```
This is a text string with some latex in it: $\vec{\xi}_\alpha$ and $\dot{\vec{x}}_\alpha$
```

I expect the text within the dollar signs to be left untouched for the latex renderer to pick up. 

```html

<p>This is a text string with some latex in it: $\vec{\xi}_\alpha$ and $\dot{\vec{x}}_\alpha$</p>

```

## Current Behavior

But in this particular instance, the markdown renderer inserts `<em>` tags within the Latex expression and prevents it from rendering correctly. The above example appears in the HTML as:

```
<p>This is a text string with some latex in it: $\vec{\xi}<em>\alpha$ and $\dot{\vec{x}}</em>\alpha$</p>
```

## Step to reproduce

Render the following page in a page that supports Latex in some form (MathJax or KaTeX)

```markdown
+++
title = "Markdown latex test page"

[extra]
latex = true
+++

An underscore in a latex string works fine in this example: $m_\alpha$

It also works fine in this example: $m_\alpha$ and $\vec{\xi}_\alpha$

But it breaks here:  $\vec{\xi}_\alpha$ and $\dot{\vec{x}}_\alpha$ 
```

You can also seen an example here: https://thomasantony.com/testpage

**Comment by Keats** [comment]
CommonMark doesn't have support for latex so that's to be expected. If you want to use Latex in Zola, put it in a shortcode
