### ISSUE TITLE
Markdown `---` renders as `<hr />`

### ISSUE THREAD

**Issue by alexrutar** [Keats/gutenberg#2020]
# Bug Report

## Environment

Zola version: tested with `0.13.0` and `0.16.1`, but likely any.

## Expected Behavior
A `---` in markdown renders as `<hr />`.

## Current Behavior
The `---` element should render as `<hr>` according to the [HTML5 spec on void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements).

I don't know any Rust really so I cannot determine how the markdown is being rendered. If this is an upstream issue, let me know and I'll move this somewhere else!

## Step to reproduce
Create any markdown file with `---`: the generated HTML will contained an `<hr />` element.

**Comment by Keats** [comment]
That's the CommonMark spec: https://spec.commonmark.org/0.30/#example-43

It's not a bug, just the markdown parser (pulldown-cmark) follows the spec.

**Comment by c-git** [comment]
This is likely an upstream issue but I think what the OP was saying is that instead of getting `<hr /> ` like in the example you get `<hr>`
