### ISSUE TITLE
Build/serve fails with "Error Page ... has taxonomy `example` which is not defined in config.toml"

### ISSUE THREAD

**Issue by comatory** [Keats/gutenberg#2021]
# Bug Report

I'm getting error when running `zola serve` or `zola build`. I haven't built my site in a while but it did work on older versions

## Environment

Zola version: 0.16.1

## Expected Behavior
The site should build.

## Current Behavior

When running `zola serve` or `zola build`:

```
Building site...
Error: Failed to build the site
Error: Page `/user/www/content/site.md` has taxonomy `example` which is not defined in config.toml
```

My relevant part `config.toml` looks like this:

```
taxonomies = [
  { name = "example", feed = true }
]
```

The markdown files use something like this:

```
+++
[taxonomies]
example=["1","2"]
+++
```

## Step to reproduce

`zola build` or `zola serve`

**Comment by comatory** [comment]
I built binary myself from the source after checking out `v0.15.3` tag where I don't get the issue, compiling `v0.16.0` reproduces the issue.

I read the breaking changes in changelog and noticed this about taxonomies:

`- Now outputs empty taxonomies instead of ignoring them`

I don't understand what the problem could be though.

**Comment by Keats** [comment]
Can you create a repo with the problem?

**Comment by comatory** [comment]
Hey @Keats thanks for the response. I don't like creating repositories on my Github profile for bugs but I hope you don't mind me uploading the archived repository here as an attachment in zip file:

[zola-taxonomy-error.zip](https://github.com/getzola/zola/files/10001203/zola-taxonomy-error.zip)


I took my original repository and stripped all the information from it and removed bunch of stuff so there's less noise - I can still reproduce the error in this repository.

With zola `0.16.1` it fails with this error:

```
Error: Failed to build the site
Error: Page `/Users/[user]/zola-taxonomy-error/content/projects/example.md` has taxonomy `tech` which is not defined in config.toml
```

On version `0.15.3` it builds the site fine.

I built `zola` from sources by checking out to relevant tags and running `cargo build --release`.

**Comment by Keats** [comment]
Looks like another victim of TOML nesting, your config.toml was:

```
# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

taxonomies = [
  { name = "tech", feed = true }
]

[extra]
# Put all your custom variables here
```
which means the taxonomies is loaded as part of markdown (which Zola doesn't look for).

Changing to 
```
# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  { name = "tech", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
```

and adding the couple of missing templates work fine. Before 0.16, this page would just be ignored.

**Comment by comatory** [comment]
Yes that was the problem 👍 Thank you.
