### ISSUE TITLE
Zola builds delete public subdirectory every time

### ISSUE THREAD

**Issue by jamesmcm** [Keats/gutenberg#2025]
Hey,

For simple manual deployment to Github pages, I was using the [Octopress approach](http://octopress.org/docs/deploying/github/) of adding `/public` to my `.gitignore` file, and pushing the root git repo to the protected `source` branch on my Github Pages user repo,  and then making the public subdirectory it's own git repo and pushing that to the `master` branch so it gets served by Github Pages.

The issue is that the current automatic deletion behaviour means that the `.git` subdirectory in the `public` subdir (and thus the commit history) of the built public subdir/master branch gets deleted every time.

This isn't super critical since the commit history of the built master branch for deployment isn't so important (unless one needed to roll back without rebuilding locally), but it is a bit annoying (compared to Octopress).

Other than it works nicely though, so it'd be nice if this could be avoided (i.e. rather than deleting the whole subdirectory, just recursively delete non-hidden files?). I appreciate it's a bit of extra complication though (I think the `walkdir` crate would be the best option).

Thanks, for the great project btw, I switched [my blog](http://jamesmcm.github.io/blog/) over last week, copying most of the Octopress theming :slightly_smiling_face:

**Comment by Keats** [comment]
See https://github.com/getzola/zola/pull/1985 for someone asking the same thing.
