### ISSUE TITLE
get_url: always add trailing slash unless path has extension?

### ISSUE THREAD

**Issue by dannyvankooten** [Keats/gutenberg#2026]
I just migrated my blog from Jekyll to Zola and after it's been great once I got the hang of it! Thank you for your great work on it. 

One thing I ran into and that the docs were a tiny bit ambiguous about was the proper way to generate permalinks using the `get_url` Tera function.

The [documentation for get_url](https://www.getzola.org/documentation/templates/overview/) states:

> By default, assets will not have a trailing slash.

This + #85 gave me the impression that `get_url('/about/)` would return `https://mysite.com/about/` but it was stripping the trailing slash because I wasn't using the internal linking (`@/`) feature.

Would it make sense to always append a trailing slash for anything that looks like a URL / directory? Eg anything that does not have a file extension?

**Comment by Keats** [comment]
`get_url` has a `trailing_slash` parameter to select whether to add it or not. I'd prefer not do it automatically.

**Comment by dannyvankooten** [comment]
@Keats It's removing it automatically in this case.

**Comment by Keats** [comment]
even with `trailing_slash=true`?

**Comment by dannyvankooten** [comment]
No, then it works as expected. It's just that I thought it would be a nice improvement to not strip it automatically for something that is obviously not an asset file.

Alternatively, maybe we can update the documentation to state that anything passed into get_url (that is not an internal link starting with '@/') while the 'trailing_slash' argument is omitted will have no trailing slash.

**Comment by Keats** [comment]
We can update the documentation to remove the asset word from

> By default, assets will not have a trailing slash. You can force one by passing trailing_slash=true to the get_url function.
