### ISSUE TITLE
Closing tag for certain html tags are missing when built with minify_html

### ISSUE THREAD

**Issue by whoisYoges** [Keats/gutenberg#2036]
Closing tag for certain html tags are missing when built with `minify_html = true`

## Environment
Arch Linux 5.15.79-1-lts: zola 0.16.1

## configuration
`minify_html = true`

## step to reproduce
Runn `zola build` or `zola serve` in any zola project with the above [configuration](#configuration) enabled and check all the output pages (index.html)

## Current Behavior
The closing tags for certain html tags are missing. As I've experiencrd, `</head>`, `</body>` and `</html>` tags are missing from all the output html pages. I am unsure that these are the only missing tags cause I haven't tried all the available tags in html.

## Expected Behavior
The output html pages (index.html) should just have been minified without removal of all those closing tags.

## Reference Projects:
- <https://github.com/whoisYoges/website>
- <https://github.com/metis-os/metislinux.org>

**Comment by Keats** [comment]
I believe it's part of what https://github.com/wilsonzlin/minify-html does. It's still interpreted correctly by browsers

**Comment by whoisYoges** [comment]
Oh! I dodn't know it was actually a feature. Thanks for the link.
