### ISSUE TITLE
Can't build using cargo

### ISSUE THREAD

**Issue by eggbean** [Keats/gutenberg#2037]
I don't know why I cannot build zola?

```
$ cargo build --release
error: failed to parse manifest at `/home/jason/getzola-zola-195b6bd/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`
```
Sorry if I am making an obvious mistake here.

**Comment by magikstm** [comment]
What is your OS and what version of Rust are you using?

Did you change values in Cargo.toml?

Are your values for these identical:
```
[profile.release]
lto = true
codegen-units = 1
strip = true
```

**Comment by Keats** [comment]
It's probably due to an old/bugged version of cargo. Cargo does support boolean for `strip`: https://doc.rust-lang.org/cargo/reference/profiles.html#strip
