### ISSUE TITLE
Feature Request: maybe add option to generate uncompressed sass

### ISSUE THREAD

**Issue by dm9pZCAq** [Keats/gutenberg#2041]
# Feature Request

## Environment

Zola version: `0.16.1`

## Expected Behavior
Add some configuration option to generate uncompressed/expanded sass

## Current Behavior
Currently `zola` hardcoded to generate compressed sass
https://github.com/getzola/zola/blob/6f29740c1890af854dd68991a5854aa0e52636e2/components/site/src/sass.rs#L21

**Comment by Keats** [comment]
What's the need for that? The browser can easily can uncompress it in the dev tools

**Comment by dm9pZCAq** [comment]
to view it outside of a "modern" browser that automatically formats CSS, or even without a browser at all

**Comment by Keats** [comment]
Most text editors/IDEs will be able to reformat it out the box so I will close that issue
