### ISSUE TITLE
Root _index.[lang].md is wrongly present in .translations

### ISSUE THREAD

**Issue by biodranik** [Keats/gutenberg#2042]
# Bug Report

A translation entry is wrongly present for the root index section despite the file is not added/present yet. It is important for partial pages/site translations support.

## Environment

Zola version: 0.16.1

## Expected Behavior

There should be no translation entry for the missing page. It works correctly for other sections.

## Step to reproduce

1. Add a language into `config.toml`
2. Do NOT add content/_index.[lang].md file
3. `section.translations` contains the entry for content/_index.[lang].md despite it being absent.

**Comment by Keats** [comment]
It's the intended behaviour, index pages are created for each language automatically if missing.

**Comment by biodranik** [comment]
Interesting. What is the reasoning for this approach?

**Comment by Keats** [comment]
Just to be consistent with the fact that the default language gets automatically created if not present.
