### ISSUE TITLE
two files with different file name, still path collision

### ISSUE THREAD

**Issue by bugswriter** [Keats/gutenberg#2048]
# Bug Report

## Environment
Arch Linux
Zola version:
0.16.1

## Expected Behavior
Successful build of diary.

## Current Behavior
```
Building site...
Error: Failed to serve the site
Error: Found path collisions:
- `/diary/23-06/` from files ["/home/suraj/site/content/diary/2022-11-29-23-06.md", "/home/suraj/site/content/diary/2022-12-05-23-06.md"]
```

## Step to reproduce
Make two files name - 2022-12-05-23-06.md and 2022-11-29-23-06.md in section
and try to build

**Comment by Keats** [comment]
This is the normal behaviour. The filename starts with a date so it is removed from the path for both and you end up with 23-06 as path for both

**Comment by bugswriter** [comment]
but why date is removed? any way to fix this? can I add some string in front?
or any option

**Comment by Keats** [comment]
It's the feature mentioned in at the beginning of https://www.getzola.org/documentation/content/page/
There will be a config option in the next release to keep the date in the path, you can try the `next` branch if you want.

**Comment by Keats** [comment]
Closing as this is not a bug and it will be configurable in the next version.
