### ISSUE TITLE
Override a template block for a single page?

### ISSUE THREAD

**Issue by lukehsiao** [Keats/gutenberg#2051]
Suppose I have a templates/page.html that looks something like

```
{% extends "index.html" %}
{% block content %}
<div class="content">
    {{ page.content }}
</div>
{% endblock content %}
{% block footer %}
{% endblock footer %}
```

I would like to override the footer block for each page individually. That is, each post has a different footer.

But, I cannot do so from within the `.md` file itself, as everything there ends up in `page.content`. 

Is there any mechanism by which I could override this other block individually for a page?

**Comment by c-git** [comment]
Your template has the footer directly following the content, therefore I would use a short code to put in the content at the bottom of the page. So pass what ever you want as the footer into the shortcode and put the call to the shortcode at the end of the .md file. That way you don't need to worry about changing the template you can just use the same template and the footer will be part of the content. 

If you needed to have something in between the content and the footer I think you can put the footer into a div with a suitable class or a <footer> tag and use CSS to float it to the bottom. If that's needed let me know I think I have the CSS somewhere around I can look for it, then again I found it somewhere on the Internet originally but I remember searching for a while before I found it.

**Comment by lukehsiao** [comment]
> If you needed to have something in between the content and the footer I think you can put the footer into a div with a suitable class or a 

Yes, this was a poor example. In my case I do indeed have a bunch of other stuff between the content and the footer. If you have an example of that CSS, that would be great!

**Comment by c-git** [comment]
Found it, guess it wasn't as hard to find as I thought. Of course if you don't want to use a footer element I think it should still work.

```css
.footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    background-color: darkgrey;
    color: white;
    text-align: center;
}
```

**Comment by Keats** [comment]
To override a block, you will need to match on the path of that page in the template, no other way.
I've done a site similar where each page has some data in `[extra]` and the template display whatever was needed depending on those values

**Comment by c-git** [comment]
Yeah that makes sense as well and is more general than the footer solution. @lukehsiao if you don't quite follow create an sample repo and I should be able to do a quick example of both solutions in there for you. If you don't need it and the first one worked for you that's fine as well.

**Comment by lukehsiao** [comment]
Hmm, yeah, I don't quite follow.

I have a repo here you could fork: https://github.com/lukehsiao/zola-pickles

**Comment by c-git** [comment]
Put an example of what I understand [here](https://github.com/c-git/zola-testluke). On the Markdown page.

**Comment by lukehsiao** [comment]
Ah, I see! Thanks everyone!

I think using the page extras will work great for me. I'd consider this issue resolved :)
