### ISSUE TITLE
word_count includes alt text and other things

### ISSUE THREAD

**Issue by classabbyamp** [Keats/gutenberg#2053]
# Bug Report

## Environment

Zola version: 0.16.1

## Expected Behavior

I'm not sure if this is the intended behaviour, but I expected alt text and other things to not count.

## Current Behavior

words in image alt text and other things count towards the word count

## Step to reproduce

for this page: 

```md
+++
title = "an example post"
date = "2021-10-10"
+++

one two three

<!-- more -->

![four five six](idk.png)
```
`page.word_count` will be 11

**Comment by Keats** [comment]
Yes, it operates on the raw content. It's very rough and is mostly useful for an estimated reading time, not anything perfect.
