### ISSUE TITLE
Dead Heroku link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by elliotwutingfeng** [Keats/gutenberg#2061]
# Documentation issue

## Summary

The link https://tmtheme-editor.herokuapp.com/#!/editor/theme/Agola%20Dark in https://github.com/getzola/zola/blob/master/CONTRIBUTING.md is dead.

## Proposed solution

Re-deploy the theme gallery site (if applicable) and update the link.

**Comment by Keats** [comment]
Argh I guess this link and all others need to be removed. I'm not the maintainer and the repo itself is abandoned

**Comment by wichops** [comment]
I tried building the project myself to host it. But some dependencies are really old and had a lot of trouble building it. Although I could run it locally. 

I could upload screenshots of the themes here or host them somewhere else 🤔
