### ISSUE TITLE
I can't translate my page to Catalan

### ISSUE THREAD

**Issue by MateuSai** [Keats/gutenberg#2064]
# Bug Report

## Environment

Zola version: 0.16.1

## Expected Behavior
I want to add Catalan to my page, but it says it not supported. Why is not supported? Do you plan to add support for more languages. Is there some workaround other than putting the Catalan translations as if they were another language?

## Current Behavior
![image](https://user-images.githubusercontent.com/57108338/209987362-e35b100b-9de1-4423-ba01-263f6b956a6c.png)

## Step to reproduce
Try to add Catalan as a language

**Comment by MateuSai** [comment]
Ahh, it's only the search index, without it, it works
![image](https://user-images.githubusercontent.com/57108338/210034136-1d6faa82-c384-4e05-a8e0-c2083b77a475.png)

But, why is not supported to build a search index for Catalan?

**Comment by Keats** [comment]
> But, why is not supported to build a search index for Catalan?

We are using whatever https://github.com/mattico/elasticlunr-rs makes available. You can contribute the language part to that project and it will be available in Zola.
