### ISSUE TITLE
Image hash should include Zola version

### ISSUE THREAD

**Issue by theMarina** [Keats/gutenberg#2066]
I had Zola version v0.15.3 and updated it to v0.16.1. The old version had a bug where the processed images were black and white which was fixed with the update. However, because Zola caches the images, it did not automatically fix the cached images.

I think that the images should contain information about the Zola version that generated them so they are regenerated if there is an update.
Additionally, I do not like that the image names of the resized images are hashed and do not contain the original image name at all. I think this is bad for SEO

**Comment by Keats** [comment]
We could name them `{original_hash}.hash.{ext}`? I don't think the hash should contain the zola version though, some people have a huge amount of images and they don't want to re-process them on every Zola update. It's easy to do as an opt-in feature though, just delete the processed folder and let Zola re-do it

**Comment by Keats** [comment]
I've gone with `{file_steam}.{hash}.{ext}`
