### ISSUE TITLE
Markdown: Add terraform syntax highlighting support

### ISSUE THREAD

**Issue by jpcaruana** [Keats/gutenberg#2067]
It would be great to be able to format `.tf` code (https://www.terraform.io/)

**Comment by Aju100** [comment]
Hey Can I work on this issue @jpcaruana

**Comment by SkypLabs** [comment]
Duplicate of #1981.

**Comment by Keats** [comment]
Good catch, closing this one.

**Comment by jpcaruana** [comment]
oups sorry for the duplicate
