### ISSUE TITLE
Cannot install Zola on Fedora 37 using dnf

### ISSUE THREAD

**Issue by linhns** [Keats/gutenberg#2078]
# Installation on Fedora 37

## Summary
I followed instructions on https://www.getzola.org/documentation/getting-started/installation/ and dnf simply could not find zola.
![image](https://user-images.githubusercontent.com/24732611/213395705-86c37551-1583-4980-9473-be0cf45d92c2.png)

## Proposed Solution
Add a package for Fedora 37.

**Comment by Keats** [comment]
See https://github.com/getzola/zola/issues/2058
We are going to remove that part from the docs

**Comment by c-git** [comment]
You can use one of the other options like snap or Flatpak which should work on all distros

**Comment by bronson** [comment]
Zola doesn't appear to have a Flatpak: https://flathub.org/apps/search/zola. Does the Flatpak exist somewhere else?

[Snap](https://snapcraft.io/zola) and COPR work.

**Comment by ghost** [comment]
> # Installation on Fedora 37
> ## Summary
> 
> I followed instructions on https://www.getzola.org/documentation/getting-started/installation/ and dnf simply could not find zola. ![image](https://user-images.githubusercontent.com/24732611/213395705-86c37551-1583-4980-9473-be0cf45d92c2.png)
> ## Proposed Solution
> 
> Add a package for Fedora 37.

Hello!
You can install from copr repo - https://www.getzola.org/documentation/getting-started/installation/#fedora
