### ISSUE TITLE
Carousel / image slideshow

### ISSUE THREAD

**Issue by tatref** [Keats/gutenberg#2093]
First off, I'm not very versed at web stuff, so I'm sure if this is supposed to be done in the site generator, or theme or template engine?

Anyway, is there some simple way to create a carousel or image slideshow with Zola?
Feel free to close the issue if this is not supposed to be done in Zola.

Thanks!

**Comment by Keats** [comment]
I haven't looked at it for Zola but that will have to be done in JS either way.
