### ISSUE TITLE
0.17 get_url, page.colocated_path & directory with date in path = invalid url

### ISSUE THREAD

**Issue by jimmyff** [Keats/gutenberg#2095]
# Bug Report

[get_url](https://www.getzola.org/documentation/templates/overview/#get-url) creates an invalid url if the post is in a directory with a date using `page.colocated_path`

## Example:

folder: `blog/2023-08-10-test/` would get a url of `blog/test/`, within the index.md or macro if I say something like: 
```
<img alt="{{ alt }}" title="{{ alt }}" src="{{ get_url(path=path ~ src) | safe }}" class="{{ class }}" />
```
where `path = page.colocated_path` and `src="image.png"` then I get a URL of : 
`http://127.0.0.1:1111/blog/2023-08-10-test/image.png`

however this is invalid as zola expected the date to have been stripped to: 
`http://127.0.0.1:1111/blog/test/image.png`

## Environment

Zola version: 0.17

**Comment by Keats** [comment]
`page.colocated_path` is only meant to be used with local assets. It represents the path on disk

**Comment by jimmyff** [comment]
ahh gotcha, my bad!
