### ISSUE TITLE
Tower livereload

### ISSUE THREAD

**Issue by allan2** [Keats/gutenberg#2099]
I have been using [tower-livereload](https://github.com/leotaku/tower-livereload) in a small project and it works great.

Watcher can be setup using to respond to changes from the filesystem. [Example](https://github.com/leotaku/tower-livereload/blob/master/examples/axum-in-process/src/main.rs)

Would there be any interest in using this with Zola in place of livereload-js?

**Comment by Keats** [comment]
What's the benefit of switching? Is livereload-js not working well?
