### ISSUE TITLE
Slow build time

### ISSUE THREAD

**Issue by jimmyff** [Keats/gutenberg#2106]
# Bug Report

Zola version: 0.17.0

My site takes a long time build. Once the image resizing is done (first build), subsequent builds takes around 30 seconds  @Keats suggested it might be taxonomy related. 

Here is the repo: https://github.com/jimmyff/jimmyff-website

**Comment by Raymi306** [comment]
Linking #2079 as there was interesting discussion there.

Having some troubles with flamegraph-rs hangs after collecting perf.data and before generating the flamegraph.svg on both debian on metal and ubuntu on wsl2 for me right now and I dk why...

I downloaded hotspot to analyze the perf.data, and I see a ton of time spent on imageproc and webp calls.
This makes me suspect that taxonomies are not the problem, but this directly contradicts @Keats findings so I'm not sure what to make of that.
I did make sure to build the site once before measuring.
On my system I was experiencing 80 second build times while running perf tracing.

![image](https://user-images.githubusercontent.com/45133114/235825133-d58daeee-4a82-4225-89d9-a6af5eda298d.png)

**Comment by Keats** [comment]
webp is slow but I think some of the slowness is also unrelated to images, you can uncomment all the resize_image call and it's still not super fast if i remember correctly

**Comment by Raymi306** [comment]
I was also wondering, why is there so much time being spent on image processing if things are meant to be cached after first build?

**Comment by Keats** [comment]
We don't keep a on-disk cache for all images so you still need to read their metadata at least once to get their dimensions. webp i believe will read the full image.

**Comment by welpo** [comment]
> webp i believe will read the full image

Is this something that can be fixed? Is it a problem with the WebP specification, a crate Zola is using, or Zola itself?

My build times are quite slow, and WebP images are to blame. Switching to PNG files speeds up the build time, but at the cost of larger files.

**Comment by welpo** [comment]
Site building is much, much faster with Zola 0.19! Looks like the webp issue is fixed.
