### ISSUE TITLE
Syntax theme links mostly dead

### ISSUE THREAD

**Issue by waynee95** [Keats/gutenberg#2114]
# Documentation issue

## Summary
Most links found in the syntax theme section are dead.

https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting

## Proposed solution
According to [this](https://github.com/aziz/tmTheme-Editor/issues/275) issue, the app can be found at https://tmtheme-editor.glitch.me/

**Comment by Keats** [comment]
Nice, I didn't realise it got put on some other site!

**Comment by waynee95** [comment]
The original url is dead because the project seems a bit abandoned. That other url is not provided by the maintainer of the project, AFAICT.
