### ISSUE TITLE
Each `resize_image` adds significantly to build time even after initial build

### ISSUE THREAD

**Issue by miakramer** [Keats/gutenberg#2118]
# Bug Report

## Environment

Zola version: 0.17

## Expected Behavior

On the first build, we need to generate sized images, so that should take a while. After that, if the images and settings don't change, we should not need to do expensive operations per-image.

## Current Behavior

Every call to `resize_image` adds significantly to every build even if the images and settings have not changed.

## Step to reproduce

- Follow the "getting started" tutorial to get a basic site going and `zola serve`
- Add some images to the static directory (I used all webp, fairly high resolution of about 24 megapixels)
- Create a shortcode that uses a couple sizes of them, like:

```html
<picture>
    {% set size1080 = resize_image(path=file, width=1920, height=1080, op="fit", format="webp") %}
    {% set size1440 = resize_image(path=file, width=2560, height=1440, op="fit", format="webp") %}
    {% set size2160 = resize_image(path=file, width=3840, height=2160, op="fit", format="webp") %}
    <source srcset="{{ size1080.url }}, {{ size1440.url }} 1.5x, {{ size2160.url }} 2x">
    <img src="{{ file }}">
</picture>
```

- Use this shortcode (called `sizeit` here) in one of the content files:

```md
+++
title = "My first post"
date = 2019-11-27
+++

This is my first blog post.

{{ sizeit(file="/image1.webp") }}

{{ sizeit(file="/image2.webp") }}

{{ sizeit(file="/image3.webp") }}
```

- This first build creates the sized images (with three of those 24 megapixel images, this took about 4.5 seconds for me)
- Change some text in the content and save to trigger rebuild. (this took 2.5 seconds)
- Each additional image added here increases the initial build by about 2-3s and subsequent builds just changing text or templates by 1s. Changing just the SCSS (if compilation is turned on) causes a very fast build

**Comment by Keats** [comment]
Hmm in theory we only need to read metadata for a file once but I guess if the file output already exist we should skip that step altogether.
That should be easy to fix if someone wants to try. It's in `components/imageproc/src/processor.rs::enqueue`

**Comment by Keats** [comment]
Hmm we do actually need to get the metadata at least once for each in practice.
Is the issue only with webp images?

**Comment by miakramer** [comment]
I tried after converting all the images to .PNG and using those and that seems much faster, initial build is 1.5 seconds and subsequent builds are <200ms.

**Comment by Keats** [comment]
I'm wondering if the image crate reads the full webp image to return the metadata.

**Comment by miakramer** [comment]
That would explain the behaviour. If I'm reading [this](https://docs.rs/image/0.24.5/src/image/codecs/webp/lossless.rs.html#146) correctly, it looks like that's what's happening. I'll open an issue with the `image` crate, and use .PNG as a workaround. Thanks for the help!
