### ISSUE TITLE
`{{ current_url }}` and `{{ current_path }}` in a Taxonomy single context is returning the wrong url

### ISSUE THREAD

**Issue by jamiedumont** [Keats/gutenberg#2119]
# Bug Report

## Environment

Zola version: 0.16.1

## Expected Behavior
I'm setting canonical URLs with `{{ current_url }}` after checking if it's present (to handle 404s).

On pages rendered with a `taxonomy_single` template, the url should be the current url as per [the docs](https://www.getzola.org/documentation/content/taxonomies/#output-paths)

For example, when viewing the "Makers" term in the "Series" taxonomy, I would expect the path to be `/series/makers`

## Current Behavior

Instead, the `{{ current_url }}` and `{{ current_path }}` is returning only the taxonomy slug (as if it were the taxonomy list).

In the above example, when visiting the "Makers" term for the "Series" taxonomy, the browser URL shows `/series/makers` (generated links with `term.permalink` are working correctly) but the `{{ current_url }}` variable will display just `/series/`, omitting the term.

## Step to reproduce
I've reproduced this with multiple taxonomies within my codebase.

**Comment by Keats** [comment]
It has been fixed in 0.17 afaik?

**Comment by jamiedumont** [comment]
Ah, apologies. I'll update to 0.17 and let you know!

**Comment by jamiedumont** [comment]
It was indeed fixed. In future I'll check for updates first! Thanks for the swift reply.
