### ISSUE TITLE
content url pattern

### ISSUE THREAD

**Issue by brmassa** [Keats/gutenberg#2121]
The basic requirement when porting a site is the maintenance of the old URLs. A site that was not "fortunate" to adopt the default Zola URL pattern previously will break ALL URLs.

Of course, it could be achieved by implementing a `path` on EACH and EVERY content. It's error-prone and difficult to maintain. If eventually the used variable (title, date, or filename) eventually changes (especially during the draft phase), the URL may not follow. Another checklist item.

If the scope of the project is to create small sites, ok. If the selling proposition is to manage large content pools, it is a must, IMHO. A use case is the automatic content creator (like documentation a software API) that creates thousands of .md files and then delegates them to an SSG to build the site. With proper URL configuration, the pages could be presented in a flat structure like a wiki or very hierarchical.

Some advantages:

*  decoupling the internal file organization of the final site organization.
*  _Tokenization_ of page, site, or file variables could be useful in other places.

At least open the door for someone to implement it in a PR.

**Comment by Keats** [comment]
Since you posted that comment in the other similar closed issue, it's not going to happen. This feature doesn't fit Zola.
