### ISSUE TITLE
Search is not working in the docs

### ISSUE THREAD

**Issue by kytta** [Keats/gutenberg#2123]
# Documentation issue

## Summary
Not sure how this hasn't been reported yet, but the search on Zola Documentation website doesn't work.

Upon a closer inspection, the JSON index doesn't seem to exist. Instead of [`search_index.en.json`](https://www.getzola.org/search_index.en.json), [`search_index.en.js`](https://www.getzola.org/search_index.en.js) gets generated. When I try to build the docs locally, it doesn't happen.

## Proposed solution
I have no clue, tbh. Can it be that the Netlify build doesn't work?

**Comment by Keats** [comment]
Woops, I had left the other search engine format when I tried it. It should be ok now once Netlify rebuilds the site.

**Comment by kytta** [comment]
Hey @Keats, did the rebuild complete correctly? Because I am still encountering this same issue :/

**Comment by Keats** [comment]
So the commit above was wrong, it's just that I forgot to bump the Zola version used by netlify. It's back on now, thanks for the heads up
