### ISSUE TITLE
[Regression] Doesn't build without top-level templates directory

### ISSUE THREAD

**Issue by vimpostor** [Keats/gutenberg#2150]
Since version 0.17.1 zola requires the top-level `/templates` directory to exist, even if a theme is used. Otherwise it will fail with:
```
Error: Failed to build the site
Error: Error parsing templates from the /templates directory
Error: Reason: Io error while writing rendered value to output: NotFound
Error: Reason: No such file or directory (os error 2)
```

This is because now tera handles globs differently, as discussed in https://github.com/Keats/tera/issues/819#issuecomment-1480392230.

I believe that this is not very user-friendly, as it can quickly lead to unexpected build failures with the default setup as follows:
- Run `zola init mysite`
- Run `zola serve`
- The official default index.html says that you should either add an `index.html` or add a theme to use
- You decide for the second option and add a theme, which leaves the top level templates directory empty
- It builds fine, so you push to a git repo
- Now pulling on a different machine or on CI will cause zola to fail building the site, because there is no templates directory checked into git

In my opinion this is not optimal, and zola should still work if there is no top-level templates directory.

The following patch fixes the problem from zola's side:
```diff
diff --git a/components/templates/src/lib.rs b/components/templates/src/lib.rs
index 6441ff49..e2747bfc 100644
--- a/components/templates/src/lib.rs
+++ b/components/templates/src/lib.rs
@@ -47,8 +47,7 @@ pub fn load_tera(path: &Path, config: &Config) -> Result<Tera> {
 
     // Only parsing as we might be extending templates from themes and that would error
     // as we haven't loaded them yet
-    let mut tera =
-        Tera::parse(&tpl_glob).context("Error parsing templates from the /templates directory")?;
+    let mut tera = Tera::parse(&tpl_glob).unwrap_or(Tera::default());
 
     if let Some(ref theme) = config.theme {
         // Test that the templates folder exist for that theme
```

However it's not really a good solution, because it will shadow actual parsing problems if `/templates` exists and there are real problems. This is why I believe this problem is better fixed on tera's side, i.e. making invalid globs just return the empty set instead of an error, which is how it is done in most languages.

**Comment by iwahbe** [comment]
This is extremely unfriendly, especially since you can't check an empty folder into git. 

We can do better then just ignoring all errors here. At the very least, we can check the err kind and apply defaults only if the expected file is missing:

```patch
 components/templates/src/lib.rs | 13 ++++++++++---
 1 file changed, 10 insertions(+), 3 deletions(-)

diff --git a/components/templates/src/lib.rs b/components/templates/src/lib.rs
index 6441ff49..7f1aaa53 100644
--- a/components/templates/src/lib.rs
+++ b/components/templates/src/lib.rs
@@ -5,7 +5,7 @@ use std::path::Path;
 
 use config::Config;
 use libs::once_cell::sync::Lazy;
-use libs::tera::{Context, Tera};
+use libs::tera::{self, Context, Tera};
 
 use errors::{bail, Context as ErrorContext, Result};
 use utils::templates::rewrite_theme_paths;
@@ -47,8 +47,15 @@ pub fn load_tera(path: &Path, config: &Config) -> Result<Tera> {
 
     // Only parsing as we might be extending templates from themes and that would error
     // as we haven't loaded them yet
-    let mut tera =
-        Tera::parse(&tpl_glob).context("Error parsing templates from the /templates directory")?;
+    let mut tera = match Tera::parse(&tpl_glob) {
+        Ok(t) => t,
+        Err(e) if matches!(e.kind, tera::ErrorKind::Io(std::io::ErrorKind::NotFound)) => {
+            Tera::default()
+        }
+        Err(e) => {
+            return Err(e).context("Error parsing templates from the /templates directory");
+        }
+    };
 
     if let Some(ref theme) = config.theme {
         // Test that the templates folder exist for that theme
```

I'm going to open a PR.

**Comment by Keats** [comment]
> especially since you can't check an empty folder into git.

You can, you just need to add a dummy file in it (usually an empty .gitkeep by convention). I agree it needs to be fixed though

**Comment by proofy** [comment]
As a supplement: This error also occurs if a theme is defined. Then the template directory should generally not matter, or?

**Comment by Keats** [comment]
You can overwrite any templates of a theme so we need to load both.
