### ISSUE TITLE
panic on zola serve from a folder with missing config

### ISSUE THREAD

**Issue by DrGo** [Keats/gutenberg#2159]
# Bug Report

## Environment
Darwin drlab 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 arm64

Zola version:
zola 0.17.2

## Expected Behavior
error message

## Current Behavior
~/local/code> RUST_BACKTRACE=full zola serve
thread 'main' panicked at 'could not find directory containing config file', src/main.rs:19:28
stack backtrace:
   0:        0x10532f9b8 - __mh_execute_header
   1:        0x104d309f0 - __mh_execute_header
   2:        0x105314648 - __mh_execute_header
   3:        0x10532f710 - __mh_execute_

## Step to reproduce
zola serve from a folder with missing config

**Comment by Raymi306** [comment]
Looks like this can be closed
