### ISSUE TITLE
[bug] config.search.index_format not accessible from templates.

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#2165]
# Bug Report

I am in the process of [refactoring the Abridge theme](https://github.com/Jieiku/abridge/issues/105).
One of the things I am doing is switching over to the [new json index format](https://github.com/getzola/zola/pull/1998)

When using the new json index format, you use a different search.js then you would with the regular js index. (this new version fetches the json file on interaction)

because of this I need to ensure or check that the right configuration is set.

```html
  {%- if config.search.index_format == "elasticlunr_json" %}
  <script defer src="{{ get_url(path='search_json.js', trailing_slash=false, cachebust=true) | safe }}"{%- if config.extra.integrity | default(value=true) %} integrity="sha384-{{ get_hash(path='search_json.js', sha_type=384, base64=true) | safe }}"{%- endif %}></script>
  {%- else %}
  <script defer src="{{ get_url(path='search_js.js', trailing_slash=false, cachebust=true) | safe }}"{%- if config.extra.integrity | default(value=true) %} integrity="sha384-{{ get_hash(path='search_js.js', sha_type=384, base64=true) | safe }}"{%- endif %}></script>
  {%- endif %}
```

## Environment

Zola version: 0.17.1

## Expected Behavior
I need for `config.search.index_format` to be accessible.

OR maybe `build_search_index = true` could also be `build_search_index = "elasticlunr_json"`  then there would not even be the need for the additional `index_format` field.

## Current Behavior
Currently you cannot check the value of `config.search.index_format` from templates

**Comment by Raymi306** [comment]
This can be closed

**Comment by Keats** [comment]
Issues are only closed once the Zola release containing the fix is released

**Comment by Raymi306** [comment]
Oh WHOOPS!  I commented on several issues, my bad!
