### ISSUE TITLE
About my pull request

### ISSUE THREAD

**Issue by mehmetcansahin** [Keats/gutenberg#2166]
Hi,
Why did you close my Pull request #2160? And without leaving any answer. I opened it by solving the problem you referenced in the previous pull request.

@Keats

**Comment by Keats** [comment]
It wasn't solving anything? Just replacing an example that seem to annoy some people from a specific country, not the first time it's happening

**Comment by mehmetcansahin** [comment]
I strongly disagree, he is a terrorist in our country and in many countries of the world. An article that makes terrorists look cute. If you want to get more information;
you can get it from [here](https://www.mfa.gov.tr/pkk.en.mfa). Also, the text I shared is only in Turkish, "hello world". Please reconsider this.
