### ISSUE TITLE
Is it possible to make taxonomies optional? (Display warning instead of error if content has taxonomies defined)

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#2172]
# Bug Report

I am in the process of [refactoring abridge](https://github.com/Jieiku/abridge/tree/refactor), one of the things I am doing is making it so that the site will still zola build or zola serve, even if options are missing in the config.toml (by defining defaults in the template files). I am now down to only 3 things being required:

```toml
base_url = "https://abridge.netlify.app"
compile_sass = true
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
```

This got me thinking, what if somebody wants to try temporarily disabling taxonomies, to do so they would have to go into ALL of their content and remove the entries.

so maybe instead of this:
```
Error: Page `/home/jieiku/.dev/abridge/content/overview-rich-content/index.md` has taxonomy `tags` which is not defined in config.toml
```

you get something like this:

```
Warning: Some content has defined taxonomies: `tags`, `categories` which are not defined in config.toml, so these taxonomies will not be generated.
```

## Environment

Zola version: 0.17.1

## Expected Behavior
I think it would be good for the site to still build even if the config.toml is missing the taxonomy, but I am not sure if this could have implications that I am not thinking of?

If there is pause for concern then maybe zola could have a build/serve flag, eg: `zola build --taxonomy-warn` in which it would only give a warning but still build without said taxonomies. The default error message could also let the user know they can try using the taxonomy-warn flag.

## Current Behavior
```
Error: Page `/home/jieiku/.dev/abridge/content/overview-rich-content/index.md` has taxonomy `tags` which is not defined in config.toml
```

## Step to reproduce
- have some content with defined taxonomies
- comment out your taxonomies in your config.toml
- zola build or zola serve

**Comment by Keats** [comment]
I think I would rather keep it as an error rather than making it a warning, even opt in

**Comment by Jieiku** [comment]
If somebody has 1,000s of posts they could just run a bash script that performs sed on them to remove the taxonomies.

Feel free to close, just something I thought of while working on stuff.

It is unlikely many sites with that much content would disabled taxonomies if they are already in place... but they might want to if they are trying to debug things.

**Comment by Keats** [comment]
I think it's better to error than have thousands of warnings in the console (since the warnings would point to each file)
