### ISSUE TITLE
Use shortcodes from a custom path

### ISSUE THREAD

**Issue by eugenesvk** [Keats/gutenberg#2175]
I'm trying to achieve something similar to https://github.com/getzola/zola/issues/375 (include html files directly within markdown pages)
There is another issue that is tracking shortcodes within shortcodes (https://github.com/getzola/zola/issues/515 which may or may not help depending on whether I misunderstood it)

But I thought that another potentially simpler solution would be to allow paths to shortcodes instead of just names

This way I could have a co-located folder with the "templates" that would just be html content that is currently inlined, and then I'd:
  - refer to these files within markdown as `{{ colocated_shortcodes/shortcode_html_file () }}`
  - to "import" the content of `./colocated_shortcodes/shortcode_html_file.html` file

(currently this works as `{{ shortcode_html_file () }}` with `templates/shortcodes/shortcode_html_file.html`

**Comment by Keats** [comment]
Shortcodes are not just for embedding HTML, they can have logic. Does having a `include_file` shortcode that use `load_data` on the given path and outputs it work for you?

**Comment by eugenesvk** [comment]
> Shortcodes are not just for embedding HTML, they can have logic.

That's fine, they can still retain that capability, just at a non-default path

> Does having a include_file shortcode that use load_data on the given path and outputs it work for you?

But how can I pass path to it? Let's say I have 10 `parts/part1.html`, `parts/part2.html`, ...
How would I write a single shortcode (instead of 10) that would allow writing in markdown

```
{ include_file ("parts/part1.html") }}
{ include_file ("parts/part2.html") }}
...
```

**Comment by Keats** [comment]
Shortcodes take arguments so it would look something like https://github.com/getzola/zola/blob/master/docs/content/documentation/content/shortcodes.md#shortcodes-without-body (minus the `/* */` stuff)

**Comment by eugenesvk** [comment]
They do, but then I can't pass that argument to the function within `{% %}`
```md
# page.md
{{ include_file (path="parts/part1.html") }}
```

```html
<!-- shortcodes/include_file.html -->
{% set data = load_data(path="content/test/parts/part1.html") %}
<!-- ↑works ↓fails -->
{% set dd = load_data(path="content/test/{{path}}") %}
```

so I can't have a single shortcode for multiple paths that will be passed from within the markdown document

(then the `test` would also be replaced by `{{page.colocated_path}}`)

**Comment by Keats** [comment]
You can, `{% set dd = load_data(path="content/test/" ~ {{path}}) %}` (although I'm having some issues remembering if you can concat in the arg param, otherwise just do it in another `set`)

**Comment by eugenesvk** [comment]
Thanks, the `{{}}` was also the issue, sorry, mixed my tera braces
so shortcode `include_file_coloc` file
```
{% set data = load_data(path="content/" ~ page.colocated_path ~ file) %}
{{ data | safe}}
```

Then you can call this shortcode `include_file_coloc` file like
```
{{ include_file_coloc (file="fd/file.html.tmpl") }}
```
(in the `fd` subfolder of the same folder where your `page.md` is)

and ignore these "template" files like so
```toml
ignored_content            	= ['*.tmpl']
```

(and you can also config your editor to ignore `.tmpl` extension for syntax highlighting purposes, so when you edit them you'll still get html syntax)
