### ISSUE TITLE
minify replaces HTML entities by their reserved characters

### ISSUE THREAD

**Issue by blueglyph** [Keats/gutenberg#2177]
For information, I reported this problem directly on the minify-html repo:

https://github.com/wilsonzlin/minify-html/issues/139

In summary, this:

```html
<a class="disabled" href=''>&lt;</a>
<a href='http://192.168.1.38:1111/page/2'>&gt;</a>
```

produces this (without the CR), with `&lt;` and `&gt;` replaced as `<` and `>` and corrupting the HTML file:

```html
<a class=disabled href><</a>
<a href=http://192.168.1.38:1111/page/2>></a>
```

I'm attaching a fake project to reproduce the problem (uncomment `minify_html = true` in the configuration):
[bug_minify.zip](https://github.com/getzola/zola/files/11201175/bug_minify.zip)

**Comment by Keats** [comment]
Not a problem as per the upstream issue.

**Comment by blueglyph** [comment]
It's probably not a problem for most browsers, indeed.

I don't think I'll be using it though, as it generates so many errors in the validator that actual errors may go unnoticed.
