### ISSUE TITLE
Error when building the site with new version 0.17.2

### ISSUE THREAD

**Issue by gersonbenavides** [Keats/gutenberg#2186]
# Bug Report

## Environment
Zola version: 0.17.2
SO: Windows 11

## Expected Behavior
The site builds correctly with version 0.16.1, when upgrading the Zola version to 0.17.2 the site is unable to build correctly.

### Zola 0.17.2
```bash
Building site...
Warning: config.toml contains both default language specific information at base and under section `[languages.en]`, which may cause merge conflicts. Please use only one to specify language specific information
Error: Failed to serve the site
Error: Error parsing templates from the /templates directory
Error: Reason: Io error while writing rendered value to output: NotFound
Error: Reason: No such file or directory (os error 2)  
```

### Zola 0.16.1
```bash
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 3 pages (0 orphan) and 4 sections
Done in 623ms.

Web server is available at http://127.0.0.1:1111
```

## Step to reproduce
To reproduce the bug, make use of the Ataraxia template, as an example you can use the [github.com/gersonbenavides/gersonbenavides.github.io](https://github.com/gersonbenavides/gersonbenavides.github.io) repository.

**Comment by Jieiku** [comment]
The language message is a warning, but it is not what is stopping it from building.

Your site no longer builds because of the missing templates directory: https://github.com/getzola/zola/issues/2150

I sent you a pull request that should add that directory and allow the site to build.

**Comment by gersonbenavides** [comment]
Gracias por tu respuesta, ahora compila perfectamente 🙂.

**Comment by Jieiku** [comment]
I am currently working on supporting translations in the Abridge theme.

I know the cause of the language warning now, basically if you want to avoid that warning, and the possible issues its suggesting, then do not provide a translations section for the configured base language, instead only do the translation if the current language is not the configured default language, here is a small snippet from the menu I am currently working on:

```
{%- if lang != config.default_language -%}
    {{ trans(key=i.name | safe, lang=lang) }}
{%- else -%}
    {{ i.name | safe }}
{%- endif -%}
```
