### ISSUE TITLE
cargo build speed for Zola

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#2188]
# Documentation issue

https://www.getzola.org/documentation/getting-started/installation/#from-source

It takes me about 3 minutes to compile Zola.

Every time I want to test a change I build zola, then use it to build a site:

```bash
cargo build --release
   Compiling templates v0.1.0 (/home/jieiku/.dev/zola/components/templates)
   Compiling site v0.1.0 (/home/jieiku/.dev/zola/components/site)
   Compiling zola v0.17.2 (/home/jieiku/.dev/zola)
    Finished release [optimized] target(s) in 3m 12s
```

```bash
cd ~/.dev/test_site
/home/jieiku/.dev/zola/target/release/zola build
```

## Summary
I am wondering if there is anything I can do to speed up compile time. (other than replacing my computer: e3-1275v2)

I did notice that it appears to only use a single core during build. (htop only shows a single core at 100%)

## Proposed solution
Would appreciate any pointers from people that have been developing rust for a while.

I am also independently searching google for general things such as "cargo build faster", etc...

but I would really love to hear what Zola developers do to speed it up. (if anything)

If there is nothing I can do then so be it, I do plan to upgrade eventually, just can't afford it at the moment.

Also if cargo/rust is mainly a single threaded build, then it seems whenever I do build a new PC that picking a CPU with a good single thread performance would be important to build times.

I just read that Cargo parallelizes at the crate level, so that explains why the Zola project is split into Crate components :)

## ALSO, please let me know what CPU you guys have, and what your build times look like, I appreciate it.

**Comment by Keats** [comment]
You don't need --release to test things, do a normal cargo build. If it can
be a unit test then it's easier, just use cargo test

**Comment by Jieiku** [comment]
> You don't need --release to test things, do a normal cargo build.

oh my, that reduced it to 6 seconds, now I just feel silly.

Thank you!
