### ISSUE TITLE
Mastodon as a comment system - enhancement

### ISSUE THREAD

**Issue by hadilq** [Keats/gutenberg#2206]
# Mastodon proposal
Mastodon is a micro blogging social media, which is so suitable to being able to handle comments of a real blog. On the other hand, zola generates static blogs, so Matodon can take care of the comments.

There are multiple ways that it's implemented for blogs:
 - https://danielpecos.com/2022/12/25/mastodon-as-comment-system-for-your-static-blog/
 - https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/

To render the comments, we need to know the host, username, and the id of a toot(toot is a post in Mastodon!). Clicking on any comment will open the toot in its host, so user can reply, reshare, etc.

BTW, I'm not sure if this could be an enhancement in the zola itself, maybe it should be supported by themes! For me as a user, a workaround would help. Thanks!

**Comment by Keats** [comment]
That sounds like Zola itself doesn't have to do anything, it's all themes?

**Comment by hadilq** [comment]
totally makes sense. Thanks,
