### ISSUE TITLE
Zola warns about 'text' as a codefence syntax, but markdown lints say that's valid and preferred

### ISSUE THREAD

**Issue by damccull** [Keats/gutenberg#2221]
# Bug Report
Zola warns when you use
```text
```text
Some text
\```
```
(please ignore the backslash)

The markdown lints at https://github.com/DavidAnson/markdownlint/blob/v0.28.2/doc/md040.md say that you should use the 'text' type if you just want plain text instead of making it blank.

## Environment

Zola version: 0.17.2

## Expected Behavior
No warning should be emitted.

## Current Behavior
I am seeing lines like:

`Warning: Highlight language text not found in blog/myblogentry/index.md`

## Step to reproduce
Produce any codefence block without a syntax specified and run a linter (like the vscode extension [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)) and see the error.

**Comment by Keats** [comment]
I'm not sure why that linter is making that recommendation. If you put some language, we're going to try to find the syntax for it and you get that error message as expected.
That seems like an opinionated suggestion rather than a good lint.
