### ISSUE TITLE
Error when markdown filename has .something.md where something is not a valid lang code

### ISSUE THREAD

**Issue by DrGo** [Keats/gutenberg#2222]
# Bug Report

## Environment

Zola version:
0.17.1

## Expected Behavior
No error

## Current Behavior
Error: File "blog/content/blog/httpswww.facebook.comislamicrelief.canada.md" has a language code of facebook.comislamicrelief.canada which isn't present in the config.toml `languages`

## Step to reproduce
create file similar to the above file

**Comment by Keats** [comment]
That's intended. The `.{...}.md` pattern is reserved for a language code.
