### ISSUE TITLE
Zola on chocolatey is outdated

### ISSUE THREAD

**Issue by wischi-chr** [Keats/gutenberg#2228]
# Documentation issue

## Summary
Chocolatey is listed in the official documentation but outdated.

## Proposed solution
Update the version provided via chocolatey, or remove chocolatey from the docs, so users don't accidentally install outdated verions.
(See this issue for example: https://github.com/welpo/tabi/issues/81)

**Comment by Keats** [comment]
I don't know chocolatey, can anyone submit a PR to update it?

**Comment by welpo** [comment]
The specific maintainer of the [Zola package in Chocolatey](https://community.chocolatey.org/packages/zola) is in charge of upgrading it.

Here's the docs regarding what to do when a package is outdated: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#the-triage-process

And this is the repository linked to Chocolatey that would need to be updated: https://github.com/gsomix/ChocolateyPackages

**Comment by wischi-chr** [comment]
Alternatively the chocolatey package could also be marked as "unofficial" in the documentation if it's not something that "zola maintainers" manage.

**Comment by Keats** [comment]
Really, all of them except snap and docker are unofficial and that's official only because it can be built automatically on release. We should add a disclaimer to the page

**Comment by welpo** [comment]
As the original maintainer was unresponsive (I tried to update the package with a PR), I am now a maintainer of the Zola package in Chocolatey ([the repo](https://github.com/welpo/chocolatey-packages)).

Version `0.17.2` is now available: https://community.chocolatey.org/packages/zola/

I'll do my best to keep it up to date!

**Comment by Keats** [comment]
Nice, thanks!
