### ISSUE TITLE
Error in headers for Github GraphQL example

### ISSUE THREAD

**Issue by Aonrud** [Keats/gutenberg#2229]
# Documentation issue

## Summary
The example using `load_data()`  to fetch from the Github GraphQL API has an `authentication` header. The header for sending the token should be `authorization` as [per the Github documentation](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql).

## Proposed solution
Update [overview.md (line 472)](https://github.com/getzola/zola/blob/master/docs/content/documentation/templates/overview.md?plain=1#L472) to use `authorization` instead in case anyone else lazily cuts and pastes the example as a starting point (like I did!) and gets a failed query.

**Comment by Keats** [comment]
A PR would be nice!

**Comment by Aonrud** [comment]
Apologies – that was a bit lazy! :)

Sent a PR to master since it's a documentation correction.
