### ISSUE TITLE
Is there a way to filter out non-text tags from the page summary?

### ISSUE THREAD

**Issue by dossalab** [Keats/gutenberg#2231]
Hi all,

I'm trying to use the summary feature described [here](https://www.getzola.org/documentation/content/page/#summary). The issue is that most of my pages have a title image somewhere in the first paragraph, so when I add a summary marker this image gets included into the summary. I'm formatting the index page differently so I need just the text.

I've also tried `description` in the front matter but writing such long descriptions manually is annoying and redundant.

So I'm thinking how to overcome that issue? AFAIK there are no tag filters in Tera? The most obvious for me as a user would be to have some text filter (so `page.summary | filter_text() ) `. Using regex is another thing but I'm not sure if I want to go that way.

**Comment by Keats** [comment]
There is a https://tera.netlify.app/docs/#striptags filter but otherwise no HTML aware tags.

**Comment by dossalab** [comment]
I was thinking on the possible solutions but it's hard for me to come up with something nice. I think I'll switch to using descriptions for now.
