### ISSUE TITLE
`public` dir missing from directory structure page

### ISSUE THREAD

**Issue by kotx** [Keats/gutenberg#2238]
# Documentation issue

## Summary
In the [directory structure](https://www.getzola.org/documentation/getting-started/directory-structure/) doc page, `public` dir is missing.

## Proposed solution
Was a bit confused when I ran `zola serve` and didn't notice the `public` directory until after. Should probably mention in the docs.

**Comment by Keats** [comment]
So the `public` folder is created/deleted automatically and it can be changed. It is mentioned in https://www.getzola.org/documentation/getting-started/cli-usage/#build

**Comment by kotx** [comment]
Made a PR (#2240) that could help clarify the documentation?
