### ISSUE TITLE
Fix Potential Footgun Leading to Data Loss

### ISSUE THREAD

**Issue by ElliotKillick** [Keats/gutenberg#2251]
# Bug Report

## Environment

Zola version: 0.17.2

## Expected Behavior

Zola should refuse to use a non-empty output directory unless maybe a `force` option is provided. Forcing is what's required if you try to `init` in a non-empty directory so it's a bit inconsistent here.

## Current Behavior

`zola serve -o <DIR>` will output to any directory even if it's non-empty. Upon `zola serve` termination (^C) the output directory is recursively deleted which could lead to potential data loss if a user incorrectly specifies the output directory. The consequences are especially severe if `~` is accidentally specified...

## Step to reproduce

Warning: Potential data loss

```
zola serve -o static
^C
```

**Comment by ElliotKillick** [comment]
Just found that Zola already implements this check for `zola build` but for `zola serve` it's missing:

```
~/Downloads/zola-v0.17.2-x86_64-unknown-linux-gnu/zola build -o content 
Building site...
Error: Failed to build the site
Error: Directory 'content' already exists. Use --force to overwrite
```

**Comment by SquirrelHub** [comment]
Would I be able to work on this issue, or is somebody else already tackling this issue?
I've managed to duplicate the behavior described, and I could mimic the behavior of the build command if that's desired.

That being said, for specifying an argument to force an override of the directory, the `fast` option in `serve` is already using the `f` for the short option, where build did not have that concern. What would be an appropriate character for that?

**Comment by Keats** [comment]
We can have only the long option, that would be fine.
