### ISSUE TITLE
Exclude custom `404` pages from `sitemap.xml`

### ISSUE THREAD

**Issue by cyann** [Keats/gutenberg#2260]
# Bug Report

## Environment

Zola version: 0.17.2

## Expected Behavior
I've looked around and cannot find a way to exclude some pages from `sitemap.xml`.

For example, I've got some custom 404 and 403 pages, and they shouldn't be listed.

## Current Behavior
`sitemap.xml` includes 404 pages (extract):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>/404/</loc>
    </url>
    <url>
        <loc>/de/404/</loc>
    </url>
    <url>
        <loc>/es/404/</loc>
    </url>
    <url>
        <loc>/fr/404/</loc>
    </url>
</urlset>
```

## Workaround

I've set this on my custom 404 and 403 pages:
```html
<head>
	<meta name="robots" content="noindex,nofollow">
</head>
```
I'm expecting the various search engines to ignore these pages.

**Comment by Keats** [comment]
The sitemap is a simple template (https://github.com/getzola/zola/blob/master/components/templates/src/builtins/sitemap.xml), you can create a sitemap.xml in the templates folder and ignore the pages you want to ignore in it.

**Comment by cyann** [comment]
Excellent, thank you!

This works:
```mustache
[...]
  {%- for sitemap_entry in entries %}
  {%- if sitemap_entry.permalink is containing("/404/")
      or sitemap_entry.permalink is containing("/403/") %}
  {%- continue %}
  {%- endif %}
[...]
```

Merci Vincent!

**Comment by Keats** [comment]
Pas de problème!
