### ISSUE TITLE
Minifying HTML introduces invalid characters

### ISSUE THREAD

**Issue by kytta** [Keats/gutenberg#2270]
# Bug Report

## Environment

Zola version: 0.17.2

## Expected Behavior
When `minify_html` is enabled, special characters in code blocks get “minified” too, which results in non-standard HTML5 code.

Let's say, I have this page (ignore the backslashes):

```markdown
---
title: Test page
---
\```py
print(24 & 12 < 10)  # True
\```

This is because `8 < 10`.
```

I expect its minified HTML to be as follows:

```html
<body><pre class=language-py data-lang=py style=background:#2b303b;color:#c0c5ce><code class=language-py data-lang=py><span style=color:#96b5b4>print</span><span>(</span><span style=color:#d08770>24 </span><span>&amp; </span><span style=color:#d08770>12 </span><span>&lt; </span><span style=color:#d08770>10</span><span>)  </span><span style=color:#65737e># True
</span></code></pre><p>This is because <code>8 &lt; 10</code>.
```

## Current Behavior
Instead, the minified HTML includes the characters `<` and `&` as-is:

```html
<body><pre class=language-py data-lang=py style=background:#2b303b;color:#c0c5ce><code class=language-py data-lang=py><span style=color:#96b5b4>print</span><span>(</span><span style=color:#d08770>24 </span><span>& </span><span style=color:#d08770>12 </span><span>< </span><span style=color:#d08770>10</span><span>)  </span><span style=color:#65737e># True
</span></code></pre><p>This is because <code>8 < 10</code>.
```

This is invalid HTML 5 which fails W3C Validator checks.

## Step to reproduce

```toml
# config.toml
minify_html = true
```

```html
<body>{{ page.content | safe }}</body>
```

**Comment by Keats** [comment]
The library we use for minifying (https://github.com/wilsonzlin/minify-html) will sometimes generate code that fails the validator check but that will still render correctly.

**Comment by kytta** [comment]
Oh, right, I should've figured this is coming from a third-party lib 😅
