### ISSUE TITLE
Feature Request: minify-html config pass-through

### ISSUE THREAD

**Issue by Jared-Sprague** [Keats/gutenberg#2277]
Hello!

I noticed that Zola is using the [minify-html](https://crates.io/crates/minify-html) crate.  This crate has a [config option](https://docs.rs/minify-html/0.11.1/minify_html/struct.Cfg.html#structfield.keep_comments) to `keep-comments` but that is not exposed by Zola.  It would be nice if there were an additional config booleon in config.toml to set this and pass it through to the `minify()` function call.

I see that Zola is hard coding the config that gets passed to `minify()` here:
```
pub fn html(html: String) -> Result<String> {
    let mut cfg = Cfg::spec_compliant();
    cfg.keep_html_and_head_opening_tags = true;
    cfg.minify_css = true;
    cfg.minify_js = true;

    let minified = minify(html.as_bytes(), &cfg);
    match std::str::from_utf8(&minified) {
        Ok(result) => Ok(result.to_string()),
        Err(err) => bail!("Failed to convert bytes to string : {}", err),
    }
}
```

I would request that this default config object be available to be overriden in config.toml like so:

```
minify_html = true
minify_config = { keep_comments = true }
```

We need this because we are using Server Side Includes, which is a [standard](https://www.w3.org/Jigsaw/Doc/User/SSI.html#include) that is used by many [web servers](https://en.wikipedia.org/wiki/Server_Side_Includes) such as [Apache SSI](https://httpd.apache.org/docs/2.4/howto/ssi.html).  The problem is that these look like regular HTML comments so the minifier strips them out.  So if we could use the config option to keep_comments offered by the minify-html crate then we could still minify but not break our SSI code.

Thanks!

**Comment by Keats** [comment]
I think I would rather than minify-html ignore those comments with an option that we could enable (I've seen you made an issue on their repo) rather than adding options for it in the config. In those I would recommend running the CLI with the options you want as it's also likely going to be faster (for some unknown reason it was last time we checked).

**Comment by Jared-Sprague** [comment]
Thanks for the response! Yeah we decided that we would use the minify-html crate directly as a post-zola step in our build with the options we want, and it is actually much faster this way.   Maybe someday the SSI directives request I made to the minify-html crate will be picked up.  
Thanks!

**Comment by iWangJiaxiang** [comment]
Hi. I believe this feature is necessary for online static site host platform such as CloudFlare Pages, Netlify and so on.

They provide auto injection feature for web statics js. However, the current default config for `minify_html` removes the tail `</body>` and `</html>` tag, which breaks the auto injection feature.

It is hard for those new bees to install minify-html as binary in static site platform and makes the workflow more complicated, which might push them away from Zola.

I propose to ajust the default config or add the feature to pass through config. And the pass-through would be more universal.

See https://answers.netlify.com/t/snippet-injection-not-working/19626/3

Thank you.

**Comment by iWangJiaxiang** [comment]
Since one of the core features of Zola is ZERO dependency, I think it is better to let users not have to install `minify_html` manully.
