### ISSUE TITLE
Use `fs-err` to improve error messages

### ISSUE THREAD

**Issue by marcospb19** [Keats/gutenberg#2282]
Today I got this error message:

```
$ zola serve
Building site...
Error: Failed to serve the site
Error: Error parsing templates from the /templates directory
Error: Reason: Io error while writing rendered value to output: NotFound
Error: Reason: No such file or directory (os error 2)
```

I'd like to know which file exactly it failed at.

`fs-err` is a drop-in replacement for `std::fs` which provides extra error information, here's the comparison:

```rust
use std::fs;

fn main() {
    println!("{}", fs::read_to_string("does-not-exist").unwrap_err());
    println!("{}", fs_err::read_to_string("does-not-exist").unwrap_err());
}
```

output:
```
No such file or directory (os error 2)
failed to open file `does-not-exists`
```

**Comment by marcospb19** [comment]
docs.rs/fs-err

you can just add `use fs_err as fs;` and it will put better error messages on everything it wraps, including reading files, it doesn't replace async fs modules tho, like tokio.

**Comment by Keats** [comment]
We already have our own wrapper around `std::fs`: https://github.com/getzola/zola/blob/master/components/utils/src/fs.rs

This error is coming from Tera itself, fs-err would not help here.

**Comment by marcospb19** [comment]
Thanks, how should I debug this error? The error message left me confused, should I ask the Tera folks?

**Comment by marcospb19** [comment]
Update: it's working with Zola 0.15.2, so I'll stick to that one, thanks.

**Comment by Keats** [comment]
Is the site failing open-source so we can debug it?

**Comment by marcospb19** [comment]
It is (at the time of writing) https://github.com/marcospb19/marcospb19.github.io.

Just a test, no real content in it.

I believe the first step to debug the error is to understand the error and know which file read failed.

**Comment by Keats** [comment]
This is already fixed in the `next` branch of zola so it will work in the next release automatically.
