### ISSUE TITLE
zola build removed .git directory in public/ folder

### ISSUE THREAD

**Issue by stevenroose** [Keats/gutenberg#2288]
So I'm trying to create a setup using git worktrees to efficiently manage this repo with both a `master` branch with my content and a `pages` branch with the public files. (To use Codeberg Pages.) The process is similar to GitHub pages and the strategy is described here: http://sangsoonam.github.io/2019/02/08/using-git-worktree-to-deploy-github-pages.html

However, when running `zola build`, the `./public/.git` directory gets removed, effectively breaking the git worktree.

It seems that whatever static site generator the writer of that article is using does keep the `.git` filter intact in their build output directory.

Would that be hard to add to zola?

**Comment by stevenroose** [comment]
Ok trying to actually implement this I found the `preserve_dotfiles_in_output` option. That seems to do it. Should this be defaulting to true?

**Comment by Keats** [comment]
> Should this be defaulting to true?

Probably not. The default behaviour is to have a clean slate. This is a settings if you have some specific requirements but for most users they probably do not want to have files kept up.

**Comment by stevenroose** [comment]
Well, idk, I think making an explicit exception for git files or all dotfiles yeah. If zola doesn't actually generate any dotfiles themselves, this should be safe to do, right? Then it's kinda sure that they are user-generated..

Anyway yeah feel free to close if you think the default shouldn't be true.
