### ISSUE TITLE
[Feature request] Add Fluent to syntax highlighting

### ISSUE THREAD

**Issue by walpox** [Keats/gutenberg#2295]
This is a request to add the Fluent language to the built-in [syntax highlighting](https://www.getzola.org/documentation/content/syntax-highlighting/). 

Example:

<pre>
```fluent
# Simple things are simple.
hello-user = Hello, {$userName}!

# Complex things are possible.
shared-photos =
    {$userName} {$photoCount ->
        [one] added a new photo
       *[other] added {$photoCount} new photos
    } to {$userGender ->
        [male] his stream
        [female] her stream
       *[other] their stream
    }
```
</pre>

Source: [https://projectfluent.org/](https://projectfluent.org/)

**Comment by walpox** [comment]
The syntax highlightning page states to open an issue on GitHub, but the contributing guidelines in this repository state to create a post in the forum beforehand. My apologies for creating the issue before the forum post.

**Comment by Keats** [comment]
It's ok, no worries. Adding new syntaxes is on pause for now: https://github.com/getzola/zola/issues/1787 but you can add your own syntaxes easily on your site.
