### ISSUE TITLE
The getzola.org domain does not resolve

### ISSUE THREAD

**Issue by mkroman** [Keats/gutenberg#2296]
The domain `getzola.org` does not resolve as it is supposed to:

```
% dig +short getzola.org @1.1.1.1
% dig +short getzola.org @1.0.0.1
% dig +short getzola.org @8.8.8.8
% dig +short getzola.org @8.8.4.4
```

However `www.getzola.org` works fine:

```
% dig +short www.getzola.org @1.1.1.1
getzola.github.io.
185.199.110.153
185.199.109.153
185.199.108.153
185.199.111.153
```

**Comment by doamatto** [comment]
That's likely in part because the CNAME file ([docs/static/CNAME](https://github.com/getzola/zola/blob/master/docs/static/CNAME)) contains `www.getzola.org`. The solution is to keep the DNS record for `www.getzola.org.`, copy the A/AAAA (or CNAME/ALIAS) record(s) to `getzola.org.`, and change the CNAME file to use `getzola.org`. AFAIK only @Keats can remedy this.

**Comment by Keats** [comment]
I wanted the www (i believe it was www before? I can't remember) and GitHub does the redirection getzola -> www.getzola.org

**Comment by mkroman** [comment]
I'm not sure why the CNAME file is in the `master` branch to begin with - it's only relevant for GitHub Pages.

Also, GitHub Pages can now be published with GitHub Actions without using a specific git branch: [Creating a custom GitHub Actions workflow to publish your site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site)

**Comment by doamatto** [comment]
> I'm not sure why the CNAME file is in the master branch to begin with - it's only relevant for GitHub Pages.

The docs source site (`docs/`) is in that branch and built from it into the `gh-pages` branch. You'd have to manually add the file each build since the GitHub action (workflow ?) that does it should start fresh each time (if that makes sense). It's similar to how GitHub Pages & Jekyll build.

**Comment by awakecoding** [comment]
I'm glad not to be the only one to have fallen into the getzola.org trap, only to realize only www.getzola.org works. It doesn't help that the Zola project doesn't have good SEO, so I often type getzola.org directly to find it again.

**Comment by Keats** [comment]
I need to check the setup, GH should automatically redirects so I obviously did something wrong

**Comment by Keats** [comment]
Ok it's fixed, I had forgotten to set the A records on the DNS.

**Comment by awakecoding** [comment]
Awesome, thanks for fixing it!
