### ISSUE TITLE
Do not check the same url more than once if it is the same on different pages/languages

### ISSUE THREAD

**Issue by biodranik** [Keats/gutenberg#2298]
For sites with many languages, the same URLs/links are checked many times. That delays `zola check` and unnecessarily overloads servers.

**Comment by Keats** [comment]
Weird, I thought we were doing that already.

**Comment by biodranik** [comment]
@Keats no, I've checked the code and reproduced the issue on our [zola website](https://github.com/organicmaps/organicmaps.github.io/). Please CC me in the PR, I'm interested to learn how to do it properly in Rust :)

**Comment by Keats** [comment]
I won't have time to do it myself right now but it should be easy enough to do if someone wants to try
