### ISSUE TITLE
Update `grass`

### ISSUE THREAD

**Issue by ISSOtm** [Keats/gutenberg#2310]
As of Zola 0.17.2, `grass` 0.12.3 is in use; later versions [fixed issues](https://github.com/connorskees/grass/issues/19#issuecomment-1688541494). It's possible to work around them by running `grass` (the CLI tool) manually after `zola build`, but that's much more inconvenient with e.g. `zola serve`.

Please note that I have also encountered further issues, which are *not* solved by 0.12.4, but are in 0.13.1.

I'm willing to make a PR, if desired.

**Comment by Keats** [comment]
That can be done on the next branch if it hasn't been done yet

**Comment by ISSOtm** [comment]
Looks like [that branch only bumped to 0.12.4](https://github.com/getzola/zola/blob/674c433f05780d588d716095a3c5e9129183c33f/Cargo.lock#L1280). The 0.13.0 changelog mentions one potential breaking change:

> fix various module system bugs when combined with `@import`. this is potentially breaking in rare cases where users were relying on the incorrect behavior

...but that incorrect behaviour is exactly what I am hoping to see *fixed*.

What's your stance on that?

**Comment by Keats** [comment]
we can upgrade

**Comment by ISSOtm** [comment]
Released in 0.18.0. Thanks!
