### ISSUE TITLE
Support titles from headings

### ISSUE THREAD

**Issue by EFanZh** [Keats/gutenberg#2317]
Jekyll’s [titles-from-headings](https://github.com/benbalter/jekyll-titles-from-headings) supports setting `page.title` from Markdown headings as a fallback if user does not specify `page.title` in the front matter. I am wondering if zola could support something similar.

**Comment by Keats** [comment]
This is not planned no

**Comment by EFanZh** [comment]
If someone else submits a PR to implement this feature (possibly with an option to enable or disable this behavior), will it be accepted?

**Comment by Keats** [comment]
Probably not

**Comment by EFanZh** [comment]
OK.
