### ISSUE TITLE
New Feature Idea. Automatic Translations.

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#2319]
I was about to write a node script to handle automatically translating pages into other languages: https://github.com/Jieiku/abridge/issues/149

However the API tool I am planning to use is written in rust and VERY light weight. So I am curious if such a feature would be of interest in the core Zola project?

**Comment by donovanglover** [comment]
I feel like automatic translations are better handled by a user's browser, browser extensions, and/or translation websites.

One of the main advantages of translating client-side is that users can see multiple options for a given translation.

**Comment by Jieiku** [comment]
I think certain use cases would benefit from having this, mostly just waiting on more people to weigh in, in particular @Keats, before I start work either adding it to zola or writing a node script.

**Comment by Keats** [comment]
Deepl does some ok translations but I wouldn't want that tool to be in Zola itself
