### ISSUE TITLE
Tera functions missing in shortcodes

### ISSUE THREAD

**Issue by bemyak** [Keats/gutenberg#2325]
# Bug Report

These functions, which work in templates, are `not found` when being used in shorcodes:
* get_section
* get_taxonomy
* get_taxonomy_term

## Environment

Zola version: 0.17.2

## Expected Behavior
The functions should be available both in templates and shortcodes.

## Current Behavior
When attempting to use the functions in a shortcode, zola gives an error:
```
Error: Failed to build the site
Error: Failed to render content of zola-test/content/_index.md
Error: Reason: Failed to render test shortcode
Error: Reason: Failed to render 'shortcodes/test.html'
Error: Reason: Function 'get_section' not found
```

## Step to reproduce

Try to build the attached website.
[zola-get-section-bug.zip](https://github.com/getzola/zola/files/12838302/zola-get-section-bug.zip)

**Comment by Keats** [comment]
It's documented in the last paragraph of https://www.getzola.org/documentation/content/shortcodes/#writing-a-shortcode

**Comment by bemyak** [comment]
Oh, I've missed that, thank you!

My use case is that on a page I want to list all _taxonomy terms_ from a specific section. I don't need the parsed Markdown for that. Would it be possible to somehow allow these functions with `metadata_only` option enabled?

**Comment by Keats** [comment]
I would rather avoid having some things partially working tbh, it's one thing not having some functions available, it's another having them working but only in some ways

**Comment by bemyak** [comment]
OK, that makes sense.
I'll use custom templates for every use case then.
