### ISSUE TITLE
BibTex parsing does not ignore escape sequences

### ISSUE THREAD

**Issue by algomaster99** [Keats/gutenberg#2329]
# Bug Report

## Environment

Zola version: 0.17.2

## Expected Behavior

Zola should remove escape sequences meant for LaTeX. It should print `&` instead of `\&`.

## Current Behavior

Zola prints `\&`.

## Step to reproduce

1. ```tex
    @article{balliu_challenges_2023,
	  title    = {Challenges of {Producing} {Software} {Bill} of {Materials} for {Java}},
	  issn     = {1558-4046},
	  doi      = {10.1109/MSEC.2023.3302956},
	  urldate  = {2023-09-27},
	  journal  = {IEEE Security \& Privacy},
	  author   = {Balliu, Musard and Baudry, Benoit and Bobadilla, Sofia and Ekstedt, Mathias and Monperrus, Martin and Ron, Javier and Sharma, Aman and Skoglund, Gabriel and Soto-Valero, César and Wittlinger, Martin},
	  year     = {2023},
	  note     = {Conference Name: IEEE Security & Privacy},
	  pages    = {2--13},
	  url      = {https://ieeexplore.ieee.org/document/10235318/},
	}
    ```
2. If we load its data, `{{ bibtex.bibliographies[0].tags.journal }}` evaluates to `IEEE Security \& Privacy` instead of `IEEE Security & Privacy`.

I think the expected behaviour should remove the escape sequences as they are meant for LaTeX.

**Comment by algomaster99** [comment]
On the same note, it should escape `{` and `}` in `{ ... {Producing} ... }`.

**Comment by Keats** [comment]
Does `{ bibtex.bibliographies[0].tags.journal | safe }}` work as intended?

**Comment by algomaster99** [comment]
I have not used `safe`, and it would still print the content as is. I think `load_data` should parse these LaTeX specific syntaxes into plain string. For example, `a = {Hello {World}}` should just be `"a": "Hello World"`. Right now it is `"a": "Hello {World}"`.

EDIT:
For now, I have implemented `{{ bibtex.bibliographies[0].tags.journal | replace(from="\", to="") }}` as a temporary solution.

Similarly, `{{ bibdata.tags.title | replace(from="{", to="") | replace(from="}", to="") }}`.

**Comment by Keats** [comment]
We use https://crates.io/crates/nom-bibtex to load that data. I see that we are 2 versions behind, i'll update it in the `next` branch and we can test again on there

**Comment by algomaster99** [comment]
Sounds good. If it is outdated, I can take this issue there.

**Comment by Keats** [comment]
I've updated the `next` branch, can you try?

**Comment by algomaster99** [comment]
@Keats thanks! I can definitely try it, but could you please provide the binary that I could directly run? I don't have rust and cargo ecosystem setup to build from source.

**Comment by Keats** [comment]
Can you push an example site with the issue somewhere so i can run it? It's going to be easier

**Comment by algomaster99** [comment]
Okay sure. My source code is [here](https://github.com/algomaster99/algomaster99.github.io).

`main` branch has the code where I manually remove the latex parsing. Please checkout to [`debug-bibtex-parsing`](https://github.com/algomaster99/algomaster99.github.io/tree/debug-bibtext-parsing) and `zola serve` it. Aftewards, go to `/publications/`. You will see some unescaped characters.
![image](https://github.com/getzola/zola/assets/35191225/cd89a154-80df-4d9e-a66b-916fcb5ef867)

**Comment by Keats** [comment]
I still see the same stuff in the next branch, can you check with https://github.com/charlesvdv/nom-bibtex if that's meant to be supported? I don't know anything about bibtex myself

**Comment by algomaster99** [comment]
I am really busy with stuff. I will give it a try over the weekend.

**Comment by algomaster99** [comment]
Hi @Keats. It seems that they also don't have this feature. I have [questioned them](https://github.com/charlesvdv/nom-bibtex/issues/25) about it. I may be wrong, but I am curious as LaTeX does ignore these characters when creating bibliography.

Closing the issue and will reopen based on the response from https://github.com/charlesvdv/nom-bibtex/issues/25.
