### ISSUE TITLE
No RSS feed generated at all.

### ISSUE THREAD

**Issue by Rietty** [Keats/gutenberg#2331]
# Bug Report
Doing the following in `config.toml` does not generate an RSS feed:

```
generate_feed = true
feed_filename = "rss.xml"
```

Attempted to use following in `index.html` for site:

```
    {%- if config.generate_feed %}
    {%- if "rss" in config.feed_filename %}
    {% set feed_type = 'rss+xml' %}
    {%- else %}
    {% set feed_type = 'atom+xml' %}
    {% endif -%}
    <link rel="alternate" type="application/{{ feed_type }}" title="RSS"
        href="{{ get_url(path=config.feed_filename) | safe }}">
    {% endif -%}
```

Using theme: https://github.com/pawroman/zola-theme-terminimal (I doubt it's a theme issue seems Zola isn't respecting or reading option at all.)

## Environment
Windows

Zola version: 0.17.2

## Expected Behavior
I should have an `rss.xml` in my website's source/public directory which is served/used and allows people to use `rss` to view my blog.

## Current Behavior
No `rss.xml` file is generated at all.

## Github link:
https://github.com/Rietty/Ramblings/tree/main

## Step to reproduce
Run Zola with: `.\zola.exe build`.

**Comment by c-git** [comment]
The repo you shared seem to be private I get a 404

**Comment by Rietty** [comment]
Sorry, this isn't needed anymore. I'm not sure if it was a config or a zola issue, but I moved onto Hugo and it's working well for me.

**Comment by c-git** [comment]
It may have been you had no articles with dates. But glad you got something that works for you.
