### ISSUE TITLE
Add style to text inside code-snippets

### ISSUE THREAD

**Issue by JesusValeraDev** [Keats/gutenberg#2333]
# ❓ Question

I have the `highlight_code = true`. Is it possible to add style to the text that is parsed inside the snippet code as we do in the markdown?

When the following code is written:

```php
'''php
// A comment with **bold**, __italic__ and ~~strikethrough~~
public function someFunction(string $value): void
{
    echo $value;
}
'''
```

I would like to have the result from below, the above is returned (maybe using HTML tags could be also a good idea?) 🤔

![image](https://github.com/getzola/zola/assets/6381924/c5915b7e-7699-4525-a88f-3fdfd1ed67ae)

**Comment by Keats** [comment]
That's not going to happen. We would need to parse the code as markdown which would likely break many things and be something not wanted by the majority.
