### ISSUE TITLE
Feature Request: embed last modifed in some template when `zola build` is run

### ISSUE THREAD

**Issue by algomaster99** [Keats/gutenberg#2339]
Hi! I am wondering if there is a feature to embed "last modified date" in a template (footer maybe). For ease of use, it could happen whenever we run `zola build`.

**Comment by Keats** [comment]
Pages can have a modified datetime in the front-matter. I'm not a huge fan of automatically setting it based on the file time for various reasons.

**Comment by algomaster99** [comment]
> Pages can have a modified datetime in the front-matter.

Could you tell me how to achieve this?

**Comment by Keats** [comment]
It's the `updated` field in https://www.getzola.org/documentation/content/page/#front-matter

**Comment by algomaster99** [comment]
Oh okay. I didn't know that configuration section was called "front matter" 😅 Thank you!

**Comment by algomaster99** [comment]
I used `Last updated on: {{ now() | date(format="%d %B %Y") }}` in my main page and footer to get the last updated date. See implementation here - https://algomaster99.github.io/
