### ISSUE TITLE
Document RSS Feed Author

### ISSUE THREAD

**Issue by c-git** [Keats/gutenberg#2341]
# Documentation issue

## Summary
> What is the issue? Is the documentation unclear? Is it missing information?

I'm trying to set the author in the rss feed and the can't seem to find how to do it in the documentation. 

## Proposed solution

> A quick explanation of what you would like to see to solve the issue.
> If you want to add content, please explain what you were looking for 
> and what was your process while looking at the current documentation.

I'd like to see the steps required to set the author documented and easy to find.

I checked the page documenting [feeds](https://www.getzola.org/documentation/templates/feeds/) and didn't find it. Then I did a search on the documentation using the search at the top for the word "author" but only turned up results that appear to be for themes. Thus I came to the conclusion this is not documented yet.

At this point I'm mostly checking if that is the case before I try to create a PR to document it. Of corse if it does already exist please pardon my ignorance and point me in the right direction.

I am lead to believe that it does exist due to this [issue](https://github.com/getzola/zola/issues/2024) and this [PR](https://github.com/getzola/zola/pull/2092) and observing that the author is set to Unknown in the currently output feed and not empty.

I think if it goes in the extra section of the `config` and `front matter` then those would be the best places to document it by showing it with the default value and a comment explaining what it is (Like the rest of the documentation). And then a mention of it on the feed page. Possibly with a short summary, while the repetition would make it easier to find, it would cause more work to update if it changes in the future as more places would need to be updated, leading to possibly inconsistent documentation.

If it should be or is documented somewhere else please let me know.

**Comment by Keats** [comment]
It should be documented yes. it looks ups in order: front-matter, config or default to unknown

**Comment by c-git** [comment]
Thanks going to give it a try now. Cuz was just going to update my site.

**Comment by c-git** [comment]
Turns out it is already documented for the [front matter](https://github.com/getzola/zola/blob/152eccc44751d070ae34b2805e7fa85a06c3667c/docs/content/documentation/content/page.md?plain=1#L131) but I guess this is not included in the search index I didn't see it in the results. Have to run now will finish later this evening hopefully.

**Comment by c-git** [comment]
Documentation merged
