### ISSUE TITLE
Feature Request: mdbook-like file including

### ISSUE THREAD

**Issue by ghost** [Keats/gutenberg#2346]
Thank you for making  such a nice static site generator.

I want to create a web page including many program codes. It is useful to be able to include code in a markdown file, such as mdbook.

see mdbook doc: https://rust-lang.github.io/mdBook/format/mdbook.html#including-files

**Comment by Keats** [comment]
You can probably get by with the load_data function and a markdown shortcode that puts the loaded file in a code block

**Comment by ghost** [comment]
Is there a feature corresponding to `ANCHOR` and `ANCHOR_END` in mdbook?

see mdbook doc: https://rust-lang.github.io/mdBook/format/mdbook.html#including-portions-of-a-file

**Comment by Keats** [comment]
There's no anchor system in Zola but you can select specific lines to hide: https://www.getzola.org/documentation/content/syntax-highlighting/#annotations
