### ISSUE TITLE
False negative with anchor checking

### ISSUE THREAD

**Issue by c-git** [Keats/gutenberg#2351]
# Bug Report

## Environment

Zola version: `zola 0.17.2`

## Expected Behaviour

Zola check should have successfully completed.

## Current Behaviour

Zola sometimes tells me that the link is broken (anchor not found). I don't think it's due to any change in zola but rather with the site. What I wanted to know is if it was easy to see what zola got back when it requested the site.

## Step to reproduce

1. Create a site that includes a link to <https://rust-lang.github.io/rustfmt/#comment_width>
2. Run `zola check`

Error message:
```
Error: Failed to check the site
Error: Found 1 broken external link(s)
  1. Broken link in /home/one/c-git.github.io/content/rust/rustfmt.md to https://rust-lang.github.io/rustfmt/#comment_width: Anchor `#comment_width` not found on page
```

**Comment by c-git** [comment]
Didn't noticed you'd tagged it with bug. In case I get a chance to take a look before someone else (not likely to be in the near future as this isn't a big deal for me and I have other stuff in zola I want to work on).

 would most likely add some debugging output to check. I'd need to do that to understand how it works. Would you be ok with me adding a flag to expose that to normal users who might be having problems?

**Comment by Keats** [comment]
I don't think it would make sense for that. It's probably an issue in https://github.com/getzola/zola/blob/master/components/utils/src/anchors.rs#L4 or https://github.com/getzola/zola/blob/master/components/link_checker/src/lib.rs#L107 so it would be easy to test manually

**Comment by c-git** [comment]
Ok no problem thanks for posting places to start looking. If I try to work on this that will help.

**Comment by Keats** [comment]
Ah so it's a Vue site and we get the content before it actually executes >_>

**Comment by c-git** [comment]
I see thank you for checking it. I wouldn't worry about it then, I'll just add a skip in the config.
