### ISSUE TITLE
Zola package Not Found on Flathub web page

### ISSUE THREAD

**Issue by aplatypus** [Keats/gutenberg#2352]
# Bug Report

## Environment

Kubuntu 23.04

Zola version:
zola 0.17.2

## Expected Behavior

I was following the installation information on:

* [Installation](https://www.getzola.org/documentation/getting-started/installation/): `https://www.getzola.org/documentation/getting-started/installation/`

and saw the Flatpak option.  This is now my prefered avenue to load 'recent' packages.

I went to Flathub web site to find the Zola package  -- I like to check the notes, etc. before I install a flatpak.

I was able to install from command line as per the web page.  
```
$ flatpak install flathub zola
```

However if you want to promote Zola it would be good to be availale on the flathub search.

## Current Behavior

On the flathub web page, I had no luck.

* [search: zola](https://flathub.org/en-GB/apps/search?q=zola)
  * No results for Zola --  Zola not found.
  * I tried a variety of alternatives: getzola, zolarweb, etc.
  
None found.  

Then I went to the command line, and typed a search /match for zola as above.

```
flatpak install flathub zola
Looking for matches…

org.getzola.zola permissions:
    network   file access [1]

    [1] host

        ID                       Branch         Op         Remote          Download
 1.     org.getzola.zola         stable         i          flathub         < 9.6 MB

Proceed with these changes to the system installation? [Y/n]:  Y
```

As you see the package is there.  However it does NOT come-up on the new Flathub website.  

May be something changed with the latest remodelling???

## Step to reproduce

* [search: zola](https://flathub.org/en-GB/apps/search?q=zola)
  * No results.  Zola not found.
  * I tried a variety of alternatives: getzola, zolarweb, etc.
  
None found.  

Then I went to the command line, and typed a search /match for zola:

```
$ flatpak install flathub zola
Looking for matches…

org.getzola.zola permissions:
    network   file access [1]

    [1] host

        ID                       Branch         Op         Remote          Download
 1.     org.getzola.zola         stable         i          flathub         < 9.6 MB

Proceed with these changes to the system installation? [Y/n]:  Y
```

As you see the package is there.  However it does NOT come-up on the new Flathub website.  

May be something changed with the latest remodelling???

**Comment by daudix** [comment]
Zola is a CLI app, such apps don't appear in Flathub web search

**Comment by Sama-004** [comment]
Which distro are you using?

**Comment by aplatypus** [comment]
That is very dissappointing -- How may a person _discover_ coold stuff if there's a anti-CLI bias on `Flathub`?
 * _Alternately_ may be it should be called `GUI-hub` to be more honest about the purpose of the site?

I like that; then we may coin:

* `CLI-hub` for command line things,
* `TUI-hub` for NCurses type stuff,  and 
* `Svc-hub` for services and servers, etc.

Just for my 2-cents; that more complexity  than having something like a "**Category**" for such things.  Looking ahead there will soon be need for something like: "_LLM-hub_" and all kinds of other stuff.

_"You can't stop the signal", you can only rage agains the_ Tempest.
