### ISSUE TITLE
Do endblocks have to be named explicitly?

### ISSUE THREAD

**Issue by 3tilley** [Keats/gutenberg#2355]
# Documentation issue

## Summary
Sometimes I see
```
{% block my_block %}
foo
{% endblock foo %}
```

and sometimes I see
```
{% block my_block %}
bar
{% endblock %}
```

Does the templating engine care? Is one better practice than the other? It would be great to mention this in the docs either way

**Comment by Keats** [comment]
The engine currently doesn't care about the endblock naming, it's only for you. It will probably become an error in v2 if they are mismatched though

**Comment by 3tilley** [comment]
Thanks! I'll open a documentation PR to note some of the things I found using Zola for the first time
