### ISSUE TITLE
Error when building without pushing the templates folder

### ISSUE THREAD

**Issue by T3kla** [Keats/gutenberg#2357]
# Bug Report

## Environment

Zola version: 0.17.2

## Expected Behavior
When using `zola build` the site should build.

## Current Behavior
It won't build the site.
```
Building site...
Error: Failed to build the site
Error: Error parsing templates from the /templates directory
Error: Reason: Io error while writing rendered value to output: NotFound
Error: Reason: The system cannot find the file specified. (os error 2)
```
(I have no idea how to add RUST_BACKTRACE=1 when running a zola command btw.)

## Step to reproduce
- Create a new zola project
- Follow the GitHub Pages guide
- Don't have anything in the templates folder, so it never gets pushed to the repo
- Have the GitHub action fail

## References
This issue in the Tera repo explains the issue.
https://github.com/Keats/tera/issues/819#issuecomment-1807338111

**Comment by Keats** [comment]
I believe it's already fixed in the next branch but i'll double check

**Comment by Keats** [comment]
Yep that seems to be fixed already

**Comment by okin** [comment]
I've been seeing the same in CI builds.

Is there an ETA for a new release with that fix?

**Comment by Keats** [comment]
Soonish I think? I'd like to get some more PRs/bugs merged

**Comment by camilasan** [comment]
I have the same problem but on Gitlab.

```
(3/3) Installing zola (0.17.2-r3)
Executing busybox-1.36.1-r5.trigger
OK: 22 MiB in 18 packages
$ zola build
Building site...
Error: Failed to build the site
Error: Error parsing templates from the /templates directory
Error: Reason: Io error while writing rendered value to output: NotFound
Error: Reason: No such file or directory (os error 2)
```
