### ISSUE TITLE
Is it blazing and fast?

### ISSUE THREAD

**Issue by GildedHonour** [Keats/gutenberg#2358]
"Blazing fast" isn't a thing.

Alternatives :
* blazing **and** fast
* blazing **,** fast
* blazing**ly** fast

![Screenshot_20231114_143239](https://github.com/getzola/zola/assets/2032888/21bc013b-9b45-4ba0-979a-fbe86702921a)

**Comment by Keats** [comment]
It seems that blazing fast can be used? https://english.stackexchange.com/questions/139316/what-is-correct-blazing-fast-speed-or-blazingly-fast-speed

**Comment by GildedHonour** [comment]
If you speak on the fucked american english - yes.
