### ISSUE TITLE
Allow loading front matter in templates

### ISSUE THREAD

**Issue by clarfonthey** [Keats/gutenberg#2379]
# Documentation issue

## Summary
Right now, it's not easy to parse out the front matter from markdown files in templates.

We have the `load_data` function for loading TOML and YAML, and we have the `markdown` filter for rendering markdown. But it's not very easy to combine these two without a lot of boilerplate.

Additionally, since `Tera` does not let you make your own objects, you can't easily make macros to do this in one step. It would have to be done via a Rust-written function instead.

## Proposed solution
After experimenting with the code, it seems relatively easy to add an `md` format to `load_data`, which can parse out the front matter and render the markdown for a file.

A few other alternatives which I don't like as much, but are worth mentioning:

* Adding the ability to read front matter from the `markdown` function: this seems less ideal because that function is often used solely for rendering, and having the option for it to output an object instead of a string feels counter-intuitive.
* Adding the ability to separately split the front matter from a file in a separate function would be more awkward because of the way Tera macros work. In general, the only cases where you'll have front matter are when you're loading files directly; if we couldn't just do it alongside the load, we'd have to first load the file as plain text, then split the front matter, then parse the front matter, then render the markdown.
* Since the front matter should be passed to `load_data` *anyway* to convert it from TOML/YAML, it makes the most sense that this function would be parsing the front matter anyway.

I do have a branch showing off this solution because I wanted to be able to use it myself, but I wanted to actually file an issue to propose a proper, mergeable solution for this.

**Comment by Keats** [comment]
What's the usecase there? We are already serializing the front-matter

**Comment by clarfonthey** [comment]
Basically, the idea is to offer a way to get around some of the restrictions on hidden pages by offering a way to load a "page" in a limited capacity from an external file. Not the full parsing of a page, just the ability to parse the front matter correctly.

Right now I'm trying to switch from an existing jank, custom setup to using zola for generating my website, and one of the existing pages under that jank setup is my CV, which is made up of a bunch of sections that could be all included in one massive page file, but would probably be easier if split up. It would be nice to be able to colocate the metadata (front matter) in the files instead of having to load two files each time, and when I tried to make a macro for it, it didn't really work out well.

The thought is, adding proper ways to have "hidden" or "internal" pages seems way out of scope, but adding in a method to parse the front matter in templates feels like an okay compromise. It would also let you separate out some content pages into multiple files without having to create dedicated pages for them, since you could embed those parts using shortcodes.

**Comment by Keats** [comment]
> The thought is, adding proper ways to have "hidden" or "internal" pages seems way out of scope, 

We do have `render = false` on sections currently exactly for that purpose

**Comment by clarfonthey** [comment]
Oh, I totally missed that, then. There isn't a `render = false` option for pages but I guess that making a page into a "section" that isn't rendered would probably work fine.

EDIT: Hmm, running off of master, it still seems to render `index.html` for sections even if I have `render = false` in their `_index.md` files. I'm not 100% sure how this is supposed to work, but at minimum the docs really aren't that clear.

**Comment by Keats** [comment]
Yeah it's lacking in `page` right now.

Can you share an example? In the code, the template rendering is after the `render` check so it shouldn't happen

**Comment by clarfonthey** [comment]
I don't want to share my existing example because it's a mess, but I'll try to create a minimally reproducible version since it'll probably help resolve the confusion. I tried looking into the code but I didn't quite understand the one if statement that seems to be branching on this flag, and whether it would be enough to fully stop the rendering. I'd have to understand more about the code structure to really know if it's working properly.

EDIT: Okay, I see the issue. I thought I had cleaned the `public` folder multiple times after setting `render = false` but I actually hadn't, and it is working properly.

The only bug I can see is that it's still generating empty folders, which I guess isn't the worst, but maybe I'll look into the code later how it can be done. I'll also try and see if I can implement a version of `render = false` for pages, since that seems like the best path forward.

**Comment by darrenmeehan** [comment]
I don't understand the problem you're facing @clarfonthey , once data is under "extra" inside the front matter it's only a matter of accessing it at "page.extra.foo".

What I am struggling with it getting the data inside extra. As I'm using Decap CMS. 

I'm likely totally missing what you're trying to do, apologies if I'm talking across ye!

**Comment by clarfonthey** [comment]
Yeah, my issue was that I couldn't make pages without them actually showing up as pages in the index, in the sitemap, etc.

But that seems like it's going to get fixed, so, I should really just close this.
