### ISSUE TITLE
Add OPDS Support to Zola

### ISSUE THREAD

**Issue by digitalethics** [Keats/gutenberg#2383]
Integrating [OPDS](https://opds.io/) support into Zola enhances content distribution, making it accessible to a wider audience through various e-book readers and applications. This addition ensures interoperability, improves the user experience, and aligns Zola with evolving standards in digital publishing. Enabling OPDS support also facilitates seamless integration into existing communities and ecosystems, making Zola a more versatile and future-proof static site generator.

**Comment by narasimha-1511** [comment]
i  want to work on this issue??

**Comment by Keats** [comment]
I don't think we want to add that. It looks dead: last message on the board from 2019, various links I've tried just 404 and can't find much about it on internet.
