### ISSUE TITLE
Docker image for 0.18.0 is broken

### ISSUE THREAD

**Issue by dansondergaard** [Keats/gutenberg#2385]
# Bug Report

## Environment

Zola version: 0.18.0

## Expected Behavior

The Docker image should build without failure.

## Current Behavior

The Docker image fails to build with "GLIBC not found" errors.

## Step to reproduce

My Dockerfile looks like this:

```
FROM ghcr.io/getzola/zola:v0.18.0 AS builder
WORKDIR /app
COPY . .
RUN ["zola", "build"]
```

When building it with:

```
docker build -t foo/foo .
```

It fails with:

```
 => ERROR [builder 4/4] RUN ["zola", "build"]                                                  0.2s
------
 > [builder 4/4] RUN ["zola", "build"]:
0.188 zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by zola)
0.188 zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by zola)
0.188 zola: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by zola)
```

**Comment by Keats** [comment]
That's weird. If someone has bandwitdh, can they look at that? I won't have time for a while

**Comment by thomasweitzel** [comment]
I have the same problem with `ghcr.io/getzola/zola:v0.18.0`: the `/bin/zola` seems to need one of the GLIBC versions mentioned. If the image uses the version on my system (Ubuntu 22.04 LTS), I have a different version.

 ```
thomy@tower:~/Downloads$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.5) 2.35
```

Is it possible to use MUSL in place of GLIBC for Zola in the Docker image for future versions instead?

**Comment by oleastre** [comment]
I suspect there is a difference between the rust image used to build and the distroless/cc one used as runtime.
Latest rust image is based on Debian 12 while the distroless/cc one is based on Debian 11.
I'm trying to reproduce locally to see if I can come with a PR.

**Comment by dansondergaard** [comment]
Thanks a lot for the super fast response! Will the updated Docker image be pushed soon or only when a new version is released? Only asking so I can build a workaround if it takes a while.

**Comment by Keats** [comment]
I need to see how to delete the tagged image and rebuild/push it. Not sure how to do that yet, if someone knows I can do it quickly otherwise that will depend on when I get the time

**Comment by oleastre** [comment]
Since your images are built with github actions, I suppose the easiest is to either move the `0.18.0` tag after the merge of #2386 or tag a new release as 0.18.1 for the fix to be picked by the action.

**Comment by Keats** [comment]
Yeah I wanted to avoid that since it will re-trigger a build for everything else as well

**Comment by Keats** [comment]
Updated in theory, can you try it?

**Comment by dansondergaard** [comment]
Works perfectly! Thanks a lot!
