### ISSUE TITLE
zola check: checking vs checked link number does not match

### ISSUE THREAD

**Issue by Raymi306** [Keats/gutenberg#2412]
# Bug Report
```
Checking 18 external link(s). Skipping 0 external link(s).
> Checked 19 external link(s): 0 error(s) found.
```

## Environment

Zola version: 0.18

## Expected Behavior

I'd think that the numbers ought to be the same.  
As an aside and reminder for myself to explore later, it also seems to take a bit longer than I would expect, I wrote an async link checker in Python that typically checked many more links in the time Zola took.

## Current Behavior

18 != 19

## Step to reproduce

I can provide my repo at a later date, I am actively overhauling things and just noticed this and thought I'd ask if it was expected

**Comment by Keats** [comment]
That is weird.

**Comment by yhoiseth** [comment]
Tried on my own with 0.18.0:

```
yngve@UT-C0D3E-027 zola-website % zola check
Checking site...
Checking all internal links with anchors.
> Successfully checked 15 internal link(s) with anchors.
Checking 102 external link(s). Skipping 0 external link(s).
> Checked 122 external link(s): 18 error(s) found.
Error: Failed to check the site
Error: Found 18 broken external link(s)
  1. Broken link in…
```

**Comment by amtanq** [comment]
I can pick this up if it's still available

**Comment by ta-nishq** [comment]
Raised a fix: https://github.com/getzola/zola/pull/2472
