### ISSUE TITLE
How to use sort_by to Sort taxonomies in taxonomy_list.html？

### ISSUE THREAD

**Issue by kcrazy** [Keats/gutenberg#2415]
I am trying to figure out how to apply sorting to taxonomies in taxonomy_list.html similar to the method used in content/_index.md. In _index.md, we use the following syntax:

```
sort_by = "date"
paginate_reversed = true
```

I want to achieve a similar sorting mechanism for taxonomies, specifically on the tags page. Could you please provide guidance on how to use sort_by in taxonomy_list.html for taxonomies?

**Comment by Keats** [comment]
There's no way to sort taxonomies currently, they are just sorted by slug. If you don't need pagination, you might be able to do it in the templates?

**Comment by kcrazy** [comment]
Thank you for your response.

 If I don't need pagination, how can I implement sorting by time order in the template?

**Comment by Keats** [comment]
You can try to use https://keats.github.io/tera/docs/#sort

**Comment by kcrazy** [comment]
This is my single.html code, 
templates/tags/single.html:
```html
{% import "macros/page.html" as page_macros %}
{% extends "index.html" %}

{% block title %}{{ term.name }}{% endblock title%}

{% block content %}
<h1>Tags: #{{ term.name }}</h1>
<div class="article-info">
    <a href="{{ get_url(path="/tags") }}">All Tags</a>
</div>

{% for page in term.pages %}
{{ page_macros::page_listing(page=page) }}
{% endfor %}

{% endblock content %}
```
and it seems that the term corresponds to the Rust structure TaxonomyTerm. 
```rust
#[derive(Debug, Clone)]
pub struct TaxonomyTerm {
    pub name: String,
    pub slug: String,
    pub path: String,
    pub permalink: String,
    pub pages: Vec<PathBuf>,
}
```
How should I sort it in chronological order?
I'm not quite familiar with the documentation on Tera sorting. 

Thanks a lot.

**Comment by Keats** [comment]
> How should I sort it in chronological order?

Taxonomy terms have no date concept, how would that work? Do you want to sort it based on the pages inside?

**Comment by kcrazy** [comment]
I understand what you mean now, 

my single.html should be written like this
```
{% import "macros/page.html" as page_macros %}
{% extends "index.html" %}

{% block title %}{{ term.name }}{% endblock title%}

{% block content %}
<h1>Tags: #{{ term.name }}</h1>
<div class="article-info">
    <a href="{{ get_url(path="/tags") }}">All Tags</a>
</div>

{% for page in term.pages | sort(attribute="date") %}
{{ page_macros::page_listing(page=page) }}
{% endfor %}

{% endblock content %}
```

Thank you so much.
