### ISSUE TITLE
support treating standalone .html files as pages

### ISSUE THREAD

**Issue by jyn514** [Keats/gutenberg#2420]
my site has several pages that are HTML and not markdown; mostly reveal.js slides. i want them to be displayed using the same template i use for my normal markdown posts. i tried the following layout:
```
; tree content/talks
content/talks
├── assembly.html
├── async-await.html
├── bootstrapping.html
├── C.html
├── _index.md
```
with the following content in `_index.md`:
```
+++
title = "talks"
sort_by = "date"
template = "home.html"
page_template = "page.html"
+++
```
my template is
```
  <ul class="post-list">
    {% for post in section.pages %}
      <li>
        <!-- various html -->
      </li>
    {% endfor %}
  </ul>
```
which works fine on my homepage. but for this subsection, it just shows an empty `<ul class="post-list></ul>`.

---

i think what's going on is zola *only* treats markdown files as pages. but i want it to include HTML as well. is there a way to configure it to do so? if not, could it be added?

**Comment by jyn514** [comment]
oh, i think i see what's going on - these are put in a separate `assets` variable, not in `pages`. i suppose that works.

**Comment by jyn514** [comment]
ah no, but that doesn't allow me to configure the post date with front-matter. i have to hard-code the dates in the template, or include it in the filename (which changes the URL, so i'd rather not do that).

**Comment by Keats** [comment]
It's not going to be supported as is but you can create a markdown file with a custom `template` attribute where the HTML will be

**Comment by jyn514** [comment]
that worked, thank you! it means i have to move the html files out of content/ to templates/, but i can live with that.
