### ISSUE TITLE
Incorrect Plist syntax: UnexpectedXmlCharactersExpectedElement (offset 56)

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [Keats/gutenberg#2427]
# Bug Report
I am migrating from Linux to Windows. Before migrating, my Zola website was working. After migrating to Windows 11, pulling from GitHub and running `zola serve`, I got the following error: 
```
Error: Failed to serve the site
Error: Invalid syntax theme settings
Error: Reason: Incorrect Plist syntax: UnexpectedXmlCharactersExpectedElement (offset 56)
```
I am sorry that I can't provide more details: the error is so vague I have no idea where to even start looking.

## Environment

Zola version: 0.18.0

## Expected Behavior
Tell us what should have happened.

## Step to reproduce
For now, the most specific report I can give is:

1. Pull my blog: https://github.com/TeaDrinkingProgrammer/TeaDrinkingProgrammer.github.io
2. run `zola serve` in the root folder.
3. The error should appear.

**Comment by Keats** [comment]
Looks like it would be the custom highlight themes not working? Can you comment https://github.com/TeaDrinkingProgrammer/TeaDrinkingProgrammer.github.io/blob/main/config.toml#L77-L81 and see if it works?

**Comment by TeaDrinkingProgrammer** [comment]
I have found the problem: I pushed my Linux symlinks on git and used them on Windows. That doesn't work, of course. I fixed the issue by making Windows symlinks. Thank you for sending me to the right direction.
