### ISSUE TITLE
Excerpt separator not compatible with Hugo (or Jekyll), is `<!-- more -->` rather than `<!--more-->`

### ISSUE THREAD

**Issue by bobhy** [Keats/gutenberg#2431]
Discovered this migrating my blog content from Hugo to Zola.  
I think the cause is here:
https://github.com/getzola/zola/blob/cec01e6f48738bac78a5ecc812333aa7db1d861e/components/markdown/src/markdown.rs#L487-L501

The migration fix was a single, global search-and-replace over my content, but it was an obstacle to migration in my case.

**Comment by bobhy** [comment]
I didn't submit a PR because I'm not sure what the fix should be:
* simply change the string to `<!--more-->` and document a breaking change for all Zola sites.
* add a second test and take the runtime perf hit (small, but annoying).  
* make the excerpt_separator a configuration setting with the default being the industry-standard `<!--more-->` and document the breaking change (and what to do about it) for all Zola sites.

The third option limits the pain of the breaking change to the current Zola community and gives those sites a migration path to the more industry-standard content syntax.

**Comment by Keats** [comment]
https://github.com/getzola/zola/pull/2382/commits/682447ee73fb858be3b9fbb73ff0a372b9e4af58 is already in the next branch so that will work in the next release
