### ISSUE TITLE
get_url generates http url during serve, even though base_url defines https

### ISSUE THREAD

**Issue by InDieTasten** [Keats/gutenberg#2434]
# Bug Report

## Environment

Zola version:
0.17.2

## Expected Behavior
get_url() uses the base_url protocol to build urls

## Current Behavior
get_url() always uses http schema to build urls

## Step to reproduce
Use a template with get_url function such as

```html
<link rel="stylesheet" href="{{ get_url(path="site.css", trailing_slash=false) | safe }}">
```

When running zola **serve** like

```
zola serve -u local-1111.dev --no-port-append
```
with the following base url in config.toml:
```toml
base_url = "https://local-1111.dev"
```

it generates html like this:
```html
<link rel="stylesheet" href="http://local-1111.dev/site.css">
```

The reason I want to use serve with https is that I'm using GitHub Codespaces, which automatically creates a secure HTTPS tunnel to any ports opened by zola.

So I get the index page using https://local-1111.dev, but inside the returned HTML it references http://local-1111.dev, which causes mixed content errors and fails loading the stylesheet.

When using the same template and using `zola build`, it generates https urls properly. However, there is no watch mode for build, so using another webserver for serving is really really inconvenient.

**Comment by InDieTasten** [comment]
I think one way to support https would be to allow for specifying the protocol schema inside the `-u` option. Currently, when specifying `-u https://local-1111.dev` it generates `http://https://local-1111.dev`. If instead it would recognize there is already a protocol specified and using that to set the base_url for the url generation, this particular problem would be solved.

**Comment by Keats** [comment]
> get_url() always uses http schema to build urls

It's more that we replace the base_url in serve. I think what you're proposing is fine?

**Comment by InDieTasten** [comment]
I guess this isn't so much a bug, and more like intended behavior until support for tls terminating reverse proxies / tunneling in front of zola serve is officiallly supported. Tracking for this continues at #2435
