### ISSUE TITLE
Search question: is it possible to set search weight per page

### ISSUE THREAD

**Issue by just1602** [Keats/gutenberg#2439]
Hello,

I'm creating a documentation website for a small collective, and some people would like to be able to add some weight for some specific page in the search index to avoid some noise in the search result.

Is it possible to set some variable in the page metadata that the search index generation algo could use to set some weight?

PS: @Keats I saw in another issue that you want to refactor the documentation using the [Diataxis](https://diataxis.fr/). I really like the idea, this is what I'm trying to do with this little documentation site project.

**Comment by Keats** [comment]
I don't think the library we use for the search supports weights.
