### ISSUE TITLE
Content from theme is not loaded?

### ISSUE THREAD

**Issue by piavgh** [Keats/gutenberg#2442]
# Bug Report

## Environment

Zola version: 0.18.0

## Expected Behavior
Tell us what should have happened.
The `content` folder from the theme should be applied automatically (pages/blog should show up). It helps someone who wants to try Zola to start quickly

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace. You can get the
stacktrace of a panic by adding `RUST_BACKTRACE=1` when running a `zola` command.
At the moment, content from the theme is not applied
I tried with some themes:
- https://www.getzola.org/themes/anemone/
- https://www.getzola.org/themes/solar-theme-zola/
- https://www.getzola.org/themes/zola-theme-terminimal/

All have the same issue, though they have some pages in their `content`, none shows up

## Step to reproduce
Please provide the steps to reproduce the issue.
If the issue is hard to reproduce, please provide a sample repository or sample
that triggers the bug.

1. Init a new project: `zola init myblog`
2. Follow the instruction here: https://www.getzola.org/documentation/themes/installing-and-using-themes/

**Comment by Keats** [comment]
That's not a bug report.

I don't think it should show the content personally.

**Comment by piavgh** [comment]
> That's not a bug report.
> 
> I don't think it should show the content personally.

So I think at least in the Themes section in Zola documentation, it should state that only the content folder in the theme will not be applied, and we have to manually copy it into the main repo content folder in order to make it looks like the demo, right?

**Comment by Keats** [comment]
Well ideally the themes has instructions on the content structure so you can just create new files rather than copying the content dir

**Comment by piavgh** [comment]
> Well ideally the themes has instructions on the content structure so you can just create new files rather than copying the content dir

Thank you, so please help me to confirm this:
In every theme, the content folder will not be applied, only the `templates`, `static`, ... folders will be modified, and it's how Zola works for all themes, right?

**Comment by Keats** [comment]
Exactly. Since often you already have content

**Comment by hakon3** [comment]
Useful information to have somewhere. Confusing.

**Comment by asimpletune** [comment]
I just want to point out that as of this moment the [Zola site](https://www.getzola.org/documentation/themes/overview/#:~:text=As%20such%2C%20themes%20are%20Zola%20projects%20which%20provide%20their%20own%20templates%2C%20content%20and%20even%20static%20assets.) still has kind of confusing language around this:

> As such, themes are Zola projects which provide their own templates, content and even static assets.

**Comment by Keats** [comment]
Hm we do want to remove content from that sentence
