### ISSUE TITLE
[Question] Disable trailing slash for `.permalink`?

### ISSUE THREAD

**Issue by mangkoran** [Keats/gutenberg#2457]
I noticed that `.permalink` (page, but also applies to section) is set with trailing slash. While it has no issue, I feel that it looks a bit weird to have a single page with no child has a trailing slash.

![image](https://github.com/getzola/zola/assets/57625126/92358db2-0220-4e1c-9f72-98ff26ad38fe)

I noticed that page link without trailing slash is also works. So is there any way I can disable/remove trailing slash from `.permalink`?

Related (or even duplicate) with https://zola.discourse.group/t/config-option-for-trailing-slashes/2071

**Comment by Keats** [comment]
Nope there's no option to do it and there won't be

**Comment by mangkoran** [comment]
Alright thank you for your reply. I just would like to say thanks for developing Zola. It helps me to start blogging. Have a good day!

**Comment by zhangshine** [comment]
A simple workaround, `{{ page.permalink | trim_end_matches(pat='/') | safe }}`. The only exception is the home path `/`.

https://keats.github.io/tera/docs/#trim-end-matches

**Comment by mangkoran** [comment]
@zhangshine Thank you for your suggestions! It seems it's possible afterall 😁
