### ISSUE TITLE
In Zola templates that extend another template, variables declared at top-level are not available in blocks

### ISSUE THREAD

**Issue by LunarEclipse363** [Keats/gutenberg#2485]
# Bug Report

## Environment
Zola version: `0.18.0`

## Current Behavior
In templates that extend another template, variables declared at top-level are not available in blocks.

## Expected Behavior
Variables declared at top-level should be available in blocks.

### File contents
In `config.toml`:
```toml
base_url = "https://example.com"
```
In `templates/base.html`:
```htmldjango
{% block content %}
{% endblock content %}
```
In `templates/index.html`:
```htmldjango
{% extends "base.html" %}

{% set        test = "Hello World!" %}
{% set_global foo  = "bar" %}

{% block content -%}
{{ test | default(value = "test is undefined") }}
{{ foo  | default(value = "foo is undefined") }}
{%- endblock content %}
```
### Resulting output
This results in `zola build` generating the following `public/index.html` file:
```
test is undefined
foo is undefined
```
### Expected output
I would expect the `public/index.html` file to instead contain:
```
Hello World!
bar
```

**Comment by Keats** [comment]
Yeah that's as expected.
When a template is extending another, anything outside of blocks is ignored since it's not part of the rendering. Move it inside a block to have it work.

**Comment by LunarEclipse363** [comment]
I see, that's somewhat inconvenient.

If anyone else runs into this, as a workaround you can add an empty block for variables at the start of the parent template, then add that block in the child template and declare the variables there, they will be available in all other blocks.
