### ISSUE TITLE
How do I get a relative link to a page?

### ISSUE THREAD

**Issue by VidhuKant** [Keats/gutenberg#2489]
I followed the "getting started" section of the documentation and created a blog and a blog-list template which shows all the posts. Now all the links on the list page are permanent i.e they all start with my website's base URL.

With Hugo I can use RelPermalink to get a relative link which I actually need for my website, as I also have it on TOR and a permanent link would always link to the clearnet site, which I don't want! Is there any *easy* way to get this in zola?

**Comment by mwcz** [comment]
You can set the following in your `config.toml`:

```toml
base_url = "/"
```

It will achieve what you want, but it can definitely have side effects for certain themes.  For instance, if you have opengraph meta tags, you could wind up with:

```html
<meta property="og:url" content="/" />
```

**Comment by VidhuKant** [comment]
Umm I think I didn't search enough...
I got what I wanted with the page.path variable listed here: https://www.getzola.org/documentation/templates/pages-sections/#page-variables

Thank you for your response!

**Comment by VidhuKant** [comment]
I think I solved this issue myself; but really appreciate the support! Thank you
