### ISSUE TITLE
Suggestion: compress_sass_output config option

### ISSUE THREAD

**Issue by xpe** [Keats/gutenberg#2491]
Hello @Keats (and other maintainers?),

## Request

Would you be open to a PR such that the [grass] `OutputStyle` could be configured via Zola?

[grass]: https://github.com/connorskees/grass

### specific Zola code

Here is one line of code that I would like to surface as a configuration option from [/components/site/src/sass.rs][1]:

```rs
let options = Options::default().style(OutputStyle::Compressed);
```

[1]: https://github.com/getzola/zola/blob/b93640851eab8db6cc0f47419e050df2c762f3c4/components/site/src/sass.rs#L21

### grass config options structs

From grass: [/crates/compiler/src/options.rs][2]:

```rs
/// Configuration for Sass compilation
///
/// The simplest usage is `grass::Options::default()`; however, a builder pattern
/// is also exposed to offer more control.
#[derive(Debug)]
pub struct Options<'a> {
    pub(crate) fs: &'a dyn Fs,
    pub(crate) style: OutputStyle,
    pub(crate) load_paths: Vec<PathBuf>,
    pub(crate) allows_charset: bool,
    pub(crate) unicode_error_messages: bool,
    pub(crate) quiet: bool,
    pub(crate) input_syntax: Option<InputSyntax>,
    pub(crate) custom_fns: HashMap<String, Builtin>,
}
```

```rs
pub enum OutputStyle {
    /// This mode writes each selector and declaration on its own line.
    ///
    /// This is the default output.
    Expanded,

    /// Ideal for release builds, this mode removes as many extra characters as
    /// possible and writes the entire stylesheet on a single line.
    Compressed,
}
```

[2]: https://github.com/connorskees/grass/blob/0.13.0/crates/compiler/src/options.rs#L13

### proposed Zola configuration item

```toml
compress_sass_output = true # default
```

or, the alternative, which is why I'm requesting this:

```toml
compress_sass_output = false
```

**Comment by xpe** [comment]
I just hand-tested my potential PR (from my fork) for my personal website; works fine. If you like this, please let me know what tests you'd like to see. I can also write some docs.

**Comment by Keats** [comment]
I don't really see the point tbh, browsers can prettify it already automatically if you need.

**Comment by xpe** [comment]
@Keats I can see why you might say that, but it isn't exclusively about pretty-printing. The current default, `OutputStyle::Compressed`, strips out comments. This makes `OutputStyle::Expanded` handy sometimes for debugging.

Aside: I looked at [grass] today. I can tell it is a lot of work to maintain feature-parity with dart-sass. I just contributed a PR over there, adding `string:split` which is currently missing. I mention this to motivate that having more control over [grass]'s [config options][1] is helpful. One of my goto strategies when things go wrong is "get more visibility". Having one tools' config buried inside another can be a barrier, and it was here in this case, which I why I made the PR.

[grass]: https://github.com/connorskees/grass

[1]: https://github.com/connorskees/grass/blob/c887e17e2e7633efea38d26625f943c758a613c4/crates/compiler/src/options.rs#L13

**Comment by Keats** [comment]
I'm not planning to add configuration options for the sass compiler atm in any way

**Comment by xpe** [comment]
> I'm not planning to add configuration options for the sass compiler atm in any way

I'm a bit surprised, personally. To sum up: I provided a PR. There is a benefit to at least one user. (I doubt I'm the only one.)

Not my call to make. But if it were, the rational framing would be: benefit versus cost. Does the benefit outweigh the effort of merging the PR and maintenance? In my eyes, the cost of merging the PR is very low, expected maintenance will be very low, benefit is (admittedly) small (but not zero). For example, `-0.01` + `-0.02` + `+.1` is still positive.

**Comment by xpe** [comment]
@Keats Thanks for your work on Zola, much appreciated.

**Comment by Keats** [comment]
Thanks for the kind words!
