### ISSUE TITLE
Zola does not recognise sections

### ISSUE THREAD

**Issue by elenakrittik** [Keats/gutenberg#2496]
# Bug Report

## Environment

Zola version: 0.18.0

## Expected Behavior
Zola properly recognises the section thanks to an `_index.html` file.

## Current Behavior
Zola acts as if `content/blog/_index.html` does not exist and reports `content/blog/first.md` as an orphan.

## Step to reproduce
Clone https://github.com/elenakrittik/blog and run `zola serve`. The output will include "`Creating 1 pages (1 orphan) and 0 sections`".

**Comment by k3rni** [comment]
From the [docs](https://www.getzola.org/documentation/content/section/):

> A section is created whenever a directory (or subdirectory) in the content section contains an `_index.md` file. If a directory does not contain an `_index.md` file, no section will be created, but Markdown files within that directory will still create pages (known as orphan pages).

`_index.md`, not `_index.html`

**Comment by elenakrittik** [comment]
Oh.. Thank you and sorry! Works great now!
