### ISSUE TITLE
GitLab CI/CD gets stuck

### ISSUE THREAD

**Issue by tangruize** [Keats/gutenberg#2509]
# Documentation issue

## Summary
GitLab CI/CD gets stuck.

Error message:

This job is stuck because of one of the following problems. There are no active runners online, no runners for the [protected branch](https://docs.gitlab.com/runner/security/index.html#reduce-the-security-risk-of-using-privileged-containers), or no runners that match all of the job's tags: docker

## Proposed solution
After deleting the `docker` tag, it works.
https://github.com/getzola/zola/blob/3d0749d4782a2a9ebb2da537a056bb75839ce59a/docs/content/documentation/deployment/gitlab-pages.md?plain=1#L53-L54

**Comment by Bogay** [comment]
It seems that gitlab has changed their hosted runner tags (see this [blog post](https://about.gitlab.com/blog/2023/08/15/removing-tags-from-small-saas-runner-on-linux/)), so removing the `tags` should work.

**Comment by Keats** [comment]
Can someone do a PR?

**Comment by tangruize** [comment]
@Keats  I can do it.
