### ISSUE TITLE
Build fails if there is a mistake in commened out template code

### ISSUE THREAD

**Issue by matusf** [Keats/gutenberg#2511]
# Bug Report
Commented out templates are still beign rendered. This leads to failing build when there is a mistake in commented out code. 

## Environment

Zola version: 0.18.0

## Expected Behavior
Templated that are commented out are not templated and thus can contain mistakes / reference unfinished parts.

## Current Behavior
When you are creating a website, you experiment a lot. For example, I created a template that used data from sections that I have not yet created. The build fails, as expected. So I commented out the template where I referenced non-existing section and wanted to iterate with next part. But the build keeps failing. Eventhough the code is commented out. I'd expect that the templating engine will not try to template template that are commented out. Now the only way I can get it to work is to remove the section completely. I did not want to do that because it structure is correct, I just do not have the data. 

## Step to reproduce
This is a silly example, but it is the smallest possible where you can notice the bug. Here I create a new blog with a single template. The template has a mistake (typo) but it should be ignored because it is commented out. But it fails to build. 

```
$ zola init blog
Welcome to Zola!
Please answer a few questions to get started quickly.
Any choices made can be changed by modifying the `config.toml` file later.
> What is the URL of your site? (https://example.com): 
> Do you want to enable Sass compilation? [Y/n]: 
> Do you want to enable syntax highlighting? [y/N]: 
> Do you want to build a search index of the content? [y/N]: 

Done! Your site was created in /tmp/tmp.wGBkBD3c5R/blog
Get started by moving into the directory and using the built-in server: `zola serve`

$ cd blog
$ echo '<!-- {% block content %} {% endblosck %} -->' > ./templates/base.html
$ zola build
zola build
Building site...
Error: Failed to build the site
Error: Error parsing templates from the /templates directory
Error: Reason: 
* Failed to parse "/tmp/tmp.wGBkBD3c5R/blog/templates/base.html"
 --> 1:26
  |
1 | <!-- {% block content %} {% endblosck %} -->
  |                          ^---
  |
  = unexpected tag; expected an endblock tag (`{% endblock block_name %}` or some content
```

**Comment by Keats** [comment]
You're commenting using HTML comments. This does nothing for the template engine, comments in Tera are `{# ... #}`.

**Comment by matusf** [comment]
Yea, that works. But I'd expect (it would be nice if) the html comments to work as well. Since the file is `.html` editors assume it is html and thus use the html comment when commenting with a keyboard shortcut (like ctrl+/). Its also not something I as a user would expect.

**Comment by Keats** [comment]
That's never going to happen, we would need to parse the HTML and I don't think it works in any template language? You can also use the template engine with XML and other file type.
