### ISSUE TITLE
Unnecessary rebuilds

### ISSUE THREAD

**Issue by jimmyff** [Keats/gutenberg#2526]
I'm getting rebuilds even when no files have changed. [My site](https://github.com/jimmyff/jimmyff-website) takes around 40s to build so unnecessary rebuilds are quite annoying!

```
Change detected @ 2024-06-14 21:56:49
-> Themes changed.
```
Example - No files changed yet I need to wait for a very long rebuild.

I don't know if it's something like spotlight/google drive or something updating file metadata or something which is causing a rebuild? This isn't a new thing, Zola has done this forever for me so I figured I'd see if there is a solution!

**Comment by Keats** [comment]
Can you try the `next` branch? The notification dep has been updated and the rebuild logic has changed a bit.
I've never seen that before though, is the site on a google drive folder?

**Comment by jimmyff** [comment]
🚀 Ohhhh crikey!! this is fast!!! 🤯 What the heck -builds have gone from 40s to 1.4s! 🚀🚀

I'll use this over the weekend and report back. Great work! :-)

Update: Forgot to answer your question in all the excitement! The site isn't a google drive folder, I was just racking my brains as to what I have installed that might be causing files to appear changed despite the content staying the same.

**Comment by Keats** [comment]
Let's close it for now
