### ISSUE TITLE
Zola 0.19 config.generate_feeds not accessible from template files.

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#2537]
# Bug Report

I believe this is related to https://github.com/getzola/zola/pull/2477

## Environment

Zola version: 0.19

## Expected Behavior
config.generate_feeds accessible via templates

## Current Behavior
config.generate_feeds is not accessible

## Step to reproduce

```
git clone https://github.com/Jieiku/feeds
cd feeds
~/zola serve
```

look at the generated page and the source in templates/index.html

templates/index.html is simply:

```
{# Works in 0.18.0+: #}
  {%- if config.generate_feed %}
    0.18: {{ config.generate_feed }}
  {%- endif %}

{# Does not work in 0.19.0: #}
  {%- if config.generate_feeds %}
    0.19: {{ config.generate_feeds }}
  {%- endif %}

```

**Comment by Jieiku** [comment]
bah, bloody hell, one sec, gotta add some .gitignore to the empty folders.

**Comment by Jieiku** [comment]
This appears to actually be even stranger than I originally thought.

setting `generate_feeds = true` in `config.toml` and using zola 0.19 then makes `generate_feed` have a value of true even though it is nowhere to be found in config.toml, meanwhile `generate_feeds` is either inaccessible or false.

**Comment by Keats** [comment]
Ah yes it's mispelled in the config serializer 🤦 
```
generate_feed: options.generate_feeds,
```
I'll fix that
