### ISSUE TITLE
Zola 0.19.0 doesn't accept all valid YAML dates

### ISSUE THREAD

**Issue by kytta** [Keats/gutenberg#2538]
# Bug Report

With 0.19.0, Zola can now understand more date formats. However, I believe there is a bug in the implementation which makes the millisecond separator (but not the milliseconds) required

## Environment

Zola version: 0.19.0

## Expected Behavior
`2024-06-22 18:42:00 +02:00` should be a correct datetime

## Current Behavior
```
Error: Failed to build the site
Error: Error when parsing front matter of section `path/to/file.md`
Error: Reason: YAML deserialize error: Error("Unable to parse datetime", line: 2, column: 1)
```

If I add a single dot after the seconds (`2024-06-22 18:42:00. +02:00`), the issue goes away.

## Step to reproduce

1. Create a Markdown file with a date like `2024-06-22 18:42:00 +02:00`
2. Try to `zola build` or `zola serve`
3. Observe the error

## Possible solution

I believe there is an error in the regex:

https://github.com/getzola/zola/blob/v0.19.0/components/utils/src/de.rs#L12

As you can see, the millisecond (aka fraction) part of the string is optional, but the period is not. This contradicts the [YAML Working Draft on Timestamp](https://yaml.org/type/timestamp.html) which was mentioned in the original issue.

```diff
-    let re = Regex::new(r#"^"?([0-9]{4})-([0-9][0-9]?)-([0-9][0-9]?)([Tt]|[ \t]+)([0-9][0-9]?):([0-9]{2}):([0-9]{2})\.([0-9]*)?Z?([ \t]([-+][0-9][0-9]?)(:([0-9][0-9]?))?Z?|([-+][0-9]{2})?:([0-9]{2})?)?|([0-9]{4})-([0-9]{2})-([0-9]{2})"?$"#).unwrap();
+    let re = Regex::new(r#"^"?([0-9]{4})-([0-9][0-9]?)-([0-9][0-9]?)([Tt]|[ \t]+)([0-9][0-9]?):([0-9]{2}):([0-9]{2})(?:\.([0-9]*))?Z?([ \t]([-+][0-9][0-9]?)(:([0-9][0-9]?))?Z?|([-+][0-9]{2})?:([0-9]{2})?)?|([0-9]{4})-([0-9]{2})-([0-9]{2})"?$"#).unwrap();
```

## Additional info

Same error also happens if I omit the seconds altogether (`2024-06-22 18:42 +02:00`). I may be opinionated, but I think requiring those should be optional, too.

Relates to https://github.com/getzola/zola/issues/2071, https://github.com/getzola/zola/pull/2208

**Comment by Keats** [comment]
Can you submit the change as a PR with some additional tests?

**Comment by kytta** [comment]
@Keats will do :) would you also be interested in using named regex groups instead of indexed ones? I find it more readable and more flexible

**Comment by Keats** [comment]
Sure go for it
