### ISSUE TITLE
Alternative Content Views (Summary, List, ..., like in Hugo)

### ISSUE THREAD

**Issue by jbirnick** [Keats/gutenberg#2541]
In Hugo there is this concept of [content views](https://gohugo.io/templates/views/).

The idea is basically that in order to have e.g. a list of all blog posts, one defines once and forever, globally, different "views" of a post. The default is of course the whole page. But then you can e.g. provide a "preview" or "summary" view, which is maybe just a `<div>` with the cover image of the post and the title of the post. Then to generate e.g. a list of all blog posts, one utilizes this view by including it in the appropriate "for" loop.

The advantage is, that when one previews the posts on different parts of the web page, the style of this preview is defined at a single location in the project. For example, one can image that the "blog" section shows all blog posts, and also the home page shows e.g. the three latest posts. And one wishes to preview them in the exact same style. Then one has boilerplate code if one implements the preview HTML twice.

Now that I think about it... maybe it's even possible to imitate the same behavior in Zola as well. Is it? If so, what do you think would be the cleanest way to do that?

**Comment by Keats** [comment]
You can use Tera macros for that: https://keats.github.io/tera/docs/#macros

**Comment by welpo** [comment]
On my theme I loop over posts to show their date, permalink, tags, and summary or description ([link to the macro](https://github.com/welpo/tabi/blob/main/templates/macros/list_posts.html)). This allows me to list posts on a front page, for example.

Hope that helps~

**Comment by jbirnick** [comment]
Thanks!
