### ISSUE TITLE
Permission denied (os error 13) during build

### ISSUE THREAD

**Issue by stalkerGH** [Keats/gutenberg#2554]
# Bug Report

## Environment
Ubuntu 22.04.4
Theme: tabi

Zola version: 0.19.1

## Expected Behavior

Site builds clean.

## Current Behavior
```
$ zola build
Building site...
Checking all internal links with anchors.
> Successfully checked 1 internal link(s) with anchors.
-> Creating 19 pages (0 orphan) and 3 sections
Error: Failed to build the site
Error: Failed to create folder /blog/2
Error: Reason: Permission denied (os error 13)
```

## Step to reproduce
`zola serve` works as expected, server is running and website is displayed. Every change in file(s) forces browser to reload. But `zola build` gives an error message.

It's strange because I started to build this site about month ago and never seen anything like this. I have also another website, with other theme, and it builds with no errors. Both sites share the same root directory, all permissions are valid.

**Comment by welpo** [comment]
It looks like #2533.

In short: drop the `paginate_path` variables and everything should work as expected.

**Comment by stalkerGH** [comment]
Indeed! Magic! It works!

Thank you :)
