### ISSUE TITLE
Unknown field `date`

### ISSUE THREAD

**Issue by adfaure** [Keats/gutenberg#2558]
# Bug Report

After reading this issue on my theme: https://github.com/adfaure/kodama-theme/issues/17
It reproduced it, and it looks like `date` is not allowed in front matter anymore in `zola >= 0.19`.

The changelog mentions a change about dates (https://github.com/getzola/zola/blob/v0.19.1/CHANGELOG.md?plain=1#L17), so is it related?

Maybe I missed a piece of information and `date` is not a valid field anymore.

Thank you!

## Environment

- Zola version: tested with zola 0.19.1 and 0.19.0.
`docker run -u "$(id -u):$(id -g)" -v $PWD:/app --workdir /app ghcr.io/getzola/zola:v0.19.1 build`
- zola 0.18.0 works

## Expected Behavior
The site should build without error.

## Current Behavior

I have the following error:
```
Building site...
Error: Failed to build the site
Error: Error when parsing front matter of section `/app/content/_index.md`
Error: Reason: YAML deserialize error: Error("invalid type: string \"date = \\\"2012-10-02\\\"\", expected struct SectionFrontMatter", line: 2, column: 1)
```

with a single content file:

```
---
date: "2012-10-02"
---

Hello 
```

It also fails with toml

```
Building site...
Error: Failed to build the site
Error: Error when parsing front matter of section `/app/content/_index.md`
Error: Reason: TOML parse error at line 2, column 1
  |
2 | date = "2012-10-02"
  | ^^^^
unknown field `date`, expected one of `title`, `description`, `sort_by`, `weight`, `draft`, `template`, `paginate_by`, `paginate_reversed`, `paginate_path`, `insert_anchor_links`, `render`, `redirect_to`, `in_search_index`, `transparent`, `page_template`, `aliases`, `generate_feeds`, `extra`
```

```md
+++
date = "2012-10-02"
+++

Hello 
```

## Step to reproduce
- Create a simple site (I used zola init and added a file `content/_index.md`)
- Add a front-matter in `_index.md` with the following content:
```md
+++
date = "2012-10-02"
+++

Hello 
```
- Build the site

**Comment by Keats** [comment]
No, it's the fact that we now error on unknown fields. `date` is not a field in section front-matter so it now show you an error. Before 0.19 it would build the site but you could never access it in the templates.

**Comment by adfaure** [comment]
Thank you. I wasn't sure because the documentation shows this field (https://www.getzola.org/documentation/content/page/#front-matter)

**Comment by Keats** [comment]
That's the documentation for the page front-matter, not section front-matter
