### ISSUE TITLE
 Variable `config.feed_filename` not found in context while rendering 'section.html'

### ISSUE THREAD

**Issue by williamdes** [Keats/gutenberg#2588]
# Bug Report

## Environment

Zola version: 0.19.1

## Expected Behavior

Build my blog like before

## Current Behavior

```
> Successfully checked 0 internal link(s) with anchors.
-> Creating 36 pages (0 orphan) and 33 sections
Error: Failed to serve the site
Error: Failed to render section '/app/blog.williamdes.eu/content/OpenSource/2021/05/_index.md'
Error: Reason: Failed to render 'section.html' (error happened in 'index.html').
Error: Reason: Variable `config.feed_filename` not found in context while rendering 'section.html'
```

I updated the config this way, but the files are not created in 1.18.0. And this config does not build on 0.19.1 
```toml
generate_feeds = true
feed_filenames = ["atom.xml"]
```

## Step to reproduce

Build https://github.com/wdesportes/blog.williamdes.eu with 0.19.1

**Comment by Keats** [comment]
It's now `config.feed_filenames` in the template and it's an array

**Comment by williamdes** [comment]
> It's now `config.feed_filenames` in the template and it's an array

Yeah I have no idea why the builder says it wants the variable, I checked the HTML file and did not understand
Can you check my repo please ?

**Comment by Keats** [comment]
It would be https://github.com/wdesportes/blog.williamdes.eu/blob/main/blog.williamdes.eu/templates/index.html#L52

**Comment by williamdes** [comment]
Oh, thank you
Sorry for the disturbing.
And many thanks for Zola, it is an awesome tool !
