### ISSUE TITLE
How do I include another markdown file in `docs` markdown file?

### ISSUE THREAD

**Issue by holmofy** [Keats/gutenberg#2607]
# Bug Report

## Environment

Zola version: 0.16.1

## Expected Behavior

Thanks for zola, I am using zola as a documentation tool for my crate. Below is my project directory structure:

```sh
├── docs
    ├── config.toml
    ├── content
    │   ├── _index.md
    │   ├── blog
    │   │   ├── _index.md
    │   │   ├── spring-rs-initial-version.md
    │   ├── docs
    │   │   ├── _index.md
    │   │   ├── contributing
    │   │   │   ├── _index.md
    │   │   │   ├── code-of-conduct.md
    │   │   │   └── how-to-contribute.md
    │   │   ├── getting-started
    │   │   │   ├── _index.md
    │   │   │   ├── introduction.md
    │   │   │   └── quick-start.md
    │   │   └── help
    │   │       ├── _index.md
    │   │       └── faq.md
    │   └── privacy-policy
    │       └── _index.md
├── spring
    ├── README.md
├── spring-web
    ├── README.md
```

I want to include the spring crate's README.md file in my `getting-started/introduction.md` file to avoid duplicating it.

I tried the markdown shortcode and load_data mentioned in [issues/2346](https://github.com/getzola/zola/issues/2346). Here are some of the things I did to get it working:

1. Shortcodes are defined in `shortcodes/include.html`
  ```html
  {% set file = load_data(path=path) -%}
  {{ file }}
  ```
2. Using shortcodes in markdown file
  ```markdown
  +++
  title = "spring-web插件"
  description = "web插件如何使用"
  draft = false
  weight = 30
  sort_by = "weight"
  template = "docs/page.html"
  
  [extra]
  lead = "spring-web是基于axum实现"
  toc = true
  top = false
  +++
  
  {{ include(path="../../spring/README.md") }}
  ```

But the included markdown is rendered as the original markdown text.

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/3cd6de18-139a-4c12-ae72-b6b2b5d8493e">

I want to render the markdown into html. How can I do this?

**Comment by Keats** [comment]
Try `{{ file | markdown | safe}}`

**Comment by holmofy** [comment]
Thanks, it works fine 👍
