### ISSUE TITLE
Regression introduced in v0.19.0 to config.toml

### ISSUE THREAD

**Issue by walpox** [Keats/gutenberg#2614]
# Bug Report

## Environment

Zola version: 0.19.1

## Expected Behavior
A site which was built fine with version 0.17.2 of Zola should also be built fine with version 0.19.1, considering no changes to its files, neither to its `config.toml` file.

## Current Behavior
The Zola site, which was built with version 0.17.2, has two relevant keys defined in its `config.toml` file:

1. generate_feed
2. feed_filename

When it is attempted to build this site with version 0.19.1 of Zola, parsing errors for `config.toml` are thrown for both of those keys. It seems that the nouns of those keys now need to be written in their plural forms and that the `feed_filename(s)` key seems to have become a string array, rather than a single string.

## Step to reproduce

1. Build a site with version 0.17.2 of Zola, ensuring the `generate_feed` and the `feed_filename` keys are set explicitly to valid values.
2. Check that the site builds without errors (e.g. with `zola serve`).
3. Build the site again, this time with version 0.19.1 of Zola.
4. The `zola serve` command should throw TOML parsing errors now for `config.toml`.

## Conclusion

If Zola follows semantic versioning, wouldn't it be reasonable to consider this change to break backwards compatibility?

Thus, either implement that functionality in a way which supports backwards compatibility, or postpone it for a version 1.x.y of Zola.

I don't know much about Rust or coding yet, but I think the change was implemented in this PR:

[#2477](https://github.com/getzola/zola/pull/2477)

The problem to consider here is environments where Zola is set to auto-update on its minor and patch numbers, ignoring the major number. For example: "0.x.y".

If Zola turns out not to follow semantic versioning and this is expected behavior, my apologies in advance.

**Comment by Keats** [comment]
> If Zola follows semantic versioning, wouldn't it be reasonable to consider this change to break backwards compatibility?

It does follow semantic versioning, and you can have breaking changes in any versions before 1.0 (https://semver.org/#spec-item-4). That change bumped the `y` version to indicate the breaking changes.
You're right though that if we were after 1.0.0, we would have had to bump to 2.0.0

**Comment by walpox** [comment]
Oh, I didn't know about point of the semantic versioning spec. Thank you for clarifying.

**Comment by omalley** [comment]
I strongly advise you to change this. This change *broke* most of the themes and sites that I've looked at. That should be considered unacceptable, just like it would be for a programming language.

I'd push for accepting both the new and old strings in the config and make the feed_filename accept a string or a list of strings. These kinds of changes are really bad for your users and community.

**Comment by Keats** [comment]
The change happened almost a year ago.

>  just like it would be for a programming language.

Programming languages do breaking changes before 1.0 as well

**Comment by omalley** [comment]
When I was looking for a theme, I looked through your theme gallery and the first two that I checked were broken out of the box by this change. I ended up having to debug the breakage as my first experience. That is not a good way to welcome new comers who are investigating your product and community.

Even pre-1.0, you should take forwards and backwards compatibility seriously. Otherwise, you'll severely curtail your community's growth.
