### ISSUE TITLE
Broken rendering when using shortcodes inside code blocks

### ISSUE THREAD

**Issue by knadh** [Keats/gutenberg#2624]
# Bug Report

## Environment
OS: Fedora  40
Zola version: v0.12.2

## Expected Behavior
A shortcode that renders content inside a ``` code block ``` (single or three backticks) should render the content correctly.

## Current Behavior

Shortcodes that render content within code blocks render broken HTML with HTML-encoded `<pre>` tags.

Within single backticks:
![image](https://github.com/user-attachments/assets/3d9ed4ea-9462-426c-be46-24b57d83e4a6)

Raw HTML:
`<code>&lt;pre data-shortcode&gt;print("hello world")&lt;/pre&gt;</code>`

Within three backticks:
![image](https://github.com/user-attachments/assets/d7833903-42f1-45e3-9fd7-22ed422008f9)

Raw HTML:
```
<pre style="background-color:#1e1e1e;"><code><span style="color:#dcdcdc;">&lt;pre data-shortcode&gt;print(</span><span style="color:#d69d85;">"hello world"</span><span style="color:#dcdcdc;">)&lt;/pre&gt;
</span></code></pre>
```

## Step to reproduce

Create a shortcode file with any arbitrary content: templates/shortcodes/test.html
```
print("hello world")
```

Invoke it in a .md content file.

````markdown
```python
{{ test }}
```

or

`{{ test }}`
````

**Comment by Keats** [comment]
> Zola version: v0.12.2

Is that a typo?

**Comment by knadh** [comment]
Whoa, I somehow brain-farted and downloaded `v0.12.2` instead of the latest `v0.19.2`. This issue is not reproducible in `v0.19.2`. Thanks for pointing out!
