### ISSUE TITLE
[ feature request ] Replace Tera with Minijinja

### ISSUE THREAD

**Issue by yonas** [Keats/gutenberg#2625]
[Minijinja](https://github.com/mitsuhiko/minijinja) seems to be a bit better than Tera: https://github.com/mitsuhiko/minijinja/issues/308

**Comment by Keats** [comment]
That's not going to happen

**Comment by yonas** [comment]
Why not? Do you need help?

**Comment by Keats** [comment]
I make Tera as well so I can modify it if needed for some Zola features. That's not going to happen with a 3rd party crate
