### ISSUE TITLE
sass calc error

### ISSUE THREAD

**Issue by wicked** [Keats/gutenberg#2633]
# Bug Report

## Environment

Zola version: 0.19.2 Arch Linux

## Expected Behavior
Use Sass Calculations with multiple arguments. 

## Current Behavior
After running zola serve it errors with

```
$ zola serve
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 28 pages (0 orphan) and 0 sections
Error: Failed to serve the site
Error: Error: Only 1 argument allowed, but 3 were passed.
   ╷
58 │   max-width: calc(min(60ch, round(down, 100%, 3ch)));
   │                             ^^^^^^^^^^^^^^^^^^^^^^
   ╵
.//foo/bar/style.scss:58:29
```

## Step to reproduce

themes/theme/sass/style.scss

```
max-width: calc(min(60ch, round(down, 100%, 3ch)));
```

**Comment by Keats** [comment]
`round` in Sass only takes one argument: https://sass-lang.com/documentation/modules/math/#round

**Comment by wicked** [comment]
for zola can i use normal css instead of sass?  here is round() with some examples with multiple arguments https://developer.mozilla.org/en-US/docs/Web/CSS/round

**Comment by wicked** [comment]
figured it out and i used the static folder for my css and js files instead.
