### ISSUE TITLE
When setting the date front matter how do I specify the timezone?

### ISSUE THREAD

**Issue by Jieiku** [Keats/gutenberg#2637]
# Documentation issue

## Summary
When setting the date front matter how do I specify the timezone?

https://www.getzola.org/documentation/content/page/#front-matter
This page says to use RFC3339 and it seems to work as long as I use UTC `2022-05-17T15:00:00Z` but If I try to add the offset for my timezone `2022-05-17T15:00:00Z-07:00` then it errors out.

## Proposed solution
What is the correct way to write the date if I want it to include my timezone offset? Or is there another way to specify the timezone that I missed?

I would like to write the date in such a way that RSS feeds are accurate. If somebody uses an RSS feed aggregator to pull in multiple site feeds, I would like to ensure that my posts are displaying accurately.

Notes:

One workaround I can think of is to just set the date and time in the post frontmatter to be whatever the current UTC time is, and on linux you can check that like this:

`date --utc '+%FT%H:%M:%SZ'`

![2024-09-14_12-47-52](https://github.com/user-attachments/assets/864f7133-9f33-4e2a-80ca-00224e85a666)

I am however still curious about the timezone, and if it is possible to set it.

**Comment by Keats** [comment]
I would need to check the code but I don't think we handle timezones at all in dates in Zola

**Comment by harrymkt** [comment]
Hello @Jieiku.

It's `yyyy-mm-ddThh-mm-ssTZ`. In your case, it's `2022-05-17T15:00:00-07:00`

**Comment by Jieiku** [comment]
OH! So I just needed to drop the Z on the end when specifying the timezone, or use the Z if I am using UTC time!

I just tested it and it works perfect, Thank you!

So for UTC:

`date --utc '+%FT%H:%M:%SZ'`

This would probably also work for UTC:

`date --rfc-3339=seconds --utc | sed 's/ /T/'`

or to specify your timezone:

`date --rfc-3339=seconds | sed 's/ /T/'`
