### ISSUE TITLE
`bottom_footnotes` config adds unwanted square brackets to footnote references

### ISSUE THREAD

**Issue by asibahi** [Keats/gutenberg#2640]
Hello.

The square brackets around footnotes references applied when `bottom_footnotes` config is set is not documented anywhere, and honestly, looks ugly. They should either be removed or made as a config option.

The removal is a tiny change I made in my fork here [here](https://github.com/getzola/zola/commit/460e61a4b4bd7dc405459a7094cfb896535ca074). I did not want to create a pull request, however, without clearing that it is ok to do so.

The additional config option would be a bit more involved: Upgrade the `bottom_footnotes` config to an enum with `Default`, `Bottom`, `Github-style` etc.

**Comment by Keats** [comment]
@totikom any idea why the brackets are there?

**Comment by totikom** [comment]
> @totikom any idea why the brackets are there?

They were initially used in "gh-style", but they can be safely removed.
The patch by @asibahi is a correct way to do it.

**Comment by Keats** [comment]
They don't seem used by GH itself so I think a PR to remove them is fine

**Comment by totikom** [comment]
> They don't seem used by GH itself so I think a PR to remove them is fine

Yep, it is totally ok.
