### ISSUE TITLE
page_or_section.title

### ISSUE THREAD

**Issue by leotsarev** [Keats/gutenberg#2649]
# Feature Request

## Environment

Zola version: 0.19.2

## Expected Behavior
There is a lot of common properties between page and section. To name a few, there is `title`, `description`, `path`, `permalink` etc etc

For example, I want to add `<meta property="og:title" content="{{ page_or_section.title }}"/>` into base template, but I can't: I have to implement in two times: for pages and for sections, add somekind of "extrahead" block, etc etc

What I want is ability to use common properties of page/section by common interface.

**Comment by ARitz-Cracker** [comment]
I agree (as a user) that this may be useful, though if you'd like a workaround, I have this in my `base.html`
```
<!DOCTYPE html>
{% if page.title %}
	{% set page_title = page.title %}
{% elif section.title %}
	{% set page_title = section.title %}
{% else %}
	{% set page_title = "[NO TITLE]" %}
{% endif %}
{% if page.description %}
	{% set page_description = page.description %}
{% elif section.description %}
	{% set page_description = section.description %}
{% else %}
	{% set page_description = "[NO DESCRIPTION]" %}
{% endif %}
<html lang="en">
<head>
	<title>{{page_title}} - My Website</title>
	<meta property="description" content="{{ page_description }}">
	...
```

**Comment by Keats** [comment]
See https://zola.discourse.group/t/proposal-deprecate-sections/1968

I'm going to close this issue as it's already being discussed on the forum but eventually it will happen

**Comment by leotsarev** [comment]
@ARitz-Cracker thanks! I also have similar workaround, but it will be handy to have it in product

@Keats thanks, I think that "deprecate sections" is good idea. At least it fits well into my mental model :-) 

P.S. And another opportunity to say "thx" for Zola
