### ISSUE TITLE
Confusion around base_url

### ISSUE THREAD

**Issue by dmarcoux** [Keats/gutenberg#2650]
Hello,

my [website](https://dmarcoux.com) is built with Zola (https://github.com/dmarcoux/dmarcoux.com). Thank you for the project!

I have a CI pipeline with preview deploys on Cloudflare in my PRs. In `config.toml`, I first set `base_url = "https://dmarcoux.com`, but it didn't load my assets from a relative path in the preview deploys. So I found this hack from one of the GitHub issues, `base_url = "/"`. The assets were then correctly loaded. However now, I would like to rely on `current_url` for canonical links and it is obviously going to be `/some/url`, instead of https://dmarcoux.com/some/url`.

As [recommended by Cloudflare](https://developers.cloudflare.com/pages/framework-guides/deploy-a-zola-site/), I cannot use `base_url = "https://my-zola-project.pages.dev"` since it would be the wrong URL as I want to use my domain.

How can I fix this?

**Comment by dmarcoux** [comment]
I found a way around this by overriding the environment variable `CF_PAGES_URL` in the Cloudflare Pages UI for the production environment only, and then using the build command `zola build --base-url $CF_PAGES_URL`.

**Comment by Keats** [comment]
The `--base-url` parameter exists precisely for previews app
