### ISSUE TITLE
resize_image not working when images are ignored via ignored_content

### ISSUE THREAD

**Issue by azbestoid** [Keats/gutenberg#2658]
# Bug Report

## Environment

Zola version: 0.19.2
OS: macOS 14.5
Processor architecture: arm

## Expected Behavior
When using the ```resize_image``` function, Zola should process and resize images even if original images are excluded from the build via ```ignored_content``` in the config. Resized images should appear in the final build and original images should be discarded. 

## Current Behavior
When images are included in the ```ignored_content``` list (for example: ```ignored_content = ["**/blog/**/*.{jpg,png}"]```), Zola doesn't resize them. Instead, they're ignored and resized images are not present in ```processed_images``` after running ```zola build``` or ```zola serve```. This issue has been addressed in #481 and #1701 but I couldn't get it to work properly. It seems like ignoring the content happens before proccesing any assets.

## Steps to reproduce

1. Create a content structure similar to this (doesn't matter if it's a post or any other page)
```
├── content
│   └── blog
│       ├── _index.md
│       ├── post
│       │   ├── image.png
│       │   └── index.md
│       └── second-post
│           ├── index.md
│           └── other-image.jpg
```

2. Use the gallery shortcode inside posts' ```index.md```

shortcodes/gallery.html
```html
<div>
{% for asset in page.assets -%}
  {%- if asset is matching("[.](jpg|png)$") -%}
    {% set image = resize_image(path=asset, width=240, height=180) %}
    <a href="{{ get_url(path=asset) }}" target="_blank">
      <img src="{{ image.url }}" />
    </a>
  {%- endif %}
{% endfor %}
</div>
```

content/blog/post/index.md
```md
+++
title = "Post"
date = 2024-09-27
+++

{{ gallery() }}
```

3. In ```config.toml``` add ```ignored_content``` line
```toml
ignored_content = ["**/blog/**/*.{jpg,png}"]
```

4. Run ```zola build``` or ```zola serve```

**Comment by Keats** [comment]
Ignoring content removes them from the assets list so it's not showing up in your shortcode, nothing to do with resize_image
