### ISSUE TITLE
google can't fetch my sitemap

### ISSUE THREAD

**Issue by Smart-SangGe** [Keats/gutenberg#2670]
# Bug Report

## Environment

Zola version: 0.18.0

## Expected Behavior
google should fetch my sitemap

## Current Behavior
google can't fetch my sitemap. https://blog.mamahaha.work/sitemap.xml
The error in google search console is Sitemap could not be read.
But in Indexed pages, it seems indexed sitemap and all other pages.
I also have tried some sitemap checker, but nothing goes wrong.

## Step to reproduce
It's pretty hard to reproduce. Only google show this error.

**Comment by Keats** [comment]
I don't think it's a zola issue since we can access it manually.

**Comment by Smart-SangGe** [comment]
It's weird but whatever, I can google my site by manually add sitemap to the indexed pages :-).
