### ISSUE TITLE
get_url returns wrong value

### ISSUE THREAD

**Issue by brianmay** [Keats/gutenberg#2681]
# Bug Report

## Environment

Zola version: 0.19.2

## Expected Behavior

The example at https://www.getzola.org/documentation/content/image-processing/#creating-picture-galleries has:

```
<div>
{% for asset in page.assets -%}
  {%- if asset is matching("[.](jpg|png)$") -%}
    {% set image = resize_image(path=asset, width=240, height=180) %}
    <a href="{{ get_url(path=asset) }}" target="_blank">
      <img src="{{ image.url }}" />
    </a>
  {%- endif %}
{%- endfor %}
</div>
```

But when I try to use it, the `get_url(...)` gives the wrong URL.

In my test case I expected to see:
http://127.0.0.1:1111/people/frank-may/funeral_page_1.png

But I actually got
http://127.0.0.1:1111/people/Frank_May/funeral_page_1.png

This gives a 404 error.

This is for a reference from `content/people/Frank_May/index.md` to `content/people/Frank_May/funeral_page_1.png`.

I suspect the problem is the underscore in the section directory name.

**Comment by Keats** [comment]
I believe it's the same issue as https://github.com/getzola/zola/issues/2598

**Comment by brianmay** [comment]
Looks like it. Closing this bug report.
