### ISSUE TITLE
Add support for hide front matter from in markdown source

### ISSUE THREAD

**Issue by LitoMore** [Keats/gutenberg#2682]
Currently we can only use `+++` and `---` to define front matter. Both of these methods will display a not-so-good-looking header on the markdown preview page.

How about allowing `+++` and `---` to use a format to hide them?

Something like the blow:

```markdown
<!--
+++
title = "Still working" 
+++
-->
```

```markdown
<!--
---
title = "Still working"
---
-->
```

```markdown
<!--+
title = "Still working"
+-->
```

```markdown
<!---
title = "Still working"
--->
```

What do you think?

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Keats** [comment]
I don't think it would be an improvement

**Comment by LitoMore** [comment]
@Keats It's OK. Thank you for your response.
