### ISSUE TITLE
Add icon support to the atom.xml

### ISSUE THREAD

**Issue by LitoMore** [Keats/gutenberg#2683]
As https://www.ietf.org/rfc/rfc4287.txt documented, we can use an `icon` field to specify the icon for the RSS source.

**Comment by Keats** [comment]
That's the kind of thing where people should probably write their own template for the atom.xml I think

**Comment by LitoMore** [comment]
OK, thank you for your response. Current simple configuration is also good direction.

Users can always customize their formats with their own template.

Closing.
