### ISSUE TITLE
Confusion regarding resize_image()

### ISSUE THREAD

**Issue by da-shalev** [Keats/gutenberg#2709]
### Confusion regarding resize_image

` {% set image = resize_image(path=path, width=(mdata.width), height=(mdata.height), format="webp", quality=65)  %}`

I am trying to find the image.path, why is this not available? There is .static_path, as I read in the source code, but it outputs the same result as image.url. Getting the root path is useful, but in my case, I would prefer the root-relative path, which is easy enough to get. However, it would be nice to be able to get it with image.path.

**URL**
`http://127.0.0.1:1111/processed_images/kitchen.8a61beaa16b6e536.webp`

**What I would perfer with .path**
`/processed_images/kitchen.8a61beaa16b6e536.webp`

**Comment by Keats** [comment]
Seems like a bug that it would output the url for the static_path

**Comment by da-shalev** [comment]
Thanks for confirming that static_path is supposed to work as I initially thought. It works now, I guess I forgot to restart zola serve, and that’s why I opened the bug report? My bad.

However, I’m now getting `/static/processed_images/`, even though in the zola build, `/processed_images/` is the correct location. No biggie, just keep this in mind.

`src="/{{ image.static_path | replace(from='static/',to='') }}"` slightly inconvenient lmk if I'm just using it wrong
