### ISSUE TITLE
Add code-theme: Tokyonight(-storm)

### ISSUE THREAD

**Issue by TornaxO7** [Keats/gutenberg#2714]
Would be nice to have this theme https://github.com/tokyo-night/tokyo-night-vscode-theme?tab=readme-ov-file

If I've understand its README correctly, the relevant sublime text theme can be found here: https://packagecontrol.io/packages/Enki%20Theme

**Comment by Keats** [comment]
For now we are putting adding themes on hold until there's some clarity on the highlighter. It's easy to add your own highlighting theme on a site though

**Comment by TornaxO7** [comment]
okidoki
