### ISSUE TITLE
Enable blockquote tags

### ISSUE THREAD

**Issue by spectria-limina** [Keats/gutenberg#2719]
Pulldown now supports blockquote tags with the [`ENABLE_GFM`](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/struct.Options.html#associatedconstant.ENABLE_GFM) feature. Please enable this in Zola or add a feature to enable it.

**Comment by Keats** [comment]
Those look like it could easily be replaced by shortcodes? What is even the output of those in pulldown-cmark? Looking at https://github.com/pulldown-cmark/pulldown-cmark/blob/f8a7e4b727b980f1d39d749a10eefcad71dd0432/pulldown-cmark/tests/suite/blockquotes_tags.rs it seems it just adds some classes to the wrapping container?

**Comment by spectria-limina** [comment]
They could be shortcodes, but shortcodes aren't very suitable for large blocks of text, especially when it's markdown.

But a more flexible approach for block styling would be welcome too.

**Comment by Keats** [comment]
> but shortcodes aren't very suitable for large blocks of text, especially when it's markdown.

Can you expand on that?

**Comment by spectria-limina** [comment]
Maybe it's just me but having to put potentially multiple paragraphs of text inside a string literal of a shortcode looks weird to me. And while I don't directly have a usecase for this right now, shortcodes don't have access to page context which I think is more and more likely to become a pain point the longer the contents.

**Comment by Keats** [comment]
Shortcodes do have page context available and in this case it would look like:

```
{% blockquote(type="info") %}
The content of my blockquote. Could also be **markdown** if i wanted.
{% end %}
```

**Comment by spectria-limina** [comment]
Oh, I must have been working on outdated information. Thanks.

**Comment by spectria-limina** [comment]
I forgot to clos  this
