### ISSUE TITLE
Question: zola build css read from base_url, but zola serve works with local css change?

### ISSUE THREAD

**Issue by AnatolyBuga** [Keats/gutenberg#2722]
# Bug Report

## Environment

Zola version: latest

## Expected Behavior
I have cloned a [template repo](https://github.com/mattimustang/zola-grayscale) 

Because I want to make minor changes to css and templates/index.html. See [changes here](https://github.com/AnatolyBuga/finestway2/commit/0bbb67e2d8d90d4de25538483499ab787142b63e) 

## Current Behavior
- `zola build` does **not** read/see my local css changes at all. 
- if I change `base_url` in config.toml - `zola build` is a completely broken html 
![image](https://github.com/user-attachments/assets/359ebc33-fb5b-4e05-8424-653b240ef01d)
- `zola serve` always works well: it loads local css and is indifferent to base_url

## Step to reproduce
change css, change base_url

## Update:
I found this very similar issue, it talks about nginx config etc which I do not have...
https://zola.discourse.group/t/style-broken-with-zola-build-while-zola-serve-works-fine/2296/9
This article recommends providing base_url which [I have done](https://github.com/AnatolyBuga/finestway/blob/main/config.toml#L2):
https://zola.discourse.group/t/my-zola-deployment-via-cloudflare-pages-is-successful-but-theme-and-style-is-broken/1912

**Comment by Keats** [comment]
Looks like you got your answer in https://zola.discourse.group/t/zola-serve-works-but-zola-build-doesnt-with-custom-css/2400
