### ISSUE TITLE
Zola standalone "template"

### ISSUE THREAD

**Issue by gruvw** [Keats/gutenberg#2725]
Hey there, thank you for creating and maintaining Zola.

While creating my website, I ran into an issue where I wanted to create an HTML page that extended a particular template, but that will be used only once.  
I achieved this by creating a new template for that page and linking it with a `content/section/index.md` file that just links to that new template.

However, this approach has two problems:

1. My new page is not really a template of any kind, as it will be used only once as a plain HTML page.
2. I have to create two files every time I want to create that type of page (one template and one `.md` file).

Would it be possible to create a new page using HTML directly, without having to go through the creation of a template ?
Something like `content/section/index.html` where that file extends a template ?

If not, is there a way to create a plain HTML page that extends a template using another technique without having to go through the two issues mentioned above?

Thank you a lot for taking the time to answer me.

**Comment by Keats** [comment]
Creating the 2 files is the intended way, no way around it that I'm aware. You could maybe just have HTML in the .md file with a special template in the front-matter if all your pages are the same but it's not great for syntax highlighting

**Comment by gruvw** [comment]
Ok, but in that particular use case don't you think it would make sense to have a standalone template system ?

Like being able to create an ".html" file directly in the content directory ?

From my point of view, that would make a lot of sense.

**Comment by Keats** [comment]
Not really imo. It makes the handling of the content much more complex and it's less powerful than having 2 files since you won't be able to set front matter, which was mentioned as desirable the last time someone wanted html in the content folder.
