### ISSUE TITLE
config variable not language aware

### ISSUE THREAD

**Issue by huanie** [Keats/gutenberg#2727]
# Bug Report

## Environment

Zola version: v0.19.2 and master branch

## Expected Behavior

``{{ config | json_encode(pretty=true) | safe  }}``
should contain the language of the current page/section not the other languages.

Is this maybe the desired behavior? The fix is really simple: https://github.com/huanie/zola/commit/dd68a1a3c6d6f969d631fd8f881c8b3430981a64

## Step to reproduce
1. Add translations
2. Create a page of any language
3. Inspect config variable

[blog.zip](https://github.com/user-attachments/files/18042912/blog.zip)

**Comment by Keats** [comment]
That's expected? When you are for example on the English version, you want to know what other languages are available. All the data for the current lang will be found directly in the config, no need to repeat it in the languages field
