### ISSUE TITLE
[ feature request ]: Icons

### ISSUE THREAD

**Issue by mahyarmirrashed** [Keats/gutenberg#2728]
It would be lovely to be able to easily add icons into the project through something like Font Awesome or Lucide Icons.

**Comment by Keats** [comment]
What exactly is needed from Zola for that? You can use them pretty easily already

**Comment by mahyarmirrashed** [comment]
I'm just not sure how to do it at the moment @Keats. Any examples online?

**Comment by Keats** [comment]
Something like https://docs.fontawesome.com/web/setup/host-yourself/webfonts

**Comment by mahyarmirrashed** [comment]
Is it possible to have an example in the documentation somewhere?
