### ISSUE TITLE
minify_html generate broken JavaScript

### ISSUE THREAD

**Issue by st1020** [Keats/gutenberg#2731]
# Bug Report

## Environment

Zola version: 0.19.2

## Expected Behavior
Minifying the HTML should generate right JavaScript.

## Current Behavior
Minifying the HTML generated broken javascript.

## Step to reproduce

Here is an example, the following HTML is minimized to:

```html
<script>
  document.addEventListener("DOMContentLoaded", () =>
    renderMathInElement(document.body, {
      delimiters: [
        { left: "$$", right: "$$", display: true },
        { left: "$", right: "$", display: false },
      ],
      throwOnError: false,
    }),
  );
</script>
```

```html
<script>document.addEventListener(`DOMContentLoaded`,()=>renderMathInElement(document.body,{delimiters:[{left:a,right:a,display:!0},{left:b,right:b,display:!1}],throwOnError:!1}))</script>
```

This is an error of [minify-html](https://github.com/wilsonzlin/minify-html), maybe we should:

1. Use the latest minify-html from the master branch.
2. Do not minifying JS:
    https://github.com/getzola/zola/blob/01c5b4d4b18b9a44d2890de5180a6dc7fe6e055a/components/site/src/minify.rs#L8
3. Or just wait the minify-html release a new version (but it hasn't been updated for a year).

**Comment by Keats** [comment]
I guess https://github.com/wilsonzlin/minify-html/issues/197 is related. We should probably not minify JS then

**Comment by st1020** [comment]
Yes, in particular minify-html seems to be poorly maintained. We can hardly expect a new version of it in the short term.
